### PR TITLE
FEATURE: new site setting 'max_emojis_in_title'

### PR DESCRIPTION
**Pull request by techAPJ**
https://meta.discourse.org/t/allow-me-to-disable-emojis-in-topic-titles/76747/

### CODE REVIEW

**Comment by techAPJ** [comment]
Build failure is unrelated.

**Comment by ZogStriP** [comment]
LGTM 👍

**Comment by jjaffeux** [comment]
@techAPJ LGTM but might be good to add a :woman:t5: in one of the tests to be sure the regex is working with skin tones and not producing a false positive.

**Comment by techAPJ** [comment]
@jjaffeux Good point, done. 👍

**Pull request merged**
