### PR TITLE
FIX: Create readonly functions during backup

### PR DESCRIPTION
**Pull request by gschlager**
Temporarily recreate already dropped functions in the discourse_functions schema in order to allow restoring of backups which still reference dropped functions.

### CODE REVIEW

**Comment by eviltrout** [comment]
Does this mean in the future we must create the constants `DROPPED_TABLES`, `DROPPED_COLUMNS` in order for things to work properly?

**Comment by gschlager** [comment]
Yes, exactly. I couldn't think of another way of knowing which functions to create. Now that you mention it I could add a spec that ensures that post migrations contain the right constants when `ColumnDropper` or `TableDropper` are used. That should prevent mistakes in most cases.

**Comment by gschlager** [comment]
I went ahead and added specs to check the post migrations.

**Comment by eviltrout** [comment]
This is definitely better, but I wonder if there's a way we could query directly as a result of the ColumnDropper calls? Could those calls set some class variables in a certain context and then allow us to check those variables?

**Comment by gschlager** [comment]
That's actually a good idea! The migrations aren't running during the restore, but I guess I could load them as I do right now and execute the `up` or `change` method. Running them in a block that makes the `execute_drop` calls only record the table and column names should be possible. I can give it another go.

**Comment by gschlager** [comment]
Actually, that won't work. There's other code in some of those migrations and I can't blindly execute all post migrations. :/

**Comment by eviltrout** [comment]
Ah too bad. Was worth a look though!

**Pull request merged**
