### PR TITLE
gravatar settings and global env

### PR DESCRIPTION
**Pull request by fantasticfears**
- Added the `enable_gravatar` to enable local gravatar images storage
- Rename `automatically_download_gravatars` to `automatically_refresh_gravatars`, also change the scheduled job to refresh gravatars
- Using GlobalSetting.gravatar_url(DISCOURSE_GRAVATAR_URL) to download gravatars.
- Avatar selector UI now reflects the site settings.
- FIX: the uploaded custom avatar can not be save

**DEPENDS ON: [discourse_docker PR 117][1]**

  [1]: https://github.com/discourse/discourse_docker/pull/117

### CODE REVIEW

**Comment by fantasticfears** [comment]
Updated.

**Comment by coding-horror** [comment]
@ZogStriP can we merge this if it is good?

**Comment by SamSaffron** [comment]
This all feels odd to me, where is the discussion that explains all the issues this is solving?

**Comment by ZogStriP** [comment]
@SamSaffron I believe it's to get around the Great China Wall

**Comment by fantasticfears** [comment]
@SamSaffron Not mentioned that on meta. And yes, prefix part is because of GFW

**Comment by fantasticfears** [comment]
@SamSaffron I am OK to remove the gravatar prefix. Then the PR would be adding a site setting to disable gravatar .

**Comment by coding-horror** [comment]
Can this be resolved and merged or are there still issues?

**Comment by ZogStriP** [comment]
Closing this since there's too much changes packed in the same PR. @fantasticfears would you mind make several small PR so that we can review them more easily?

**Pull request closed without merging**
