### PR TITLE
Fix same domains links on subfolder installs

### PR DESCRIPTION
**Pull request by xfalcox**
isInternal link handling logic needs to test if the link is inside the same subfolder

### CODE REVIEW

**Comment by riking** [comment]
Travis failure is unrelated.

**Comment by xfalcox** [comment]
Maybe we should add tests for subfolder detection? And I signed the CLA already...

**Comment by nlalonde** [comment]
Good catch. Your change removes the `http(s?)://` and adds a trailing slash at the end. Not sure if it matters, but to strictly keep the same behaviour this should do the trick:

```
window.location.origin + (Discourse.BaseUri === "/" ? '' : Discourse.BaseUri)
```

**Comment by xfalcox** [comment]
Thx @nlalonde ! Fixed it and added some tests.

**Comment by nlalonde** [comment]
Thanks! :+1:

**Pull request merged**
