### PR TITLE
DEV: makes main scss colors accessible from js

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by ZogStriP** [comment]
Does it need to be available "everywhere"? I mean, can't this be an admin-only thing?

**Comment by eviltrout** [comment]
I agree with Regis, that this should only be exposed on the admin side of things.

**Comment by SamSaffron** [comment]
what is the specific use case here?

**Comment by SamSaffron** [comment]
Yeah I say we close this for now, I don't really like it that our JS has this knowledge

**Pull request closed without merging**
