### PR TITLE
A11Y: Don't mark multiple form labels as applying to the same element

### PR DESCRIPTION
**Pull request by pmusaraj**
This was raised in a client's accessibility review.

### CODE REVIEW

**Comment by CvX** [comment]
If those `<label>`s can't have `for` attribute, then probably they shouldn't be labels but `<span>`s or something.

**Comment by pmusaraj** [comment]
Yeah, that's reasonable. @jordanvidrine (since you last worked on this), thoughts?

**Comment by jordanvidrine** [comment]
> Yeah, that's reasonable. @jordanvidrine (since you last worked on this), thoughts?

That should be fine, I can take a look next week.

**Comment by jordanvidrine** [comment]
@pmusaraj Got this done, tested locally and looks fine.

**Comment by pmusaraj** [comment]
Awesome, thanks Jordan! @CvX can you review (and approve, if all is good)?

**Review by CvX — APPROVED** [review]

**Pull request merged**
