### PR TITLE
Add belarusian locale

### PR DESCRIPTION
**Pull request by kirylpl**
This link is not available now https://meta.discourse.org/t/how-to-add-a-new-language/14970
So it's not clear how to add new language.
Feel free to correct me and I'll update PR.

### CODE REVIEW

**Comment by gschlager** [comment]
> This link is not available now https://meta.discourse.org/t/how-to-add-a-new-language/14970

That guide must have been deleted by accident. Sorry about that. It's back.

**Comment by SamSaffron** [comment]
@nlalonde  is this safe to merge?

**Comment by nlalonde** [comment]
No, Discourse fails to start up with this change. Many of the translations in these files aren't in Transifex, and many files are missing. I tried pulling the missing files from Transifex, but Discourse still has javascript errors with this locale.

**Comment by SamSaffron** [comment]
@gschlager can you take this over and help get the locale in to Discourse?

**Comment by gschlager** [comment]
Merged in https://github.com/discourse/discourse/commit/a5e80079d6bbc0a14b4b2862d82924e3b5b0aee6

@kirylpl `rake i18n:check[be]` shows a huge amount of errors in the translations. Please try to fix them on Transifex. Transifex makes it really easy to correctly insert interpolation keys by clicking on the keys in the English texts.

```
================================================================================
config/locales/client.be.yml
================================================================================
js.dates.medium.x_minutes [few] -- Missing interpolation keys: ["count"]
js.dates.medium.x_minutes [few] -- Unsupported interpolation keys: ["Count"]
js.dates.medium.x_minutes [many] -- Missing interpolation keys: ["count"]
js.dates.medium.x_minutes [many] -- Unsupported interpolation keys: ["Count"]
js.dates.medium.x_minutes [other] -- Missing interpolation keys: ["count"]
js.dates.medium.x_minutes [other] -- Unsupported interpolation keys: ["Count"]
js.dates.medium.x_hours [few] -- Missing interpolation keys: ["count"]
js.dates.medium.x_hours [few] -- Unsupported interpolation keys: ["Count"]
js.dates.medium.x_hours [many] -- Missing interpolation keys: ["count"]
js.dates.medium.x_hours [many] -- Unsupported interpolation keys: ["Count"]
js.dates.medium.x_hours [other] -- Missing interpolation keys: ["count"]
js.dates.medium.x_hours [other] -- Unsupported interpolation keys: ["Count"]
js.dates.medium.x_days [few] -- Missing interpolation keys: ["count"]
js.dates.medium.x_days [few] -- Unsupported interpolation keys: ["Count"]
js.dates.medium.x_days [many] -- Missing interpolation keys: ["count"]
js.dates.medium.x_days [many] -- Unsupported interpolation keys: ["Count"]
js.dates.medium.x_days [other] -- Missing interpolation keys: ["count"]
js.dates.medium.x_days [other] -- Unsupported interpolation keys: ["Count"]
js.dates.medium_with_ago.x_hours [many] -- Missing interpolation keys: ["count"]
js.dates.medium_with_ago.x_hours [many] -- Unsupported interpolation keys: ["Count"]
js.dates.medium_with_ago.x_hours [other] -- Missing interpolation keys: ["count"]
js.dates.medium_with_ago.x_hours [other] -- Unsupported interpolation keys: ["Count"]
js.dates.medium_with_ago.x_days [many] -- Missing interpolation keys: ["count"]
js.dates.medium_with_ago.x_days [many] -- Unsupported interpolation keys: ["Count"]
js.dates.medium_with_ago.x_days [other] -- Missing interpolation keys: ["count"]
js.dates.medium_with_ago.x_days [other] -- Unsupported interpolation keys: ["Count"]
js.character_count [one] -- Unsupported interpolation keys: ["Count"]
js.character_count [few] -- Missing interpolation keys: ["count"]
js.character_count [few] -- Unsupported interpolation keys: ["Count"]
js.character_count [many] -- Missing interpolation keys: ["count"]
js.character_count [many] -- Unsupported interpolation keys: ["Count"]
js.character_count [other] -- Missing interpolation keys: ["count"]
js.character_count [other] -- Unsupported interpolation keys: ["Count"]
js.user_action.user_posted_topic -- Missing interpolation keys: ["topicUrl"]
js.user_action.you_posted_topic -- Missing interpolation keys: ["topicUrl"]
js.user_action.user_replied_to_post -- Missing interpolation keys: ["postUrl", "post_number"]
js.user_action.you_replied_to_post -- Missing interpolation keys: ["postUrl", "post_number"]
js.user_action.user_replied_to_topic -- Missing interpolation keys: ["topicUrl"]
js.user_action.you_replied_to_topic -- Missing interpolation keys: ["topicUrl"]
js.user_action.user_mentioned_user -- Missing interpolation keys: ["user2Url", "another_user"]
js.user_action.user_mentioned_you -- Missing interpolation keys: ["user2Url"]
js.user_action.you_mentioned_user -- Missing interpolation keys: ["user2Url", "another_user"]
js.directory.total_rows [one] -- Unsupported interpolation keys: ["Count"]
js.directory.total_rows [few] -- Missing interpolation keys: ["count"]
js.directory.total_rows [few] -- Unsupported interpolation keys: ["Count"]
js.directory.total_rows [many] -- Missing interpolation keys: ["count"]
js.directory.total_rows [many] -- Unsupported interpolation keys: ["Count"]
js.directory.total_rows [other] -- Missing interpolation keys: ["count"]
js.directory.total_rows [other] -- Unsupported interpolation keys: ["Count"]
js.user.said -- Missing interpolation keys: ["username"]
js.user.said -- Unsupported interpolation keys: ["Username"]
js.password_reset.continue -- Missing interpolation keys: ["site_name"]
js.notifications.popup.confirm_title -- Missing interpolation keys: ["site_title"]
js.topic.read_more -- Missing interpolation keys: ["catLink"]
js.topic.read_more -- Unsupported interpolation keys: ["CatLink"]
js.posts_long -- Missing interpolation keys: ["number"]
js.changed_by -- Missing interpolation keys: ["author"]
js.changed_by -- Unsupported interpolation keys: ["Author"]
js.filters.category.title -- Missing interpolation keys: ["categoryName"]
js.filters.category.title -- Unsupported interpolation keys: ["CategoryName"]
js.keyboard_shortcuts_help.navigation.open -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.application.create -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.application.notifications -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.share_post -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.reply_post -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.quote_post -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.like -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.flag -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.bookmark -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.edit -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.delete -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.mark_muted -- Missing interpolation keys: ["shortcut"]
js.keyboard_shortcuts_help.actions.mark_tracking -- Missing interpolation keys: ["shortcut"]
admin_js.admin.user.send_activation_email_failed -- Missing interpolation keys: ["error"]
admin_js.admin.user.send_activation_email_failed -- Unsupported interpolation keys: ["Error"]
admin_js.admin.badges.no_user_badges -- Missing interpolation keys: ["name"]
admin_js.admin.badges.no_user_badges -- Unsupported interpolation keys: ["Name"]

================================================================================
config/locales/server.be.yml
================================================================================
themes.settings_errors.number_value_not_valid_max -- Missing interpolation keys: ["max"]
themes.settings_errors.string_value_not_valid_min_max -- Missing interpolation keys: ["min", "max"]
themes.settings_errors.string_value_not_valid_min -- Missing interpolation keys: ["min"]
themes.settings_errors.string_value_not_valid_max -- Missing interpolation keys: ["max"]
education.avatar -- Missing interpolation keys: ["profile_path"]
site_settings.version_checks -- Missing interpolation keys: ["base_path"]
sso.email_error -- Missing interpolation keys: ["email"]
login.suspended_with_reason -- Missing interpolation keys: ["date", "reason"]
login.already_logged_in -- Missing interpolation keys: ["current_user"]
user.deactivated -- Missing interpolation keys: ["email"]
unsubscribe_mailer.subject_template -- Missing interpolation keys: ["site_title"]
system_messages.email_reject_invalid_access.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_invalid_access.text_body_template -- Missing interpolation keys: ["destination", "former_title", "base_url"]
system_messages.email_reject_strangers_not_allowed.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_strangers_not_allowed.text_body_template -- Missing interpolation keys: ["destination", "former_title", "base_url"]
system_messages.email_reject_invalid_post.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_invalid_post.text_body_template -- Missing interpolation keys: ["destination", "former_title"]
system_messages.email_reject_invalid_post_specified.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_invalid_post_specified.text_body_template -- Missing interpolation keys: ["destination", "former_title", "post_error"]
system_messages.email_reject_post_too_short.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_post_too_short.text_body_template -- Missing interpolation keys: ["destination", "former_title", "count"]
system_messages.email_reject_invalid_post_action.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_invalid_post_action.text_body_template -- Missing interpolation keys: ["destination", "former_title"]
system_messages.email_reject_reply_key.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_reply_key.text_body_template -- Missing interpolation keys: ["destination", "former_title", "base_url"]
system_messages.email_reject_bad_destination_address.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_bad_destination_address.text_body_template -- Missing interpolation keys: ["destination", "former_title"]
system_messages.email_reject_old_destination.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_old_destination.text_body_template -- Missing interpolation keys: ["destination", "former_title", "number_of_days", "short_url"]
system_messages.email_reject_topic_not_found.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_topic_not_found.text_body_template -- Missing interpolation keys: ["destination", "former_title", "base_url"]
system_messages.email_reject_topic_closed.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_topic_closed.text_body_template -- Missing interpolation keys: ["destination", "former_title", "base_url"]
system_messages.email_reject_auto_generated.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_auto_generated.text_body_template -- Missing interpolation keys: ["destination", "former_title", "base_url"]
system_messages.email_reject_unrecognized_error.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_unrecognized_error.text_body_template -- Missing interpolation keys: ["destination", "former_title", "base_url"]
system_messages.email_reject_attachment.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_reject_attachment.text_body_template -- Missing interpolation keys: ["destination", "former_title", "rejected_errors", "base_url"]
system_messages.email_error_notification.subject_template -- Missing interpolation keys: ["email_prefix"]
system_messages.email_error_notification.text_body_template -- Missing interpolation keys: ["base_url"]
system_messages.email_revoked.text_body_template -- Missing interpolation keys: ["base_url"]
system_messages.email_bounced -- Missing interpolation keys: ["email", "raw"]
system_messages.too_many_spam_flags.text_body_template -- Missing interpolation keys: ["site_name", "base_url"]
system_messages.too_many_tl3_flags.text_body_template -- Missing interpolation keys: ["site_name", "base_url"]
system_messages.silenced_by_staff.text_body_template -- Missing interpolation keys: ["site_name", "base_url"]
system_messages.user_automatically_silenced.subject_template -- Missing interpolation keys: ["username"]
system_messages.user_automatically_silenced.text_body_template -- Missing interpolation keys: ["username", "user_url", "base_url"]
system_messages.spam_post_blocked.subject_template -- Missing interpolation keys: ["username"]
system_messages.spam_post_blocked.text_body_template -- Missing interpolation keys: ["username", "user_url", "domains"]
system_messages.unsilenced.text_body_template -- Missing interpolation keys: ["site_name"]
system_messages.pending_users_reminder.text_body_template -- Missing interpolation keys: ["base_url"]
system_messages.dashboard_problems.text_body_template -- Missing interpolation keys: ["base_url"]
system_messages.new_user_of_the_month.text_body_template -- Missing interpolation keys: ["month_year", "url"]
unsubscribe_link -- Missing interpolation keys: ["unsubscribe_url"]
unsubscribe_link_and_mail -- Missing interpolation keys: ["unsubscribe_url"]
unsubscribe_mailing_list -- Missing interpolation keys: ["unsubscribe_url"]
email_from -- Missing interpolation keys: ["user_name", "site_name"]
user_notifications.reply_by_email -- Missing interpolation keys: ["base_url", "url"]
user_notifications.reply_by_email_pm -- Missing interpolation keys: ["base_url", "url", "participants"]
user_notifications.only_reply_by_email_pm -- Missing interpolation keys: ["participants"]
user_notifications.visit_link_to_respond -- Missing interpolation keys: ["base_url", "url"]
user_notifications.visit_link_to_respond_pm -- Missing interpolation keys: ["base_url", "url", "participants"]
user_notifications.posted_by -- Missing interpolation keys: ["username", "post_date"]
user_notifications.pm_participants -- Missing interpolation keys: ["participants"]
user_notifications.invited_group_to_private_message_body -- Missing interpolation keys: ["username", "group_name", "topic_title", "topic_excerpt", "site_title", "site_description"]
user_notifications.invited_to_private_message_body -- Missing interpolation keys: ["username", "topic_title", "topic_excerpt", "site_title", "site_description"]
user_notifications.invited_to_topic_body -- Missing interpolation keys: ["username", "topic_title", "topic_excerpt", "site_title", "site_description"]
user_notifications.user_invited_to_private_message_pm_group.subject_template -- Missing interpolation keys: ["email_prefix", "username", "group_name", "topic_title"]
user_notifications.user_invited_to_private_message_pm_group.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "respond_instructions"]
user_notifications.user_invited_to_private_message_pm.subject_template -- Missing interpolation keys: ["email_prefix", "username", "topic_title"]
user_notifications.user_invited_to_private_message_pm.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "respond_instructions"]
user_notifications.user_invited_to_private_message_pm_staged.subject_template -- Missing interpolation keys: ["email_prefix", "username", "topic_title"]
user_notifications.user_invited_to_private_message_pm_staged.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "respond_instructions"]
user_notifications.user_invited_to_topic.subject_template -- Missing interpolation keys: ["email_prefix", "username", "topic_title"]
user_notifications.user_invited_to_topic.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "respond_instructions"]
user_notifications.user_replied.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_replied.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_replied_pm.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_replied_pm.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_quoted.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_quoted.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_linked.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_linked.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_mentioned.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_mentioned.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_mentioned_pm.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_mentioned_pm.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_group_mentioned.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_group_mentioned.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_posted.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_posted.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_watching_first_post.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_watching_first_post.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_posted_pm.subject_template -- Missing interpolation keys: ["email_prefix", "topic_title"]
user_notifications.user_posted_pm.text_body_template -- Missing interpolation keys: ["header_instructions", "message", "context", "respond_instructions"]
user_notifications.user_posted_pm_staged.subject_template -- Missing interpolation keys: ["optional_re", "topic_title"]
user_notifications.user_posted_pm_staged.text_body_template -- Missing interpolation keys: ["message"]
user_notifications.account_suspended.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.account_suspended.text_body_template -- Missing interpolation keys: ["suspended_till", "reason", "message"]
user_notifications.account_silenced.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.account_silenced.text_body_template -- Missing interpolation keys: ["silenced_till", "reason", "message"]
user_notifications.account_exists.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.account_exists.text_body_template -- Missing interpolation keys: ["site_name", "email", "base_url"]
user_notifications.account_second_factor_disabled.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.account_second_factor_disabled.text_body_template -- Missing interpolation keys: ["site_name", "base_url"]
user_notifications.digest.why -- Missing interpolation keys: ["site_link", "last_seen_at"]
user_notifications.digest.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.digest.unsubscribe -- Missing interpolation keys: ["site_link", "email_preferences_link", "unsubscribe_link"]
user_notifications.digest.from -- Missing interpolation keys: ["site_name"]
user_notifications.digest.preheader -- Missing interpolation keys: ["last_seen_at"]
user_notifications.forgot_password.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.forgot_password.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "email_token"]
user_notifications.email_login.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.email_login.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "email_token"]
user_notifications.set_password.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.set_password.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "email_token"]
user_notifications.admin_login.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.admin_login.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "email_token"]
user_notifications.account_created.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.account_created.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "email_token"]
user_notifications.confirm_new_email.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.confirm_new_email.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "email_token"]
user_notifications.confirm_old_email.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.confirm_old_email.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "email_token"]
user_notifications.notify_old_email.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.notify_old_email.text_body_template -- Missing interpolation keys: ["site_name", "new_email"]
user_notifications.signup_after_approval.subject_template -- Missing interpolation keys: ["site_name"]
user_notifications.signup_after_approval.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "new_user_tips"]
user_notifications.signup.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.signup.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "email_token"]
user_notifications.activation_reminder.subject_template -- Missing interpolation keys: ["email_prefix"]
user_notifications.activation_reminder.text_body_template -- Missing interpolation keys: ["site_name", "base_url", "email_token"]
user_notifications.suspicious_login.subject_template -- Missing interpolation keys: ["site_name", "location"]
user_notifications.suspicious_login.text_body_template -- Missing interpolation keys: ["location", "client_ip", "browser", "device", "os", "base_url"]
login_required.welcome_message -- Missing interpolation keys: ["title"]
login_required.welcome_message_invite_only -- Missing interpolation keys: ["title"]
upload.unauthorized -- Missing interpolation keys: ["authorized_extensions"]
upload.store_failure -- Missing interpolation keys: ["upload_id", "user_id"]
upload.attachments.too_large -- Missing interpolation keys: ["max_size_kb"]
upload.images.too_large -- Missing interpolation keys: ["max_size_kb"]
upload.images.larger_than_x_megapixels -- Missing interpolation keys: ["max_image_megapixels"]
upload.placeholders.too_large -- Missing interpolation keys: ["max_size_kb"]
flag_reason.sockpuppet -- Missing interpolation keys: ["ip_address", "base_path"]
flag_reason.spam_hosts -- Missing interpolation keys: ["domain", "base_path"]
skipped_email_log.user_email_no_user -- Missing interpolation keys: ["user_id"]
skipped_email_log.user_email_post_not_found -- Missing interpolation keys: ["post_id"]
static_topic_first_reply -- Missing interpolation keys: ["page_name"]
guidelines_topic.body -- Missing interpolation keys: ["base_path"]
tos_topic.body -- Missing interpolation keys: ["base_url", "company_name", "contact_email", "governing_law", "city_for_disputes"]
badges.autobiographer.description -- Missing interpolation keys: ["base_uri"]
badges.autobiographer.long_description -- Missing interpolation keys: ["base_uri"]
badges.read_guidelines.description -- Missing interpolation keys: ["base_uri"]
badges.read_guidelines.long_description -- Missing interpolation keys: ["base_uri"]
badges.badge_title_metadata -- Missing interpolation keys: ["display_name", "site_title"]
tags.staff_tag_disallowed -- Missing interpolation keys: ["tag"]
tags.staff_tag_remove_disallowed -- Missing interpolation keys: ["tag"]
tags.forbidden.in_this_category -- Missing interpolation keys: ["tag_name"]
rss_by_tag -- Missing interpolation keys: ["tag"]
finish_installation.confirm_email.message -- Missing interpolation keys: ["email"]
finish_installation.resend_email.message -- Missing interpolation keys: ["email"]
wizard.step.introduction.disabled -- Missing interpolation keys: ["topic_title"]
wizard.step.contact.fields.contact_email.description -- Missing interpolation keys: ["base_path"]
wizard.step.contact.fields.contact_url.description -- Missing interpolation keys: ["base_path"]
wizard.step.corporate.description -- Missing interpolation keys: ["base_path"]
wizard.step.finished.description -- Missing interpolation keys: ["base_path"]
discourse_push_notifications.popup.mentioned -- Missing interpolation keys: ["username", "topic", "site_title"]
discourse_push_notifications.popup.group_mentioned -- Missing interpolation keys: ["username", "topic", "site_title"]
discourse_push_notifications.popup.quoted -- Missing interpolation keys: ["username", "topic", "site_title"]
discourse_push_notifications.popup.replied -- Missing interpolation keys: ["username", "topic", "site_title"]
discourse_push_notifications.popup.posted -- Missing interpolation keys: ["username", "topic", "site_title"]
discourse_push_notifications.popup.private_message -- Missing interpolation keys: ["username", "topic", "site_title"]
discourse_push_notifications.popup.linked -- Missing interpolation keys: ["username", "topic", "site_title"]
discourse_push_notifications.popup.watching_first_post -- Missing interpolation keys: ["username", "topic", "site_title"]
discourse_push_notifications.popup.confirm_title -- Missing interpolation keys: ["site_title"]
discourse_push_notifications.popup.custom -- Missing interpolation keys: ["username", "site_title"]
staff_action_logs.user_merged -- Missing interpolation keys: ["username"]
staff_action_logs.user_delete_self -- Missing interpolation keys: ["url"]
staff_action_logs.webhook_deactivation_reason -- Missing interpolation keys: ["status"]

================================================================================
plugins/poll/config/locales/server.be.yml
================================================================================
poll.invalid_argument -- Missing interpolation keys: ["value", "argument"]
poll.multiple_polls_with_same_name -- Missing interpolation keys: ["name"]
poll.named_poll_must_have_at_least_2_options -- Missing interpolation keys: ["name"]
poll.named_poll_must_have_different_options -- Missing interpolation keys: ["name"]
poll.named_poll_with_multiple_choices_has_invalid_parameters -- Missing interpolation keys: ["name"]
poll.edit_window_expired.cannot_edit_default_poll_with_votes -- Missing interpolation keys: ["minutes"]
poll.edit_window_expired.cannot_edit_named_poll_with_votes -- Missing interpolation keys: ["minutes"]
poll.no_poll_with_this_name -- Missing interpolation keys: ["name"]

================================================================================
plugins/discourse-narrative-bot/config/locales/server.be.yml
================================================================================
discourse_narrative_bot.bio -- Missing interpolation keys: ["discobot_username"]
discourse_narrative_bot.timeout.message -- Missing interpolation keys: ["username", "skip_trigger", "reset_trigger"]
discourse_narrative_bot.dice.not_enough_dice -- Missing interpolation keys: ["num_of_dice"]
discourse_narrative_bot.dice.results -- Missing interpolation keys: ["results"]
discourse_narrative_bot.quote.results -- Missing interpolation keys: ["quote", "author"]
discourse_narrative_bot.magic_8_ball.result -- Missing interpolation keys: ["result"]
discourse_narrative_bot.track_selector.random_mention.reply -- Missing interpolation keys: ["discobot_username", "help_trigger"]
discourse_narrative_bot.track_selector.random_mention.tracks -- Missing interpolation keys: ["discobot_username", "reset_trigger", "default_track", "tracks"]
discourse_narrative_bot.track_selector.random_mention.bot_actions -- Missing interpolation keys: ["discobot_username", "dice_trigger", "quote_trigger", "magic_8_ball_trigger"]
discourse_narrative_bot.track_selector.do_not_understand.track_response -- Missing interpolation keys: ["skip_trigger", "reset_trigger"]
discourse_narrative_bot.track_selector.do_not_understand.second_response -- Missing interpolation keys: ["base_path"]
discourse_narrative_bot.new_user_narrative.onebox.reply -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.images.instructions -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.images.like_not_found -- Missing interpolation keys: ["url"]
discourse_narrative_bot.new_user_narrative.images.not_found -- Missing interpolation keys: ["image_url"]
discourse_narrative_bot.new_user_narrative.bookmark.instructions -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.bookmark.reply -- Missing interpolation keys: ["profile_page_url"]
discourse_narrative_bot.new_user_narrative.bookmark.not_found -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.emoji.instructions -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.emoji.not_found -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.mention.instructions -- Missing interpolation keys: ["discobot_username"]
discourse_narrative_bot.new_user_narrative.mention.not_found -- Missing interpolation keys: ["discobot_username"]
discourse_narrative_bot.new_user_narrative.flag.instructions -- Missing interpolation keys: ["guidelines_url", "about_url", "base_uri"]
discourse_narrative_bot.new_user_narrative.flag.reply -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.flag.not_found -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.search.instructions -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.search.hidden_message -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.search.reply -- Missing interpolation keys: ["search_url"]
discourse_narrative_bot.new_user_narrative.search.not_found -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.new_user_narrative.end.message -- Missing interpolation keys: ["username", "certificate", "base_uri", "discobot_username"]
discourse_narrative_bot.advanced_user_narrative.start_message -- Missing interpolation keys: ["base_uri", "username"]
discourse_narrative_bot.advanced_user_narrative.edit.bot_created_post_raw -- Missing interpolation keys: ["discobot_username"]
discourse_narrative_bot.advanced_user_narrative.edit.not_found -- Missing interpolation keys: ["url", "base_uri"]
discourse_narrative_bot.advanced_user_narrative.delete.instructions -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.advanced_user_narrative.delete.not_found -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.advanced_user_narrative.recover.deleted_post_raw -- Missing interpolation keys: ["discobot_username"]
discourse_narrative_bot.advanced_user_narrative.recover.instructions -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.advanced_user_narrative.recover.not_found -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.advanced_user_narrative.recover.reply -- Missing interpolation keys: ["deletion_after"]
discourse_narrative_bot.advanced_user_narrative.category_hashtag.instructions -- Missing interpolation keys: ["category"]
discourse_narrative_bot.advanced_user_narrative.change_topic_notification_level.reply -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.advanced_user_narrative.poll.instructions -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.advanced_user_narrative.poll.not_found -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.advanced_user_narrative.details.instructions -- Missing interpolation keys: ["base_uri"]
discourse_narrative_bot.advanced_user_narrative.end.message -- Missing interpolation keys: ["certificate"]
```

**Pull request closed without merging**
