### PR TITLE
FIX: PG::StringDataRightTruncation when linking posts

### PR DESCRIPTION
**Pull request by AndrewPrigorshnev**
Users who use encoded slugs on their sites sometimes [run into 500 error](https://meta.discourse.org/t/pg-stringdatarighttruncation-error-value-too-long-for-type-character-varying-500/182426) when pasting a link to another topic in a post. The problem happens when generating a backward "reflection" link that would appear in a linked topic:
Screenshot 2021-05-25 at 16 11 53

Link URL restricted on the database level to 500 chars in length. At first glance it should work since we have a restriction on topic title length:
Screenshot 2021-05-24 at 17 56 24

But it doesn't work when a site uses encoded slugs, like [here](https://rembetiko.gr/t/%CE%B2%CF%81%CE%AE%CE%BA%CE%B1-%CE%BA%CE%AC%CF%84%CE%B9-%CE%B3%CE%B9%CE%B1-%CE%BC%CE%AD%CE%BD%CE%B1-%CF%84%CE%BF-%CF%81%CE%B5%CE%BC%CF%80%CE%AD%CF%84%CE%B9%CE%BA%CE%BF-%CF%84%CF%81%CE%B1%CE%B3%CE%BF%CF%8D%CE%B4%CE%B9-%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9-%CE%BA%CE%B1%CF%84%CE%AC-%CE%B2%CE%AC%CF%83%CE%B9%CE%BD-%CE%B1%CF%81%CE%BC%CE%BF%CE%BD%CE%B9%CE%BA%CE%BF-%CE%BA%CE%B1%CE%B9-%CE%B4%CE%B9%CE%AC-%CF%84%CE%BF%CF%8D%CF%84%CE%BF-%CF%80%CE%BF%CE%BB%CF%85%CF%86%CF%89%CE%BD%CE%B9%CE%BA%CE%BF/42000) (take a look at the URL). The link to a topic, in this case, can be much longer than 500 characters.

By the way, an error happens only when generating a "reflection" link and doesn't happen with a direct link, we [truncate that link](https://github.com/discourse/discourse/blob/6e2ecf40c7456a1af7f6470d09921f0138fbd4bb/app/models/topic_link.rb#L309). It works because, in this case, the original long link is still present in the post body and can be used for navigation. But we can't do the same for backward "reflection" links (without rewriting their implementation), the whole link must be saved to the database.

The simplest and cleanest solution will be just to remove the restriction on the database level. Abuse is impossible here since we are already protected by the restriction on topic title length. There aren’t performance benefits in using length-constrained columns in Postgres, in fact, length-constrained columns need a few extra CPU cycles to check the length when storing data ([doc](https://www.postgresql.org/docs/9.3/datatype-character.html)).

### CODE REVIEW

**Comment by ZogStriP** [comment]
What would happen if we used the slugless topic URL when the URL is too long?

**Comment by AndrewPrigorshnev** [comment]
> What would happen if we used the slugless topic URL when the URL is too long?

At first glance, this should work just fine. I'll investigate more to make sure we won't break anything if we decide to go this way.

But, what a bit concerns me is that by doing this we'll introduce a new logic just to support a constraint in the database.
```javascript
if (longer_than_500_chars) {
    use_slugless_link()
} else {
    use_full_link()
}
```
At the same time, it seems to be safe just to drop constraint. Do we have reasons to have this constraint in the db?

**Comment by ZogStriP** [comment]
I was just being curious. We could even always use the slugless URL when they're using encoded slugs.

**Comment by AndrewPrigorshnev** [comment]
I'm curious, do we have reasons to have this constraint in the db?

**Comment by ZogStriP** [comment]
Not sure, probably worth looking at `git blame` to see if there was a reason in the commit message.

Maybe it was just to ensure there's some kind of limit on the field in order to avoid it being abused (if that's even possible).

**Comment by SamSaffron** [comment]
I say we merge this as is for now, the DB constraint is just causing problems.

**Review by SamSaffron — APPROVED** [review]

**Comment by AndrewPrigorshnev** [comment]
@ZogStriP about the initial reason for this constraint, it exists from the initial commit, so as you said it probably was protection from abuse. Now, it's safe to delete it.

I'm merging this, but I still want to research pros and cons of using slugless URLs for reflection links, so I'm adding it to my list with low priority.

**Pull request merged**
