### PR TITLE
FIX: poll ensure ranked choice results can handle options with rich text and links

### PR DESCRIPTION
**Pull request by merefield**

### CODE REVIEW

**Comment by ZogStriP** [comment]
Are any of these HTML values properly escaped / allowlisted on the server before displaying it back to the users? I'm always wary of `htmlSafe` as it often introduces XSS 🧐

**Comment by merefield** [comment]
> Are any of these HTML values properly escaped / allowlisted on the server before displaying it back to the users? I'm always wary of `htmlSafe` as it often introduces XSS 🧐

@ZogStriP the use here is just the same as for any poll options.  Only poll options values are being exposed.  This is just so users can incorporate rich text within those options and it be exposed in the results verbatim.

**Comment by merefield** [comment]
@ZogStriP thinking about this more, maybe I'm missing something, but surely the options text is only ever what you are allowed to enter into the Poll Builder (unchanged), what is then inserted into the Post (unchanged) and what is allowed to be created on Post create (also unchanged)?  If there is a vulnerability here it is an existing one.

**Comment by merefield** [comment]
@ZogStriP gentle reminder on this one :)

**Comment by merefield** [comment]
@ZogStriP gentle reminder

**Review by ZogStriP — APPROVED** [review]

**Comment by ZogStriP** [comment]
Sorry I missed your pings. Yeah my questions was mostly "out of habits" rather than "thought through".

In this case, I think we're fine since we're going through the regular "create post" pipeline which has plenty of failsafes 👍

**Pull request merged**
