### PR TITLE
FEATURE: allow setting postgres connection variables via environment

### PR DESCRIPTION
**Pull request by Supermathie**

### CODE REVIEW

**Comment by Supermathie** [comment]
Don't merge yet, will simplify

**Comment by eviltrout** [comment]
> Don't merge yet, will simplify

BTW, it's best to use a Draft PR for this since they can't be merged.

**Comment by Supermathie** [comment]
> BTW, it's best to use a Draft PR for this since they can't be merged.

I would have, but couldn't switch it back to a draft.

**Review by eviltrout — APPROVED** [review]

**Comment by Supermathie** [comment]
@eviltrout do we want these settings in `test` and `profile` as well?

I suspect not…

**Comment by eviltrout** [comment]
I doubt anyone would need them there, so I think we can omit for now

**Pull request merged**
