### PR TITLE
FIX: Move store for readonly mode to DB.

### PR DESCRIPTION
**Pull request by tgxworld**
* The thread dies when the container is rebuilt causing the site
  to come out of readonly mode.

Not sure if there were other considerations previously.
cc/ @SamSaffron  @ZogStriP

### CODE REVIEW

**Comment by tgxworld** [comment]
@SamSaffron retrieval of values from `SiteSetting` is cache so no extra queries.

**Comment by ZogStriP** [comment]
This was done in Redis because it allowed you to put the site in readonly mode for a little while, restore a backup and still be in readonly mode to confirm that everything works. Not sure that workflow is still useful though...

**Comment by SamSaffron** [comment]
Also super concerned this is going to risk sites in the wild being stuck in
readonly does this allow for crashing restore process?

**Comment by tgxworld** [comment]
>  little while

I kind of need it abit longer. I ran into this when I was migrating meta's db and upon rebuild the site came out of read-only even before I could check that it was connecting properly.

> Also super concerned this is going to risk sites in the wild being stuck in readonly

Hmm that is a good point. I could run a migration script to ensure they remain in the right state though, assuming the redis-key doesn't expire when they are rebuilding the container.

Is there a scenario that this might happen? 

> does this allow for crashing restore process?

Hmm not sure what you mean here.

**Comment by SamSaffron** [comment]
I mean ...

1. backup process enables readonly mode
2. backup process runs out of memory and crashes
3. site is stuck readonly now potentially for hours cause backup in an
unattended processe

This is why the expiring keys in redis are so powerful, process crashes,
site moves out of readonly automatically.

**Comment by ZogStriP** [comment]
I'm going to close this. We need to figure out something else ;)

**Comment by tgxworld** [comment]
:+1:

**Pull request closed without merging**
