### PR TITLE
FIX: don't show dashboard warning when s3 settings are globally configured

### PR DESCRIPTION
**Pull request by OsamaSayegh**
https://meta.discourse.org/t/dashboard-warning-when-s3-backups-are-globally-configured/88872?u=osama

### CODE REVIEW

**Comment by tgxworld** [comment]
@OsamaSayegh This looks good to me. Can you please rebase this? Thanks!

**Comment by OsamaSayegh** [comment]
@tgxworld I've rebased it, but it's not quite ready, I've noticed three failing test cases failed because of this change https://travis-ci.org/discourse/discourse/jobs/386601444 -- particularly because I shadowed the `s3_use_iam_profile` site setting, which made it always evaluate to `false` because the setting is globally configured so by default:

https://github.com/discourse/discourse/blob/c0b0c66a9e043ff905be0b202127b385616f8e30/config/discourse_defaults.conf#L176

Would it cause any issues if we leave the global setting unset instead of giving it default value? Or should I simply unshadow the setting?

**Comment by SamSaffron** [comment]
Yeah we don't need to do this, we should simply check `GlobalSetting` in s3_config_check. No need to add all that shadowed by global stuff it can cause issues if there is overlap.

**Comment by SamSaffron** [comment]
(closing this for attempt #2 ) :)

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Pull request closed without merging**
