### PR TITLE
No implicit this codemod

### PR DESCRIPTION
**Pull request by wagenet**
This runs the codemod against app and plugins. Tests were not updated.

### CODE REVIEW

**Comment by CvX** [comment]
I see that this prefixes **all** template variables with `this.`, even those that are component arguments and ideall would be prefixed with `@`. Is there a separate codemod that could handle this?

**Comment by wagenet** [comment]
@CvX unfortunately, I couldn’t find one offhand. I still think this is an improvement since it distinguishes from helpers. I suspect we can convert to named arguments as we move to glimmer components. Also, if you do move to TypeScript, Glint is very helpful.

**Review by CvX — APPROVED** [review]
Yup, is a step forward! It needs one more rebase/main-merge and it's ready to go.

**Comment by wagenet** [comment]
@CvX @davidtaylorhq I'll rebase and add the linting rule.

**Pull request merged**
