### PR TITLE
FIX: since Ember 3 interceptClick was not working on buffered links

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by eviltrout** [comment]
This never used to be required, as those links were handled by the global link handler. Why does it need to happen in here now?

**Comment by jjaffeux** [comment]
@eviltrout Don’t have an answer so far...

What I know:

- This is correctly initialized https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/initializers/click-interceptor.js.es6

- https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/initializers/click-interceptor.js.es6#L7 is never trirggering on mobile
- another event like `touchstart` would trigger it

**Comment by eviltrout** [comment]
I'd like to take a look at it myself if that's OK. I'll try to get to it soon.

**Comment by jjaffeux** [comment]
Sure, anyways it's making a test fail. I'm reading more at ember internals meanwhile.

**Pull request merged**
