### PR TITLE
Split alias levels in mentionable and messageable levels.

### PR DESCRIPTION
**Pull request by nbianca**

### CODE REVIEW

**Comment by SamSaffron** [comment]
This looks really nice, but we got to add a few tests here, it has a bunch of security implications we want to make sure we did not miss anything.

**Comment by nbianca** [comment]
There are also tests failing so I'm going to take care of that too.

**Comment by nbianca** [comment]
There are few groups (:moderators, :admins, :trust_level_1, :trust_level_2). By default, these are now messageable, but I believe they were not before?

**Comment by SamSaffron** [comment]
OK, lets try this out! thanks!

**Pull request merged**
