### PR TITLE
FIX: pretty-text shims - getURL's baseUri

### PR DESCRIPTION
**Pull request by renato**
I've noticed that all emojis with names starting with the subfolder path don't work, I found that `__getURLNoCDN` was returning the non-modified `url` instead of prepending `baseUri` for any URL that contained the `baseUri`, not only for emojis. Some examples that can currently fail:
* `/forum` subfolder with a URL like `/t/forums-are-awesome/1234` returns the unmodified URL instead of `/forum/t/forums-...`
* `/info` subfolder with an emoji like `:information_source:`
* `/f` subfolder (my scenario) with a `:frowning:` emoji

This last example can be seen [here](https://www.comparajogos.com.br/f/t/jogo-ark-nova-com-defeito-de-fabrica-cartas-cortadas/35806/8), but basically it renders a broken image because the `src` is wrong (missing `baseUri`):
broken emoji example

There are possibly other edge cases.

### CODE REVIEW

**Comment by xfalcox** [comment]
Is it possible to add some tests?

**Comment by renato** [comment]
From my understanding these shims are only used from ruby calling `v8.eval` and I couldn't find any tests for them, I'm not sure how I would add one but I'm happy to if you can point me in the right direction

**Comment by xfalcox** [comment]
> From my understanding these shims are only used from ruby calling `v8.eval` and I couldn't find any tests for them, I'm not sure how I would add one but I'm happy to if you can point me in the right direction

Have you tried https://github.com/discourse/discourse/blob/main/spec/lib/pretty_text_spec.rb ?

**Comment by renato** [comment]
@xfalcox Thanks for the tip, I hadn't tried it before. I pushed a commit adding 2 tests, one that failed with the previous version and passes now and one that passed before and now. From my testing it doesn't seem like other parts are affected, like links and avatars, and there are some other tests for subfolders.

Please let me know if you think we need to cover something else or if you have any suggestion. Thank you!

**Review by xfalcox — APPROVED** [review]

**Pull request merged**
