### PR TITLE
FEATURE: add slow_mode_prevents_editing setting..

### PR DESCRIPTION
**Pull request by 3-w-c**
..as per https://meta.discourse.org/t/slow-mode-for-a-category/179574/16

### CODE REVIEW

**Comment by eviltrout** [comment]
Did you link to the wrong topic? I don't see anything about edits in that topic. Also, this defaults to `true` which is questionable.

**Comment by mintsaxon** [comment]
Yes, sorry, wrong link, the right one is here: https://meta.discourse.org/t/edit-old-posts-in-a-slow-topic/171489/3 (thanks discoursebot!).

> Also, this defaults to `true` which is questionable.

I set the default to `true` because that matches how Discourse currently works (i.e. edits aren't permitted after `editing_grace_period`). 

I don't really have an opinion about the default, I can see both sides – and the instance we're running will flip it to `false` as soon as we're able. It seems like a pretty big change for forums to suddenly start allowing slow-mode edits, so maybe if y'all prefer `false` there's a way of only having that apply to new sites?

**Comment by eviltrout** [comment]
@mintsaxon thanks for the clarification. It was my mistake and your default sounds good. I'm going to merge it now.

**Review by eviltrout — APPROVED** [review]

**Comment by mintsaxon** [comment]
Much appreciated, sorry for not being clearer the first time round!

**Pull request merged**
