### PR TITLE
Update rtl.scss

### PR DESCRIPTION
**Pull request by Qasem-h**
update post page rtl 
add user activity rtl 
update search rtl
add onebox rtl
and ...
me and @scossar
screenshot : https://meta.discourse.org/t/update-rtl-support-for-discourse/27335

### CODE REVIEW

**Comment by ZogStriP** [comment]
The build is failing and it looks related to your changes. Can you see what's wrong and fix it?

**Comment by Qasem-h** [comment]
I don't know ! everything's ok !

**Comment by Qasem-h** [comment]
im working to fix

**Comment by ZogStriP** [comment]
@Qasem-h You know you don't need to close a PR everytime you want to change something? Just push your changes to the same PR ;)

**Comment by Qasem-h** [comment]
Ok soory !

**Pull request closed without merging**
