### PR TITLE
Add a plugin entry point to add SEO metadata

### PR DESCRIPTION
**Pull request by notriddle**
Related to https://github.com/discourse/discourse-solved/pull/69

### CODE REVIEW

**Comment by SamSaffron** [comment]
We already have:

https://github.com/discourse/discourse/blob/f0af61da415d0bbb4a49cb0eb461bd7bbeb7ea12/app/views/layouts/application.html.erb#L55-L55 

Are you sure this is needed?

**Comment by notriddle** [comment]
Yeah. `server:before-head-close` isn't included in https://github.com/discourse/discourse/blob/cc851af /app/views/layouts/crawler.html.erb

**Comment by SamSaffron** [comment]
Hmm @eviltrout  what is your call here as you added the original extension, there are 2 options

1. Extend `server:before-head-close` so it hits crawler as well

2. Add the extra plugin html that is unconditional 

From what I can tell in all-the-plugins nobody is using server:before-head-close so this must be a customer specific hook.

**Comment by SamSaffron** [comment]
@notriddle see: https://github.com/discourse/discourse/commit/abaa3f0650058bff083761d5318b640588b7d78d

**Pull request closed without merging**
