### PR TITLE
FEATURE: Instagram OmniAuth login methods

### PR DESCRIPTION
**Pull request by markbiegel**
All methods added to include Instagram as an OmniAuth provider.

### CODE REVIEW

**Comment by SamSaffron** [comment]
The PR looks good, but ... would prefer if gem was `require: false` can that be safely changed? 

Also, @coding-horror my call is to add instagram in, it has bigger and more diverse userbase than even github (21 million) vs instagram (400 million)

**Comment by coding-horror** [comment]
OK fine by me

**Comment by SamSaffron** [comment]
OK, let try this out, I will see if I can clean up the requiring

**Comment by SamSaffron** [comment]
thanks!

**Pull request merged**
