### PR TITLE
Adding Piwik as a analytics option

### PR DESCRIPTION
**Pull request by Mooash**
As requested here (https://meta.discourse.org/t/support-for-piwik-analytics-as-an-alternative-to-google-analytics/7512/51) by several people this allows people to use Piwik as an alternative to GA.

I don't know if this PR will be accepted, but I'm hoping for it to be part of the Discourse core as opposed to having to build a plugin for this functionality.

I haven't updated all the languages, do I need to? Apologies if I've missed something else.

### CODE REVIEW

**Comment by coding-horror** [comment]
I really do not support this. Adding piwik is as easy as going to admin, customize, html and pasting the embed code in the html footer.

**Comment by Mooash** [comment]
I don't know why the build failed, it seems to be unrelated to any of the changes I made.

**Comment by SamSaffron** [comment]
@coding-horror the footer thing don't trivially work cause you need to integrate with the page tracker, I do dislike the coupling of yet another tracking mechanism into our code base beyond the 2 google ones. 

I wonder if longer term having a public browsable library of site customisations is the way to go, cause then core does not need to get infected with this.

**Comment by Mooash** [comment]
Closing PR are further discussion on the above linked thread.

**Pull request closed without merging**
