### PR TITLE
FIX: Forward to SSO login automatically

### PR DESCRIPTION
**Pull request by sigginet**
Forward to SSO login URL automatically if SSO is enabled and login is required.

Makes it simpler for users to log in automatically.

### CODE REVIEW

**Comment by riking** [comment]
Travis failure is an unordered TopicQuery result

**Comment by sigginet** [comment]
@riking .. I have nooo clue what that means .. (I started learning RoR this weekend)

It looks like Travis succeeds using Ruby 2.0 but fails in 2.1 due to this TopicQuery result (which I believe I didn't touch..?)
Is it possible that Travis is drinking at work?

**Comment by riking** [comment]
Yeah, heh. I was saying that the failure was unrelated to your changes; it's due to an improperly nondeterminstic test.

**Comment by SamSaffron** [comment]
I will get that test fixed :) thanks for the change

**Pull request merged**
