### PR TITLE
DEV: Run topic tracking state updates in defer queue.

### PR DESCRIPTION
**Pull request by tgxworld**
There is alot of potential for TopicTrackingState to become out of sync
when running it in Sidekiq. If Sidekiq is delayed, the state being
published may no longer make sense.

Follow-up to b1f32f2f5717c4f55b902485794e62b8cecd8522

### CODE REVIEW

**Comment by tgxworld** [comment]
@jbrw Can you have a look at this? There is more potential for stuff to become out of sync if Sidekiq is ever delayed. I've switch this to run in a defer queue to address the original performance concerns.

**Comment by SamSaffron** [comment]
There is some minor risk that stuff headed to defer will never run, will stuff "self correct", if it is just a lost notification if you rudely stop Discourse I guess it is OK?

**Comment by tgxworld** [comment]
@SamSaffron Nope stuff will not self correct as we rely on the message bus messages to keep stuff in sync. The ideal state here is for us to publish the message within the same request but will need @jbrw to clarify why we moved stuff to Sidekiq in the first place.

**Comment by tgxworld** [comment]
My guess here is that `TopicTracking#publish_unread` is fairly inefficient because we publish one message per `TopicUser` record in the DB.

**Comment by tgxworld** [comment]
Can I clarify how this is related to notifications?

**Comment by SamSaffron** [comment]
sorry ... I see... this is just about `2 new topics` `1 unread topic` and so on... 

Recommend you time the block on a typical case, maybe only defer stuff is you know it is going to trigger a mess?

**Comment by jbrw** [comment]
(Sorry - I never noticed the notification for this review request.)

> It was observed that calling TopicTrackingState on popular topics could result in a large number of calls to redis, resulting in slow response times when posting replies.

The response time for posting will increase somewhat linearly as more users participate in a topic, but the problem becomes really apparent when you have thousands of participants in a topic.

**Comment by SamSaffron** [comment]
I am sadly going to close this @tgxworld, the tradeoff of "defer" vs "sidekiq" does not make sense here. Defer is meant for really short jobs and this one can take quite a while.

**Pull request closed without merging**
