### PR TITLE
FEATURE: Add warning input to flag dialog when notifying a user

### PR DESCRIPTION
**Pull request by cpradio**
Added isWarning property
pass is_warning along to post_action
Added is_warning to possible arguments to receive from post_actions route
Only show warning checkbox for staff
Only permit the is_warning argument if the user is staff

### CODE REVIEW

**Comment by cpradio** [comment]
Adding screenshot
image

**Comment by coding-horror** [comment]
I think it might be better to have a red danger button addedat the bottom for staff like we do for spam flags "delete spammer" except it says official warning with the alert glyph

**Comment by cpradio** [comment]
Oh, so instead of a checkbox do a second button? I could look into doing that.

**Comment by cpradio** [comment]
New screenshot
image

**Comment by coding-horror** [comment]
Looks good to me!

**Comment by coding-horror** [comment]
Can we review and merge this @SamSaffron I think it's a good change

**Comment by SamSaffron** [comment]
Sure, looks good and PR is very tidy, nice work @cpradio !

**Pull request merged**
