### PR TITLE
FIX: Handle img src starting with "//" in pull_hotlinked_images job

### PR DESCRIPTION
**Pull request by LeoMcA**

### CODE REVIEW

**Comment by ZogStriP** [comment]
No tests? :'(

**Comment by LeoMcA** [comment]
I'm not sure I know where to even begin writing a test like this (which seems to rely on so many external things, like externally hosted images)... but I'll give it a go!

**Comment by LeoMcA** [comment]
@ZogStriP how's that? 😸

**Comment by LeoMcA** [comment]
Is there anything on my end blocking this from being merged?

**Comment by ZogStriP** [comment]
I was waiting for the build to pass and then completely forgot... Sorry.

Thanks for the work 👍

**Pull request merged**
