### PR TITLE
DEV: Make chatMessage.cook function async

### PR DESCRIPTION
**Pull request by AndrewPrigorshnev**
This will make it simpler to work with this code. This also can make this code more stable and increase stability of our test suite.

Cooked message now will be available immediately after cooking, it wasn't the case before:

```javascript
await message.cook();
const cooked = message.cooked;
```

This also removes a call to `message.cook()` from message fabricator. Alternatively we may leave the call there and make the fabricator function async, but I fill it's better this way. If someone needs to test something related to cooked message, they can either pass cooked text to fabricator:

```javascript
message = fabricators.message({ cooked: "<p>cooked</p>" });
```

or call `message.cook()` after fabrication:

```javascript
message = fabricators.message({ message: "raw message" });
await message.cook()
```

### CODE REVIEW

**Comment by jjaffeux** [comment]
I tried this in the past, I had issues with it (mostly due to multiple simultaneous calls), but if we get it working like this, cool :+1:

**Comment by jjaffeux** [comment]
I like the last changes :+1:

**Comment by AndrewPrigorshnev** [comment]
It's ready for review now, and should be safe to merge.

**Review by jjaffeux — APPROVED** [review]
Ok, just tried it, looks good thanks!

**Pull request merged**
