### PR TITLE
DEV: Show warning message when using ember css selectors

### PR DESCRIPTION
**Pull request by oblakeerickson**
When editing the theme css via the admin UI a warning message
will be displayed if it detects that the `#emberXXX` or `.ember-view`
css selectors are being used. These are dynamic selectors that ember
generates, but they can change so they should not be used.

This error message will be displayed:

image

### CODE REVIEW

**Review by jjaffeux — APPROVED** [review]
would be nice to check the actual error message in spec too IMO as it's custom, but looking very good anyways 🙌

**Comment by davidtaylorhq** [comment]
I worry a regex could have some false positives here. What if someone puts a comment in the CSS file like

```
// Avoiding .ember-view class here
.not-ember-view {
...
```
This would completely break theme editing, and importing/updating remote themes.

If this was a warning rather than an error, it might be a little safer? We already have a pattern for warnings like this here:

https://github.com/discourse/discourse/blob/8a001c2fe3f957d7be81f9c0113d51888c0668ff/app/models/theme_field.rb#L69-L69

**Comment by jjaffeux** [comment]
This was supposed to be a warning no? I recall we talked of a warning in the topic.

**Comment by eviltrout** [comment]
Agreed @oblakeerickson - it has to be a warning. Preventing saves is dangerous here.

**Comment by oblakeerickson** [comment]
Sounds good. Thanks for the feedback. I'll make sure it is just a warning.

**Pull request merged**
