### PR TITLE
Prepare for Teatro

### PR DESCRIPTION
**Pull request by divineforest**
Hey!

I am developer at Teatro.io and I want to offer you our service — it automatically creates a staging server for each opened pull request.

Teatro.io is free for open source projects and some large projects like GitLab, ErrBit, OpenProject, Spree and others are already using Teatro for free stage servers.

Here's URL of Teatro stage server for my fork of discourse: http://teatro.divineforest-discourse-51d3c00407c3a4a9be8e.ttrcloud.com/

When you connect project to Teatro, we'll automatically post a comment (via @TeatroIO) with link to unique stage server that was made for this specific branch (see divineforest#3 for example).

To use Teatro you need:
— sign in using Github account on https://teatro.io
— add your project

Benefits:
— demo for new users (always up to date!)
— the way to test changes: each Pull Request gets separate stage server
— FREE for open source!

### CODE REVIEW

**Comment by coding-horror** [comment]
Hmm depends if @riking likes it or not

http://youtu.be/vYEXzx-TINc

**Comment by divineforest** [comment]
@coding-horror could you give any feedback?

**Comment by coding-horror** [comment]
I just feel like we're so busy working at 150% capacity with a small team that we have no time to look at extra bonus things right now.

**Comment by divineforest** [comment]
@coding-horror I can help with setting up so you will not need to spend your time

**Pull request closed without merging**
