### PR TITLE
Added plugin outlets above post in topic stream and above and below footer

### PR DESCRIPTION
**Pull request by aedensixty**
Added plugin outlets above user in topic stream and above and below footer. Allows insert of custom image above user in topic and custom code inserted context above and below the custom html content from the admin.

### CODE REVIEW

**Comment by aedensixty** [comment]
The CI appeared to fail due to a broken test and not related to my commits.

**Comment by eviltrout** [comment]
`topic-above-user` is perhaps less appropriate than `topic-above-posts` ?

**Comment by aedensixty** [comment]
Will update

**Comment by aedensixty** [comment]
Any news on this?

**Comment by eviltrout** [comment]
Thanks for this, merged :)

**Pull request merged**
