### PR TITLE
DEV: introduces the {{if-action}} helper

### PR DESCRIPTION
**Pull request by jjaffeux**
Usage:

```
<DButton @action={{if-action this.action}} />
```

If `this.action` is undefined it will just be a noop.

### CODE REVIEW

**Comment by jjaffeux** [comment]
@cvx thoughts on this?

**Comment by CvX** [comment]
1. The test relies on d-button, which already kinda handles that case. So it doesn't actually test "doesn't exist" path (e.g. `<DButton @action={{lololol}} />` does not error either)
2. I wonder if this wouldn't be more self-explanatory: `@action={{or this.onClick (no-op)}}`? See: https://github.com/discourse/discourse/commit/32c391744fd27d8e888a46966403fb91a4ffc23f
3. What use cases do you have in mind? Maybe it's something that the end component should handle (in js?), like the mentioned d-button?

**Comment by jjaffeux** [comment]
> 1

I didn't know d-button had this logic, but yes would just need to change the test

> 2\. I wonder if this wouldn't be more self-explanatory: `@action={{or this.onClick (no-op)}}`? See: [32c3917](https://github.com/discourse/discourse/commit/32c391744fd27d8e888a46966403fb91a4ffc23f)

I did the same in chat ATM :p  https://github.com/discourse/discourse-chat/pull/1031/files#diff-f3a580ca449661273cf79f55187564299489e9c172dc4d0d98155d195d5cc3be

So I'm fine with this syntax, don't have strong opinions either way.

> What use cases do you have in mind? Maybe it's something that the end component should handle (in js?), like the mentioned d-button?

Even if this is to the end component to handle it, and this is how I use it in chat, you still have to implement it, and this noop helper make it super easy.

**Comment by CvX** [comment]
> I did the same in chat ATM :p https://github.com/discourse/discourse-chat/pull/1031/files#diff-f3a580ca449661273cf79f55187564299489e9c172dc4d0d98155d195d5cc3be
> 
> So I'm fine with this syntax, don't have strong opinions either way.

Ah, okay, so I'd go with the `no-op` function/helper 😃

My very first impression when I saw `{{if-action this.x}}` was, "if action then what?? what, Joffrey??" 🤪 i.e. I expected more arguments after the first one 😉

**Comment by jjaffeux** [comment]
> > I did the same in chat ATM :p https://github.com/discourse/discourse-chat/pull/1031/files#diff-f3a580ca449661273cf79f55187564299489e9c172dc4d0d98155d195d5cc3be
> > So I'm fine with this syntax, don't have strong opinions either way.
> 
> Ah, okay, so I'd go with the `no-op` function/helper 😃
> 
> My very first impression when I saw `{{if-action this.x}}` was, "if action then what?? what, Joffrey??" 🤪 i.e. I expected more arguments after the first one 😉

Sure, push your commit or create a new Pr with yours if you want, I'm fine with `no-op` :+1:

Though...
```
{{if-action "question" 42}}
```

**Comment by davidtaylorhq** [comment]
Some interesting references:

- A helper which does something very similar to the proposal here: https://github.com/DockYard/ember-composable-helpers#optional

- An old discussion about the same problem: https://github.com/emberjs/rfcs/issues/90

But… do we still need to be using the `{{action` helper here? I just did a quick test and this seems to work:

```
<button onclick={{this.optionalAction}} />
```

If optionalAction is defined, it gets fired on click. If not, it's a no-op.

(this approach does rely on the action function being decorated with `@action`)

**Comment by jjaffeux** [comment]
> But… do we still need to be using the `{{action` helper here? I just did a quick test and this seems to work:
> 
> ```
> <button onclick={{this.optionalAction}} />
> ```

I noticed exactly the same yesterday and started using it

**Pull request closed without merging**
