### PR TITLE
Update RSpec to test on Rails 5

### PR DESCRIPTION
**Pull request by maclover7**
This will allow Rails 5 tests to run normally now.

### CODE REVIEW

**Comment by maclover7** [comment]
cc @SamSaffron

**Comment by SamSaffron** [comment]
Cant we restructure so this is only the case when running in rails 5 mode ?

**Comment by SamSaffron** [comment]
we upgraded to 3.4.0 recently and I think its working on 5, can revisit with another stable rspec upgrade once rails 5 is out.

**Comment by maclover7** [comment]
Crap, sorry I forgot about this PR 😞

**Comment by SamSaffron** [comment]
no worries

**Pull request closed without merging**
