### PR TITLE
FEATURE: RS512, RS384 and RS256 COSE algorithms

### PR DESCRIPTION
**Pull request by udan11**
These algorithms are not implemented by cose-ruby, but used in the web
authentication API.

### CODE REVIEW

**Review by eviltrout — APPROVED** [review]

**Comment by tgxworld** [comment]
Are there any tests we can add for this monkey patch here? Also, are there plans to upstream the changes here? It'll be good to add a comment in the patch explaining why we need to carry it for documentation purposes.

**Comment by martin-brennan** [comment]
Agree with @tgxworld , we really should have documentation in the monkey patch with the reasons why we need this based on backstory in /t/60175

**Comment by udan11** [comment]
I will add a comment to the patch.

I didn't submit a PR to cose-ruby because there is a similar one for another algorithm since 2019 that was not merged yet. I do not think the library is maintained anymore.

**Review by martin-brennan — DISMISSED** [review]
> Are there any tests we can add for this monkey patch here?

Sorry I didn't realise this either, we really should add a spec to cover the original issue, which was that the `SecurityKeyRegistrationService` allowed the `-257` alg but the `SecurityKeyAuthenticationService` did not. There are already spec files for both of these so it shouldn't be too hard to add.

Also I agree about the upstreaming, definitely doesn't seem maintained anymore (the cose gem)

**Review by ZogStriP — APPROVED** [review]

**Comment by bdewater** [comment]
`cose-ruby` is maintained, just not seeing a lot of updates as it's mostly feature complete right now. If a patch seems to much trouble you can always open an issue :)

But I don't believe it this should be necessary when https://github.com/cedarcode/webauthn-ruby/blob/master/lib/cose/rsapkcs1_algorithm.rb does the same?
```
[bdewater@thatch-bart webauthn_demo % bin/rails c
Loading development environment (Rails 7.0.3.1)
irb(main):001:0> WebAuthn::VERSION
=> "2.5.2"
irb(main):002:0> COSE::VERSION
=> "1.2.1"
irb(main):003:0> COSE::Algorithm.instance_variable_get(:@registered_by_id)
=> 
{-7=>                                                                                                      
  #<COSE::Algorithm::ECDSA:0x00000001099eb6f0                                                              
   @curve=#<struct COSE::Key::Curve id=1, name="P-256", pkey_name="prime256v1">,                           
   @hash_function="SHA256",                                                                                
   @id=-7,                                                                                                 
   @name="ES256">,                                                                                         
 -35=>                                                                                                     
  #<COSE::Algorithm::ECDSA:0x00000001099eb420                                                              
   @curve=#<struct COSE::Key::Curve id=2, name="P-384", pkey_name="secp384r1">,                            
   @hash_function="SHA384",                                                                                
   @id=-35,                                                                                                
   @name="ES384">,                                                                                         
 -36=>                                                                                                     
  #<COSE::Algorithm::ECDSA:0x00000001099eb2b8                                                              
   @curve=#<struct COSE::Key::Curve id=3, name="P-521", pkey_name="secp521r1">,
   @hash_function="SHA512",
   @id=-36,
   @name="ES512">,
 -47=>
  #<COSE::Algorithm::ECDSA:0x00000001099eb100
   @curve=#<struct COSE::Key::Curve id=8, name="secp256k1", pkey_name="secp256k1">,
   @hash_function="SHA256",
   @id=-47,
   @name="ES256K">,
 -37=>#<COSE::Algorithm::RSAPSS:0x00000001099eaf98 @hash_function="SHA256", @id=-37, @name="PS256", @salt_length=32>,
 -38=>#<COSE::Algorithm::RSAPSS:0x00000001099eae58 @hash_function="SHA384", @id=-38, @name="PS384", @salt_length=48>,
 -39=>#<COSE::Algorithm::RSAPSS:0x00000001099ead90 @hash_function="SHA512", @id=-39, @name="PS512", @salt_length=64>,
 4=>#<COSE::Algorithm::HMAC:0x00000001099eacc8 @hash_function="SHA256", @id=4, @name="HMAC 256/64", @tag_length=64>,
 5=>#<COSE::Algorithm::HMAC:0x00000001099eab60 @hash_function="SHA256", @id=5, @name="HMAC 256/256", @tag_length=256>,
 6=>#<COSE::Algorithm::HMAC:0x00000001099eaa98 @hash_function="SHA384", @id=6, @name="HMAC 384/384", @tag_length=384>,
 7=>#<COSE::Algorithm::HMAC:0x00000001099ea9d0 @hash_function="SHA512", @id=7, @name="HMAC 512/512", @tag_length=512>,
 -257=>#<RSAPKCS1Algorithm:0x00000001093fa520 @hash_function="SHA256", @id=-257, @name="RS256">,
 -258=>#<RSAPKCS1Algorithm:0x00000001093f9800 @hash_function="SHA384", @id=-258, @name="RS384">,
 -259=>#<RSAPKCS1Algorithm:0x00000001093f94e0 @hash_function="SHA512", @id=-259, @name="RS512">,
 -65535=>#<RSAPKCS1Algorithm:0x00000001097374b8 @hash_function="SHA1", @id=-65535, @name="RS1">}
irb(main):005:0> 
****
```

**Pull request merged**
