### PR TITLE
DEV: s/\$redis/Discourse\.redis

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by eviltrout** [comment]
Another thought - can we deprecate `$redis` with an error?

**Comment by jjaffeux** [comment]
> Another thought - can we deprecate `$redis` with an error?

Yew I would want to do this but want to do a check of plugins first

**Comment by eviltrout** [comment]
Sorry I should have said warning! Output something when it's used.

**Comment by jjaffeux** [comment]
@eviltrout I added a rubocop rule which should do this

**Comment by SamSaffron** [comment]
feel free to merge when you are comfortable.

**Pull request merged**
