### PR TITLE
Improving search result blurb

### PR DESCRIPTION
**Pull request by jumbojett**
# Problem

Discourse _blurb_ does not correlate with the Postgres methods used to index and search data. 

# Solution

This PR does the following:

- Removes Ruby methods that build "blurbs" in search results. In place, harnessing powerful Postgres `ts_headline` to build better blurbs.
- Removes unnecessary index data from raw_data fields (topic title) in posts, and topic indexes leaving search_data fields in current format
- Improves result processing by using preprocessed raw_data
- Removes blurb-length search option due to irrelevance in blurb calculations

### CODE REVIEW

**Comment by SamSaffron** [comment]
can you include some specific examples of how this improves things?

**Comment by jumbojett** [comment]
> specific examples of how this improves things

Sure @SamSaffron ! Specifically:

- Now blurbs directly reflect the original `ts_vector` query. This means the extracted text more relevant.
- Terms are hi-lighted with respect to stemming. If a user searches for _computing_ and the search engine matches on _computer_ then this term will be hi-lighted. The Ruby and Javascript methods cannot detect this.
- Blurbs are created from a lexical analysis and contain whole words rather than cutting up strings

# Example
They say a picture is worth a thousand words. 
## Before
image

## After
image

**Comment by SamSaffron** [comment]
hmmm that sample is showing a blurb that has no indication that it is taking part of the sentence, can you add the ellipsis on both ends if it is a partial quote?

**Comment by jumbojett** [comment]
> can you add the ellipsis on both ends if it is a partial quote?

@SamSaffron Yes! Ellipsis for partials are currently rendered for results that have more than one fragment. `ts_header` appends ellipsis for multiple fragments. The number of fragments are limited to three and generated based on relevance to the vector query. Here's another example where ellipses appear in blurbs.

image

**Comment by SamSaffron** [comment]
I follow, but what about the leading and trailing ellipsis? Should it not be? 

...think we should add a new tag to the system that isn't included ... know by replying down below. Suggest new tags Here...

**Comment by SamSaffron** [comment]
Also, I wonder what will happen in other locales, especially Chinese where the tokenizing is all messed up

**Comment by jumbojett** [comment]
> what about the leading and trailing ellipsis

Postgres doesn't give a way to control these at the moment. I suppose a '...' could be prepended after the fact if a capital letter is not detected? 

> I wonder what will happen in other locales, especially Chinese where the tokenizing is all messed up

I'm not sure. This PR is a direct reflection of the current `ts_vector` query. In other words, if your current search functions with Chinese locales, then the blurbs _should_ automatically reflect it.

**Comment by SamSaffron** [comment]
The problem with CJK languages is that PG support is super uneven. So we do the tokenizing in ruby. 

In Chinese, for example: asentencecanlooklikethis

We go ahead and split it up and store: "a sentence can look like this" 

If you we followed this blurb scheme in Chinese the blurbs would look incredibly confusing.

**Comment by jumbojett** [comment]
> We go ahead and split it up and store: "a sentence can look like this"

Ah I understand - Are there any Chinese users who could help test? I'm thinking worst case is that a blurb is not returned. 

Could the PR be accepted in the meantime and file an open issue to look into this? I left the `blurb_for` method in place for the event we need to have an alternative game-plan for Chinese text.

**Comment by SamSaffron** [comment]
I can't really break Chinese here, that is a non starter, @fantasticfears  may be able to help you test this

**Comment by jumbojett** [comment]
@fantasticfears if you can help in this area it would be greatly appreciated. 😊 

👌  @SamSaffron I have an up-and-coming PR that builds off of this one. If there's anything else I can do to increase the chances of its acceptance let me know.

**Comment by SamSaffron** [comment]
@jumbojett If you made this optional, default off, via a site setting I would feel much more comfortable accepting it. 

Then we can experiment with it

**Comment by jumbojett** [comment]
Site settings sounds like a possible path, but I'm afraid of the complexity it might introduce when trying to build upon this revision.

**Comment by SamSaffron** [comment]
can you expand on why your next PR needs this change?

**Comment by jumbojett** [comment]
> expand on why your next PR needs this change?

Next PR will be for expanded searches. Searches that span topic-wide. (Similar to how google would search a discourse instance.) This requires `raw_data` to be specifically formatted according to this PR.

**Comment by fantasticfears** [comment]
Sure I can help you with testing in Chinese. I'll come back with testing results later. The picture looks awesome!

Would you mind drawing some lines about your plans on [Meta](https://meta.discourse.org/c/dev)?
Sam has to keep maintaining the support for CJK search. And I'd also like to work on improving searching Chinese for Discourse later on. It would be great for the community to discuss.

**Comment by jumbojett** [comment]
Great! Thanks for your help @fantasticfears. 

> Would you mind drawing some lines about your plans on Meta?

Sure thing. I'll be sure to detail plan as soon as it's fully formulated.

**Comment by fantasticfears** [comment]
I may run into some locale problem which I can't reproduce the production search with the local docker. Anyway, it's better to just tell you how the local tests with your PR. It breaks the sentences with blanks where it shouldn't be. It looks bad but the quality seems nice. Great work!

And Chinese search appears having some problems back in months and it's not the index problem. Your PR seems fixing it somehow...

image

As of the dev process, if I can submit proposal in GSoC this year, I'll have the opportunity to address CJK searches from the ground up. It's quite hard to reproduce or address the searches on my end :(

**Comment by jumbojett** [comment]
Thank you for helping us test @fantasticfears !  

> if I can submit proposal in GSoC this year, I'll have the opportunity to address CJK searches from the ground up

That would be great.

@SamSaffron Thoughts moving forward?

**Comment by SamSaffron** [comment]
I feel like we have to fix the spacing issue in chinese before accepting this, I think the best way to move forward here is to make this a site setting

**Comment by jumbojett** [comment]
@fantasticfears I found the following Postgres extension. If this were included as part of the base discourse docker image, could it address white-space formatting?

https://github.com/amutu/zhparser

**Comment by fantasticfears** [comment]
@jumbojett My bad. I think my backup may override the index. Now I checkout the version before your PR and restore. Then I rebuild to your branch. The space issue is a false negative. Sorry for the confusion.

image

But the search blurb may not show the search term. `raw_data` isn't being tokenized. The difference is that only the markdown marks are stripped.
And it seems bold text (style) are not filtered by the method.

https://github.com/amutu/zhparser is an tokenizer which breaks the sentences into words. The tokenization is done in Ruby now. It is tempting but harder for @SamSaffron to maintain if not stable enough.

**Comment by SamSaffron** [comment]
I still don't get the reluctance to make this optional for the time being, its quite simple to do the switching cause the blurbs can be generated server side and highlighting done server sides. So the whole difference ends up being weather you select an extra column or not.

**Comment by jumbojett** [comment]
> I still don't get the reluctance to make this optional for the time being

@SamSaffron apologies for the reluctance. I'm new to ruby and find it intimidating to some extent.

> highlighting done server sides

I welcome assistance. I'm not entirely sure the best way to approach this in ruby.

**Comment by tgxworld** [comment]
@jumbojett Just wanted to check if there are any updates on this?

**Comment by jumbojett** [comment]
Hi @tgxworld . Thanks for checking in. I've been unable to tend to this PR. I'm not sure when I'll be able to update it. I'll add you as a collab on my fork in the event you'd like to finalize it based on @SamSaffron 's advice. How does that sound?

**Pull request closed without merging**
