### PR TITLE
Added san francisco font

### PR DESCRIPTION
**Pull request by fathermerry**

### CODE REVIEW

**Comment by coding-horror** [comment]
Thanks for this! These are odd font names, is there anything cleaner to use?

**Comment by SamSaffron** [comment]
Also, I really want some screen shots here of before and after. and some
feedback from @awesomerobot before changing fonts globally.

**Comment by fathermerry** [comment]
There's no cleaner way to write it. Apple didn't include the new font in font book by default. I found out here myself https://css-tricks.com/i-left-my-system-fonts-in-san-francisco/

**Comment by fathermerry** [comment]
I think making use of the system font ensures some kind on consistency with the operating system, and is not so much a global font change as it is _supporting_ the new El Capitan. I might be wrong though. Here are screenshots.
Before
After

**Comment by coding-horror** [comment]
It's a really nasty hack in the current form.. if we could specify it as a normal font-family, maybe.. I just don't like shipping this level of nasty hack in the box. People can add it to Admin, Customize, CSS as needed. Appreciate the effort though. (I thought it would be simpler!)

**Comment by fathermerry** [comment]
That’s okay. Thanks for the consideration


Cheers,Opemipo.

**Pull request closed without merging**
