### PR TITLE
FEATURE: Use image gallery functionality in magnific

### PR DESCRIPTION
**Pull request by gdpelican**
image

Looks like the author of the lightbox plugin you're using released gallery functionality a little ways back.

[(relevant thread)](https://meta.discourse.org/t/navigating-between-images-within-a-post/39158)
[(gif for reference)](http://recordit.co/G7CVts1SC3)

### CODE REVIEW

**Comment by ZogStriP** [comment]
Looks 👍 Mind squashing the commits?

**Comment by gdpelican** [comment]
Oh, can't github do that for you now?
screen shot 2017-04-25 at 5 06 19 am

**Comment by ZogStriP** [comment]
We disabled these options for this repository.

**Comment by gdpelican** [comment]
Alright, should be good to go now @ZogStriP . I'd be curious to hear the rationale for turning those features off if you're willing to share it? 🍖

**Comment by ZogStriP** [comment]
Thanks. Let's try this 👍 

> I'd be curious to hear the rationale for turning those features off if you're willing to share it? 🍖

I actually have no idea. I re-enabled it.

**Pull request merged**
