### PR TITLE
FEATURE: Add link to original image in lightbox

### PR DESCRIPTION
**Pull request by nbianca**
Adds a link to the original image next to the download link. It can be
used to view full resolution image in the browser.

image

### CODE REVIEW

**Comment by tgxworld** [comment]
Will it be possible to add a test for this?

**Review by eviltrout — APPROVED** [review]

**Comment by SamSaffron** [comment]
I am not sure if 🔍 is the right iconography here cause it clashes with search. @awesomerobot  

Also can you include a screenshot of how this looks on narrow images?  This only shows up beyond a certain width?

**Comment by nbianca** [comment]
This is what it looks now. I fixed it a bit, because it used to show one character per line for narrow images.

image

Screenshot 2022-02-11 at 14 30 29

**Comment by nbianca** [comment]
Added a min-width:

image

**Comment by ZogStriP** [comment]
> Screenshot 2022-02-11 at 14 30 29

I think we can do much better here. 

Can you find a way to hide/show the most important information based on the width of the image?

**Comment by nbianca** [comment]
I added a minimum width and now it looks like this:

Screenshot 2022-03-07 at 22 49 32

What do you think? Do you still want to hide some information?

**Comment by ZogStriP** [comment]
I guess that's OK for now 👍

**Pull request merged**
