### PR TITLE
Add a nil check on the connection before attempting to exec it

### PR DESCRIPTION
**Pull request by farmdawgnation**
Ran into an issue while trying to [import mbox files](https://meta.discourse.org/t/howto-import-mbox-mailing-list-files/51233) that I tracked back to this line. I'm not an avid rubyist so I'm not entirely sure this is the Right Solution™, but it got my import running after I made this change.

Figured that others would probably run into the same issue so I thought I'd submit a PR to call attention to the issue, if nothing else. =)

Cheers!

### CODE REVIEW

**Comment by coding-horror** [comment]
Is this ok @ZogStriP ?

**Comment by ZogStriP** [comment]
It would probably be better to change this to use a SQL transaction instead and add the `ON COMMIT DROP` option to the `TEMP TABLE`.

**Comment by farmdawgnation** [comment]
@ZogStriP I don't think that would fix the problem here, which is that `connection` is `Nil`.

**Comment by ZogStriP** [comment]
Why is `connection` `nil` then?

**Comment by farmdawgnation** [comment]
That I don't know. It would seem that `ActiveRecord::Base.connection.raw_connection` likely returns `nil` but I wasn't able to try down why that might be happening. I spent some time digging through the Rails docs trying to figure out how that could happen and `puts`'ing a few things but I was quite befuddled at what was actually going on in this code.

My best guess is that this method was being executed before the database connection was fully set up? But once again, I had issues disentangling what was actually going on here.

**Comment by tgxworld** [comment]
This looks good to me. `connection` may be `nil` if `import_ids` is empty.

**Pull request merged**
