### PR TITLE
DEV: uses popper for autocomplete

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by jjaffeux** [comment]
I'm unsure yet I want to bring this new way to compute caret position.

**Review by eviltrout — APPROVED** [review]
I am happy to improve this library, but we need to be very careful because I think it is lacking in testing and changes to it could break stuff easily.

**Comment by SamSaffron** [comment]
I am not sure about merging this quite yet, autocomplete is so fragile, can we wait till after the major release?

**Comment by jjaffeux** [comment]
Yes sure if you want, I reduced the scope a lot to avoid issues though, also it’s already broken in some way atm.

Envoyé de mon iPhone

**Pull request merged**
