### PR TITLE
FEATURE: Include topic title, category in posts.json

### PR DESCRIPTION
**Pull request by riking**
https://meta.discourse.org/t/no-topic-title-on-posts-json/32802

### CODE REVIEW

**Comment by SamSaffron** [comment]
One moment here, before we get all excited, how does this avoid an N+1 query?

**Comment by riking** [comment]
This part:

```
     # last 50 post IDs only, to avoid counting deleted posts in security check
     posts = Post.order(created_at: :desc)
                 .where('posts.id <= ?', last_post_id)
                 .where('posts.id > ?', last_post_id - 50)
                 .includes(topic: :category)
                 .includes(:user)
                 .limit(50)
```

However, there is a N+1 on users...

```
D, [2015-09-04T13:33:42.810805 #419] DEBUG -- :   User Load (0.9ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = $1 LIMIT 1  [["id", 15271]]
D, [2015-09-04T13:33:42.816186 #419] DEBUG -- :   User Load (1.3ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = $1 LIMIT 1  [["id", 14270]]
D, [2015-09-04T13:33:42.820628 #419] DEBUG -- :   User Load (0.9ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = $1 LIMIT 1  [["id", 16397]]
D, [2015-09-04T13:33:42.827412 #419] DEBUG -- :   CACHE (0.0ms)  SELECT  "groups".* FROM "groups"  WHERE "groups"."id" = $1 LIMIT 1  [["id", 47]]
D, [2015-09-04T13:33:42.831737 #419] DEBUG -- :   User Load (1.0ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = $1 LIMIT 1  [["id", 1995]]
D, [2015-09-04T13:33:42.835459 #419] DEBUG -- :   CACHE (0.0ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = $1 LIMIT 1  [["id", 1995]]
```

**Comment by riking** [comment]
Verified no N+1s after this:

```
I, [2015-09-04T13:36:22.652053 #419]  INFO -- : Started GET "/posts.json" for 127.0.0.1 at 2015-09-04 13:36:22 -0700
I, [2015-09-04T13:36:22.806593 #419]  INFO -- : Processing by PostsController#latest as JSON
D, [2015-09-04T13:36:22.812808 #419] DEBUG -- :   User Load (0.8ms)  SELECT  "users".* FROM "users"  WHERE "users"."auth_token" = 'f496bf5188f51ee0e30c083638a057c1' LIMIT 1
D, [2015-09-04T13:36:22.815669 #419] DEBUG -- : Unpermitted parameters: format
D, [2015-09-04T13:36:22.820942 #419] DEBUG -- :   Post Load (0.8ms)  SELECT  "posts".* FROM "posts"  WHERE ("posts"."deleted_at" IS NULL)  ORDER BY "posts"."id" DESC LIMIT 1
D, [2015-09-04T13:36:22.840563 #419] DEBUG -- :   Post Load (1.7ms)  SELECT  "posts".* FROM "posts"  WHERE ("posts"."deleted_at" IS NULL) AND (posts.id <= 136516) AND (posts.id > 136466)  ORDER BY "posts"."created_at" DESC LIMIT 50
D, [2015-09-04T13:36:22.852577 #419] DEBUG -- :   Topic Load (1.2ms)  SELECT "topics".* FROM "topics"  WHERE ("topics"."deleted_at" IS NULL) AND "topics"."id" IN (3053, 32228, 32206, 28793, 32256, 30473, 31993, 31753, 32261, 32163, 32258, 32260, 32259, 32257, 11613, 32243, 24879, 32239, 32234, 32251, 32255, 32252, 26875, 32253, 32254)
D, [2015-09-04T13:36:22.876796 #419] DEBUG -- :   Category Load (0.9ms)  SELECT "categories".* FROM "categories"  WHERE "categories"."id" IN (7, 17, 2, 6, 25, 1, 36, 22)
D, [2015-09-04T13:36:22.891166 #419] DEBUG -- :   User Load (1.3ms)  SELECT "users".* FROM "users"  WHERE "users"."id" IN (6626, 19, 15814, 11160, -1, 16424, 16457, 32, 9833, 16397, 7229, 1995, 14169, 5351, 15568, 15320, 9437, 16410, 12933, 15271, 8300, 2, 16295, 16325, 3987, 14750)
D, [2015-09-04T13:36:22.898895 #419] DEBUG -- :   Group Load (0.9ms)  SELECT "groups".* FROM "groups"  WHERE "groups"."id" IN (47)
D, [2015-09-04T13:36:22.907481 #419] DEBUG -- :   User Load (1.2ms)  SELECT "users".* FROM "users"  WHERE "users"."id" IN (6626, 212, 15271, 14270, 16397, 1995, 19, 15320, 13042, 15085, 15604, 14448, 3987, 1)
D, [2015-09-04T13:36:22.912454 #419] DEBUG -- :   PostAction Load (1.3ms)  SELECT "post_actions".* FROM "post_actions"  WHERE ("post_actions"."deleted_at" IS NULL) AND "post_actions"."post_id" IN (136516, 136515, 136514, 136513, 136512, 136511, 136510, 136509, 136508, 136507, 136506, 136505, 136504, 136503, 136502, 136501, 136500, 136499, 136498, 136497, 136496, 136495, 136494, 136493, 136492, 136491, 136490, 136489, 136488, 136487, 136486, 136485, 136484, 136483, 136482, 136481, 136480, 136479, 136478, 136477, 136476, 136475, 136474, 136473, 136472, 136471, 136470, 136469, 136468, 136467) AND "post_actions"."user_id" = 6626
D, [2015-09-04T13:36:22.935496 #419] DEBUG -- :   SQL (0.7ms)  SELECT "user_custom_fields"."name", "user_custom_fields"."value" FROM "user_custom_fields"  WHERE "user_custom_fields"."user_id" = $1  [["user_id", 6626]]
I, [2015-09-04T13:36:23.011288 #419]  INFO -- : Completed 200 OK in 203ms (Views: 0.2ms | ActiveRecord: 27.5ms)
```

**Comment by ZogStriP** [comment]
:+1:

**Pull request merged**
