### PR TITLE
FEATURE: Add "delete on owner reply" bookmark functionality

### PR DESCRIPTION
**Pull request by martin-brennan**
This adds an option to "delete on owner reply" to bookmarks. If you select this option in the modal, then reply to the topic the bookmark is in, the bookmark will be deleted on reply.

image

This PR also changes the checkboxes for these additional bookmark options to an Integer column in the DB with a combobox to select the option you want.

---------------------------

The use cases are:

* Sometimes I will bookmark the topics to read it later. In this case we definitely don’t need to keep the bookmark after I replied to it.
* Sometimes I will read the topic in mobile and I will prefer to reply in PC later. Or I may have to do some research before reply. So I will bookmark it for reply later.

### CODE REVIEW

**Comment by SamSaffron** [comment]
This feels like a combo box not 2 checkboxes: 

Automatically delete bookmark:

[Once I am reminded]
[After I reply]
[Never]


For an added bonus I think this setting should be "sticky" per browser. So after you change it it should remember for the next bookmark you make on the same browser (chucking it into localstorage I guess)

**Comment by martin-brennan** [comment]
@SamSaffron I moved the option into a dropdown and changed the DB column to an integer, can you please take another look at this one?

**Comment by SamSaffron** [comment]
UX looks great to me!

**Comment by SamSaffron** [comment]
The name "delete_option" is a bit strange, but I am struggling here to come up with an improvement.

Maybe `auto_delete`, it is a bit more reflective of it ... or maybe `auto_delete_preference`  ? naming is certainly hard.

**Pull request merged**
