### PR TITLE
Revert "UX: Better emoji escaping for topic title"

### PR DESCRIPTION
**Pull request by ZogStriP**
Reverts discourse/discourse#7176 as this is breaking the https://github.com/discourse/discourse-prometheus-alert-receiver plugin (specs are failing)

### CODE REVIEW

**Comment by ZogStriP** [comment]
cc @venarius can you have a look?

**Comment by venarius** [comment]
will do!

**Comment by venarius** [comment]
@ZogStriP 

Can't really test when there are already tests that fail before I even do a change. 

Screenshot from 2019-03-19 20-15-38

To be sure, I reinstalled my whole local discourse instance after [this](https://meta.discourse.org/t/beginners-guide-to-install-discourse-on-ubuntu-for-development/14727) Guide and installed both the [discourse-assign plugin](https://github.com/discourse/discourse-assign) and then the [discourse-prometheus-alert-receiver plugin](https://github.com/discourse/discourse-prometheus-alert-receiver).

After that I ran `bundle exec rake plugin:spec["discourse-prometheus-alert-receiver"]` and instantly half of the tests failed on me.

Any suggestions?

**Comment by ZogStriP** [comment]
Did you run the plugin migrations with `RAILS_ENV=test LOAD_PLUGINS=1 rake db:migrate`?

**Comment by venarius** [comment]
Yeah, that was the problem. Thanks a lot!

**Pull request merged**
