### PR TITLE
Please add info about the vagrant box architecture

### PR DESCRIPTION
**Pull request by rubo77**
if it is 32 bit or 64bit

### CODE REVIEW

**Comment by rubo77** [comment]
It seems like 
https://vagrantcloud.com/discourse/discourse-0.9.9.15.box
only works for 64 bit. Can you provide an alternate box for 32bit?

**Comment by rubo77** [comment]
It turned out, that the box is 32 bit already. The only problem was, that I had to enable Virtualization in my bios settings.

Had to restart my Computer to access bios and set it there, so this hint should be set in the vagrant file there somehow.

**Comment by coding-horror** [comment]
Ok, you signed the CLA?

**Comment by rubo77** [comment]
I signed. But this pull-request is just a kind of issue request..

The comment I added doesn't say anything yet.

Please close this PR and add a reasonable comment there instead

thx.
Rubo77

**Pull request closed without merging**
