### PR TITLE
UX: Dropdown not dismissing until next page renders.

### PR DESCRIPTION
**Pull request by tgxworld**
Address: https://meta.discourse.org/t/about-page-slow-menu-slow-to-disapear/24635.

### CODE REVIEW

**Comment by tgxworld** [comment]
One behavior that will change here is that when we search within a topic, clicking on any results will close the dropdown as opposed to the previous behavior where the search will remain open. Was the previous behavior by design?

**Comment by SamSaffron** [comment]
yes, previous behavior was by design.

**Comment by tgxworld** [comment]
@sam ok! I'll update the PR to take that into account.

**Comment by SamSaffron** [comment]
cool :+1:

**Pull request merged**
