### PR TITLE
FEATURE: Added outlet user-menu-glyphs

### PR DESCRIPTION
**Pull request by joebuhlig**

### CODE REVIEW

**Comment by erlend-sh** [comment]
Related topic:

https://meta.discourse.org/t/two-new-plugin-outlets-user-activity-bottom-and-user-menu-glyphs/40227

**Comment by SamSaffron** [comment]
My concern here is that it simply will not fit ... can you try the username WWWWWWWWWWWWW and post a screen mock of what happens with the extra glyph?

**Comment by joebuhlig** [comment]
Sure thing, Sam. I'll post it to the original topic on meta.

**Comment by cpradio** [comment]
And here is my suggestion for solving the issue.
https://meta.discourse.org/t/two-new-plugin-outlets-user-activity-bottom-and-user-menu-glyphs/40227/17?u=cpradio

**Comment by joebuhlig** [comment]
I'm closing this per this post: https://meta.discourse.org/t/two-new-plugin-outlets-user-activity-bottom-and-user-menu-glyphs/40227/18?u=joebuhlig

**Pull request closed without merging**
