### PR TITLE
FIX: Prefer user's primary group when setting title

### PR DESCRIPTION
**Pull request by riking**
https://meta.discourse.org/t/invited-person-s-account-should-have-its-title-set-from-the-primary-group/31465

### CODE REVIEW

**Comment by aral** [comment]
Hey Kane, thanks for the patch. Looks like there’s a syntax error in there. Looking forward to seeing this in production :)

     SyntaxError: /home/travis/build/discourse/discourse/app/models/user.rb:761: syntax error, unexpected &, expecting ']'

**Comment by riking** [comment]
Yep, I also need to write tests for it

**Comment by eviltrout** [comment]
It's still failing in travis? Are tests passing for you locally?

**Comment by riking** [comment]
Oh, it's failing a User.destroy_all. I was running 'short specs', specifying the files to run based on what failed in the first change

**Comment by eviltrout** [comment]
Ping @riking can you get this one up to snuff?

**Comment by ZogStriP** [comment]
Seems like the build is still failing on this one.

**Pull request closed without merging**
