### PR TITLE
Update code-of-conduct.md

### PR DESCRIPTION
**Pull request by aabowen**
Please add usage rights.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Hi Alex 

totally fine to add something here what should we be adding, can you link me to some examples.

**Comment by aabowen** [comment]
Is the CoC under a Creative Commons? Can we use and change the CoC if we use attribution, for example? Can we edit/change it as needed/wanted?

**Comment by SamSaffron** [comment]
Yes to everything, can you include some sample text of you would like to see and some links to other CoCs that contain such text.

**Comment by SamSaffron** [comment]
Let's just keep the discussion here please: 

https://meta.discourse.org/t/usage-rights-of-coc/63615

**Pull request closed without merging**
