### PR TITLE
DEV: Drop deprecated site settings for the 2.8 release.

### PR DESCRIPTION
**Pull request by tgxworld**

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
I think we should wait until after 2.8 to merge this. IMO we should remove deprecated things at the beginning of a release cycle, so that developers have the chance to fix up any broken plugin/themes before the release goes stable.

**Comment by tgxworld** [comment]
These have been deprecated in 2.7 and will be dropped in 2.8. Technically they already have the entire 2.7 release to fix the deprecation.

**Comment by davidtaylorhq** [comment]
Only if they checked the logs diligently, which is not always the case. I just checked our own logs, and we have at least one place where we're still using these old setting names in production.

**Comment by tgxworld** [comment]
Are you suggesting we keep the deprecation for another release or is the logging of the deprecation insufficient as a form of deprecation? Per the way deprecated site settings have been designed, we’ve given users the whole 2.7 release to fix the deprecation and have informed them these settings will be dropped in 2.8.

**Comment by CvX** [comment]
At the very least we should not break anything (even "planned" things) hours before release. We can drop it soon after, in 2.9.beta1 or beta2, when we're not on the lookout for any release-stopping issues.

**Comment by davidtaylorhq** [comment]
> Are you suggesting we keep the deprecations for another release

Ideally we would have dropped them shortly after starting the 2.8 beta. But we didn't, and so I think we now have to wait until shortly after starting the 2.9 beta.

> is the logging of the deprecations insufficient as the way of informing users of the deprecations?

Whatever we do, some people are going to miss the warnings. So I think we have to be mindful of that

**Comment by tgxworld** [comment]
In this case, I’ll change everything to be dropped in 2.9.

**Pull request closed without merging**
