### PR TITLE
FEATURE: Integrity hashes for scripts

### PR DESCRIPTION
**Pull request by riking**
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

image
---
image

The `logster_javascript` partial will only take effect when there is an error before vendor.js loads and runs & puts in the real onerror handler, but this is necessary to get reports of integrity violations.

---

~~don't pull this, it breaks prod atm: https://code.google.com/p/chromium/issues/detail?id=527286~~ Worked around

### CODE REVIEW

**Comment by eviltrout** [comment]
This is a cool idea but I feel that it should be hidden behind a feature flag at first. Can you add a site setting to enable/disable it? 

We can then try it out on various sites, see if there are issues then perhaps default it to Y at that point.

**Comment by SamSaffron** [comment]
hmmm ... what exactly are we gaining here feature wise?

**Comment by eviltrout** [comment]
It's more secure, as it ensures that assets haven't been tampered with. I think that's worth supporting.

**Comment by riking** [comment]
Actually, according to https://github.com/rails/sprockets-rails

> Sprockets 3.x adds experimental support for subresource integrity checks

so we should probably wait for that rather than that messy code in integrity_hash that relies on the asset config being specifically set up.

**Pull request closed without merging**
