### PR TITLE
DEV: Refactor draft attributes for `CategoryList` and `TopicList`.

### PR DESCRIPTION
**Pull request by tgxworld**
Avoid repeating the same logic in a bunch of places which will allow us
to make changes to the draft attributes easier in the future.

### CODE REVIEW

**Comment by SamSaffron** [comment]
I am fine with a refactor here but concerns ... concern me ... they hide where stuff is implemented I much prefer a static method here of sorts, can you refactor this elsewise?

**Comment by tgxworld** [comment]
> I am fine with a refactor here but concerns ... concern me ... they hide where stuff is implemented I much prefer a static method here of sorts

I'm not sure I understand what the concern here with concerns are. Isn't composition encouraged?

**Comment by SamSaffron** [comment]
In this case there is no need for any kind of concern class, just have both  inherit off BaseList or DraftableList? 

composition if fine, but I thing using concerns is a last resort after standard inheritance can not fit the bill.

**Comment by tgxworld** [comment]
We've generally been avoiding inheritance and preferring composition in our codebase so I still don't understand why including a module is not preferred here.

**Comment by tgxworld** [comment]
@SamSaffron I updated the PR per your review.

**Comment by tgxworld** [comment]
Merged in https://github.com/discourse/discourse/commit/b979579c1bec92d5e786a2004d0af8c9b07d5eab

**Pull request closed without merging**
