### PR TITLE
FIX: allows more chars than a-z in select-kit

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by SamSaffron** [comment]
@jjaffeux  this has drifted a bit, can you sort out and merge?

**Comment by jjaffeux** [comment]
@SamSaffron done 👍

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Pull request merged**
