### PR TITLE
FEATURE: updates emoji to latest 12.0 version

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by jjaffeux** [comment]
Something a little bit concerning is that a lot of images have been quite a significant increase in size. Not sure we can do anything about this though.

**Comment by SamSaffron** [comment]
I looked at one of these and we can halve the size by running it through pngquant. 

at a minimum we should run them via a lossless png compressor like pngout

**Comment by coding-horror** [comment]
did this regress? we always pngouted these

**Comment by jjaffeux** [comment]
Got less lucky on the ones I tried, was averaging at 1.5% win.

Will try with pngquant. And no we had stopped doing it, as it wasn’t giving any win, there is an extended topic about it on dev.

**Comment by jjaffeux** [comment]
Ok I did a full pass optim, there are big wins on apple set. Most of the others win nothing. I think apple emojis stopped being optimised on unicode site for some reason.

**Comment by ZogStriP** [comment]
LGTM 👍

**Comment by jjaffeux** [comment]
> LGTM 👍

I want to remove the specific categories as discussed

**Comment by SamSaffron** [comment]
I wants all my new emojis!!!! :waffles: are very important to me

**Comment by SamSaffron** [comment]
:waffles: :waffles: :waffles:

https://www.youtube.com/watch?v=8HOlXJ2EJxw

Let's get this merged 👍

**Comment by jjaffeux** [comment]
> I wants all my new emojis!!!! :waffles: are very important to me

waffles is not in this I'm sorry, it's not yet available

**Comment by jjaffeux** [comment]
I just updated the pr:

Screenshot 2019-03-15 at 15 51 59

**Pull request merged**
