### PR TITLE
UX: Adjust topic progress wrapper border radius

### PR DESCRIPTION
**Pull request by jordanvidrine**
This PR adjusts how border radius affects the topic progress wrapper.

**Before**
image

**After**
image

### CODE REVIEW

**Review by CvX — APPROVED** [review]

**Comment by tytekkit** [comment]
CleanShot 2023-11-20 at 15 14 02

I am seeing:
CleanShot 2023-11-20 at 15 12 56

**Comment by tytekkit** [comment]
To achieve this:

CleanShot 2023-11-20 at 15 15 57

I think...

```
#topic-progress-wrapper {
    .topic-admin-menu-button .toggle-admin-menu {
        border-top-right-radius: 0;
        border-bottom-left-radius: var(--d-border-radius); // added
        border-bottom-right-radius: 0;
    }
    #topic-progress {
        border-top-left-radius: 0; // added
        border-top-right-radius: var(--d-border-radius);
        border-bottom-right-radius: var(--d-border-radius);
    }
}
```

**Comment by tytekkit** [comment]
Seems there are more elements that try to break the borders:

CleanShot 2023-11-20 at 15 37 49

Fixing this and the case where the button is not there:

```
:root {
    --d-border-radius: 10px;
}

#topic-progress-wrapper {
    .topic-admin-menu-button .toggle-admin-menu {
        border-top-right-radius: 0;
        border-bottom-left-radius: var(--d-border-radius);
        border-bottom-right-radius: 0;
    }
    #topic-progress {
        &, & > .bg {
            border-radius: var(--d-border-radius);
        }
    }
    .topic-admin-menu-button-container + #topic-progress {
        border-top-left-radius: 0;
        border-top-right-radius: var(--d-border-radius);
        border-bottom-left-radius: 0;
        border-bottom-right-radius: var(--d-border-radius);
        & > .bg {
            border-top-left-radius: 0;
            border-top-right-radius: var(--d-border-radius);
            border-bottom-left-radius: 0;
            border-bottom-right-radius: var(--d-border-radius);
        }
    }
}
```

CleanShot 2023-11-20 at 15 44 17

CleanShot 2023-11-20 at 15 44 46

* This could probably be shorthand, but I'm not sure which styles shorthand might will be fighting with. *

**Comment by tytekkit** [comment]
Sorry for so many updates.
Taking advantage of ``overflow: hidden`` will prevent this:

284400989-e026e46d-5d20-4da4-862a-80fd33751e6b



:root {
    --d-border-radius: 10px;
}

#topic-progress-wrapper {
    .topic-admin-menu-button .toggle-admin-menu {
        border-top-right-radius: 0;
        border-bottom-left-radius: var(--d-border-radius);
        border-bottom-right-radius: 0;
    }
    #topic-progress {
        border-radius: var(--d-border-radius);
        overflow: hidden;
    }
    .topic-admin-menu-button-container + #topic-progress {
        border-top-left-radius: 0;
        border-top-right-radius: var(--d-border-radius);
        border-bottom-left-radius: 0;
        border-bottom-right-radius: var(--d-border-radius);
    }
}

**Comment by jordanvidrine** [comment]
Thanks for the help here Ty!

**Pull request merged**
