### PR TITLE
FIX: ensures invisible link is not interfering with UI/tab order

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by CvX** [comment]
I think you can achieve the same result without adding a new class by adding `visibility: hidden` to `#email-login-link` and `visibility: visible` to `input.value-entered + label.alt-placeholder + #email-login-link` on line 171.

**Comment by jjaffeux** [comment]
> I think you can achieve the same result without adding a new class by adding `visibility: hidden` to `#email-login-link` and `visibility: visible` to `input.value-entered + label.alt-placeholder + #email-login-link` on line 171.

yes... dunno... I find this kind of selectors very hard to reason about in the future

**Comment by CvX** [comment]
That's a valid point. But choose one method or the other, not both. 😃 E.g. remove that wacky plus-joined selector and then:

```scss
#email-login-link {
  transition: opacity 0.5s;

  &.no-login-filled {
    opacity: 0;
    visibility: hidden;
  }
}
```

**Comment by jjaffeux** [comment]
> That's a valid point. But choose one method or the other, not both. 😃 E.g. remove that wacky plus-joined selector and then:
> 
> ```css-scss
> #email-login-link {
>   transition: opacity 0.5s;
> 
>   &.no-login-filled {
>     opacity: 0;
>     visibility: hidden;
>   }
> }
> ```

yes sure can do that :+1: what makes it really easier is the added class not moving it out, but that's un-necessary agreed. I'm mostly not willing to move much in login code...

**Comment by jjaffeux** [comment]
@CvX made the change, tested it, seems good :+1:

**Review by CvX — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
