### PR TITLE
FIX: `created:@` search keyword for uppercase usernames

### PR DESCRIPTION
**Pull request by Canapin**
The filter wasn't working if the username had uppercase letters. This commit fixes it.

### CODE REVIEW

**Comment by Canapin** [comment]
This filter doesn't exist in the advanced search forum but can be used, so it might as well be working. 🙂
I noticed the tests don't try the filter with a username containing uppercase letters. Should this case be added?

**Review by pmusaraj — COMMENTED** [review]
Fix looks good to me. Any chance you can add a spec? There are some already under https://github.com/discourse/discourse/blob/main/spec/lib/search_spec.rb#L1944

**Comment by Canapin** [comment]
I'd be very happy to, but I've never written tests, and even looking at them I'm not sure how I should proceed, especially the part where the username should contain uppercase letters.

**Comment by pmusaraj** [comment]
Yeah, no worries @Canapin, I've just added a test. Approving, let's wait for specs to pass before merging. Thanks!

**Review by pmusaraj — APPROVED** [review]

**Pull request merged**
