### PR TITLE
FIX: Timegap only shows up for sequential posts.

### PR DESCRIPTION
**Pull request by tgxworld**
Meta:
* https://meta.discourse.org/t/large-time-gap-indicator-disappears-on-delete/30864/6
* https://meta.discourse.org/t/missing-x-months-ago-between-posts-when-post-numbers-are-not-continuous/32714

### CODE REVIEW

**Comment by coding-horror** [comment]
sweet! this has always bugged me, even if it handles the deleted post case that would be perfect :icecream:

**Comment by tgxworld** [comment]
@coding-horror This is how it'll look when the deleted post filter is applied

screenshot from 2015-09-02 17 29 37

**Comment by SamSaffron** [comment]
I wonder, is it desirable to be hiding time gaps when you collapse the stream, I think its actually quite useful there cc @eviltrout  @coding-horror

**Comment by coding-horror** [comment]
I am only worried about missing time gaps when posts are deleted at the moment.. are you referring to "Summarize This Topic" and filtering a topic by user?

**Comment by SamSaffron** [comment]
lets try this out!

**Pull request merged**
