### PR TITLE
UX: Use user locale for locations.

### PR DESCRIPTION
**Pull request by nbianca**

### CODE REVIEW

**Comment by ZogStriP** [comment]
Looks good 👍 Can you add a test as well?

**Comment by gschlager** [comment]
Looks good, but you might need to replace `_` in locale names with `-`. It looks like MaxMind uses a different format for locales:

|MaxMind|Discourse|
|---|---|
|de|de|
|en|en|
|es|es|
|fr|fr|
|ja|ja|
|pt-BR|pt_BR|
|ru|ru|
|zh-CN|zh_CN|

**Comment by SamSaffron** [comment]
looks good to me.

**Comment by gschlager** [comment]
Rubocop isn't happy @nbianca 😉 
https://travis-ci.org/discourse/discourse/jobs/446056582

**Pull request merged**
