### PR TITLE
FIX: trigger user_updated webhook when avatar changes

### PR DESCRIPTION
**Pull request by majakomel**
https://meta.discourse.org/t/user-profile-avatar-icon-not-triggering-webhook/117089

### CODE REVIEW

**Comment by SamSaffron** [comment]
As a pattern does it make sense to do all the hooking here vs deeper in service object or user after save? @tgxworld  / @vinothkannans  what pattern have you been following here?

**Comment by vinothkannans** [comment]
I think it should be in the user after save. Currently, except for user model everywhere else we're triggering the `_updated` in `after_commit` callback.

**Comment by tgxworld** [comment]
@majakomel Shouldn't we only trigger an event if `User#uploaded_avatar_id` changes? 

https://github.com/discourse/discourse/blob/648af78298f7ed15385504a252c0e1541044962a/app/models/user.rb#L1504

**Comment by tgxworld** [comment]
LGTM :+1: Thanks @majakomel

**Pull request merged**
