### PR TITLE
DEV: Move text area surround code out of d-editor

### PR DESCRIPTION
**Pull request by martin-brennan**
This commit moves _getMultilineContents and _applySurround into
TextareaTextManipulation, so other text area components using
that mixin can benefit from them (such as the chat composer).

### CODE REVIEW

**Comment by eviltrout** [comment]
If other components can use them, they should not be underscored, which indicates private. Let's drop that and it should be good to go.

**Comment by martin-brennan** [comment]
> If other components can use them, they should not be underscored, which indicates private. Let's drop that and it should be good to go.

I have a question about this, shouldn't they be private because this is just a mixin? The component isn't exposing these externally, it's using these private functions itself. For example the places we use TextareaTextManipulation are in the d-editor and the chat-composer. One of the functions `_focusTextArea` is already used by both internally, and I'm sure other ones that I'm not changing in this PR are too.

Just confused because I thought the underscore prefix should be used if not exposing the method to the outside (e.g. with actions)

**Comment by martin-brennan** [comment]
@eviltrout just had a question on this one, sorry forgot to mention you on the first message I sent

**Comment by eviltrout** [comment]
You are not wrong to ask @martin-brennan because it's a particular style call. Some OOP languages (like Ruby/C++) do not let you call private methods in subclasses. You have to mark them as protected. Others like Java let you do it.

My thinking is underscores should be used when in the same file. If you see them you are free to change them without worrying about other files relying on them.

This is particularaly useful in Discourse, where plugins/themes might mix in modules or subclass classes. If the API is that the underscored methods must be called, then any plugin could use those too! Then when you go to refactor, you have to search everywhere for any particular plugin that used it.

If other places in our code are doing this we should eventually fix those, too!

**Comment by martin-brennan** [comment]
Ah yes that's fair enough, thanks @eviltrout. In this PR I will also add sub methods without the underscore for all the methods already being used publicly, then I will make PRs for any plugins using them and change it over. Then a final PR to get rid of the underscored versions of the methods :+1:

**Comment by martin-brennan** [comment]
@eviltrout can you please take another look, I've added public wrappers to all the underscored functions that should be public, and after this PR is merged I will work through the plugins relying on the underscored versions.

**Pull request merged**
