### PR TITLE
FIX: prevents exception when search q params is a hash

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by jjaffeux** [comment]
An exception was happening for this kind of request for example:

`/search?q[aaa]=1`

**Comment by tgxworld** [comment]
Is the hash `q` params generated from the client side code? I think we should throw an error if `q` params is provided as a hash.

**Comment by jjaffeux** [comment]
> Is the hash `q` params generated from the client side code? I think we should throw an error if `q` params is provided as a hash.

no I dont think so, I just think sometimes people try things 🤷‍♂️ but I can raise InvalidParameters if you prefer

**Comment by tgxworld** [comment]
I think we should raise `InvalidParameters` here since there is no need for us to support the hash version of `q`

**Comment by jjaffeux** [comment]
> I think we should raise `InvalidParameters` here since there is no need for us to support the hash version of `q`

ok will amend to do this then

**Comment by jjaffeux** [comment]
@tgxworld updated

**Comment by tgxworld** [comment]
@jjaffeux Yay thank you for fixing this :+1:

**Pull request merged**
