### PR TITLE
FEATURE: allow group to be invited to topics

### PR DESCRIPTION
**Pull request by xrav3nz**
> CONTEXT & DISCUSSION: https://meta.discourse.org/t/rate-limiting-blocking-group-invitations-to-topics/73954/11?u=xrav3nz

Uploaded a quick video of the changes in the discussion topic linked above.

It'd be great if someone familiar with the invitation flow could take a look; there are also some copy changes to reflect the new behaviour.

Cheers 💪

### CODE REVIEW

**Comment by xrav3nz** [comment]
The failed test seems to be flaky acceptance test that is unrelated to the changes.

**Comment by tgxworld** [comment]
@xrav3nz The mailer that is sent out seems to have a missing body. Could you have a look? Thanks!

**Comment by tgxworld** [comment]
Pending the discussion in https://meta.discourse.org/t/allow-groups-to-be-invited-to-topics/73954/14?u=tgxworld

**Comment by xrav3nz** [comment]
> The mailer that is sent out seems to have a missing body. Could you have a look? Thanks!

Will do!

> The only access control methods we have for public topics are at the category level and I’m not sure if it would be easy to bypass that with invites at the moment.

Definitely didn't think of this before, thanks for pointing this out! I'll watch and follow the discussion on Meta.

**Comment by tgxworld** [comment]
Thank you for the work though @xrav3nz! We appreciate the time and effort you took in submitting this PR. :+1:

**Pull request closed without merging**
