### PR TITLE
UX: Make Post Notices consistent

### PR DESCRIPTION
**Pull request by darkpixlz**
I deleted the repository that had the original PR, sorry! This is a duplicate of it, nothing has changed.

Notices look like this in DMs:
image

But they look like this in posts:
image

So, in this PR I made them both look the same.
image

All old discussion is here, I just deleted `darkpixlz/discourse` stupidly, so it closed all of the PRs that were merged from my repository.
https://github.com/discourse/discourse/pull/17635

### CODE REVIEW

**Comment by darkpixlz** [comment]
image
Looks like the alignment may need to be changed in the future.

**Comment by darkpixlz** [comment]
The linting is prettier, will fix tomorrow

**Comment by darkpixlz** [comment]
After a week I finally fixed Prettier.

**Comment by darkpixlz** [comment]
The error seemed to be a bug, is fixed now

**Comment by jordanvidrine** [comment]
I believe the color change is fine, but adjusting to border radius and padding I do not agree with.

The padding & border radius are on PMs only in order for PMs to be more easily separated from the default topic view.

**Comment by darkpixlz** [comment]
> I believe the color change is fine, but adjusting to border radius and padding I do not agree with.
> 
> 
> 
> The padding & border radius are on PMs only in order for PMs to be more easily separated from the default topic view.
> 
> 

I agree, however I don't quite understand the difference with PMs in that case.

I think it's already pretty clear when a thread is a DM, although it may be a bit more confusing for some users.

The one in DMs creates a lot less clutter and in general looks better than the ones in topics right now. The extra padding makes things feel more spaced out and cleanser, and a refreshed look.

**Comment by jordanvidrine** [comment]
For the sake of simplicity I believe this PR should only address the color of the topic notice. 

I do understand your point, but the padding and border changes can be added to a theme or a theme component. For now it does not belong in core.

**Comment by darkpixlz** [comment]
In that case I will make something that's in between this and the current one

**Comment by pmusaraj** [comment]
Are you still working on this @darkpixlz?

**Comment by darkpixlz** [comment]
> Are you still working on this @darkpixlz?

Not really anymore, not sure about the failing tests.

**Comment by pmusaraj** [comment]
Closing this for now @darkpixlz, there's not enough support for adding padding/border radius changes to the regular topic notice atm.

**Pull request closed without merging**
