### PR TITLE
FEATURE: Staged user moderation

### PR DESCRIPTION
**Pull request by jose-hms**
Discussion found here: https://meta.discourse.org/t/email-staged-users-not-held-for-moderation/84068

### CODE REVIEW

**Comment by gschlager** [comment]
Thanks! Could you please add some tests?

**Comment by jose-hms** [comment]
Will do!

**Comment by jose-hms** [comment]
@gschlager Tests added.

**Comment by gschlager** [comment]
LGTM! 👍 Thanks!

**Pull request merged**
