### PR TITLE
FIX: Show parent and subcategories for 2nd level categories

### PR DESCRIPTION
**Pull request by udan11**

### CODE REVIEW

**Comment by ZogStriP** [comment]
Since this is a UX change, can you add some before/after screenshots?

Also, can you add a commit message that explains why this change is needed? (_future-you thanks you_)

**Comment by udan11** [comment]
Before:

Screen Shot 2019-12-18 at 17 03 55

After (with wider parent category chooser):

Screen Shot 2019-12-18 at 17 04 15

**Comment by ZogStriP** [comment]
Have you tested on mobile?

**Comment by udan11** [comment]
Mobile was left untouched because I could not widen the category chooser (not too much space there).

**Pull request merged**
