### PR TITLE
HACK: Added commit approved notification type for discourse-code-review

### PR DESCRIPTION
**Pull request by danielwaterworth**

### CODE REVIEW

**Comment by romanrizzi** [comment]
You can achieve the same outcome without touching core using this method:

https://github.com/discourse/discourse/blob/master/lib/plugin/instance.rb#L190

**Comment by danielwaterworth** [comment]
@romanrizzi, the ID needs to be reserved so that other plugins don't create conflicting notifications.

**Comment by SamSaffron** [comment]
I don't really see this as HACK, this is best practice ... :)

**Comment by danielwaterworth** [comment]
@sam, I see this as a hack because a plugin shouldn't have to modify core. Ideally, I think getting rid of the notification type ids and just using the names would be better.

**Pull request merged**
