### PR TITLE
refactors select-box

### PR DESCRIPTION
**Pull request by jjaffeux**
Note: this commit also now uses select-box for mobile topics controls

### CODE REVIEW

**Comment by coding-horror** [comment]
Can we merge this in @eviltrout or @tgxworld?

**Comment by jjaffeux** [comment]
Wait a minute please ;)

**Comment by jjaffeux** [comment]
But yes should be pretty safe to merge

screen shot 2017-08-16 at 00 37 56

The API and code needs more work, but I wanted to merge this before I leave for few days.

**Comment by coding-horror** [comment]
image

**Pull request merged**
