### PR TITLE
UX: simplifies UI for listing user auth tokens

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by jjaffeux** [comment]
@awesomerobot I'm not so sure about all of this. The existing design is mostly showing nothing more when expanding, so a simple table looks better.

However, with more thought:
1) we will have to add location at some point
2) the existing design works better on mobile

I let you decide what's best here.

**Comment by SamSaffron** [comment]
this is conflicting now that I merged @nbianca's changes

**Comment by SamSaffron** [comment]
closing for now

**Comment by jjaffeux** [comment]
@SamSaffron Yes what was at the beginning a simple lifting ends up being more of a "we should think more about this UI"

**Pull request closed without merging**
