### PR TITLE
DEV: Load SVG sprites during system spec runs

### PR DESCRIPTION
**Pull request by pmusaraj**
The svg sprite endpoint currently takes the hostname as a paramenter: as in `/svg-sprite/HOSTNAME/svg-1-hash.js`, however, in system specs we were previously setting the host to `localhost:31337`, which is not a valid param for that route, and so the svg sprites won't load.

It seems incorrect in general to include the port in the `SiteSetting.force_hostname` setting, removing the port there fixes svgs in system specs, but only if system specs skip the force_hostname middleware.

(This solution isn't perfect, because it can cause unexpected issues if running a subset of non-system and system specs together. For example, this will: 

`bin/rspec spec/system/bookmarks_spec.rb spec/integration/twitter_omniauth_spec.rb`

We do skip system tests in `turbo_rspec`, so it is generally not a good idea to run system and non-system specs together. (Maybe we can make this clearer using a warning?)

### CODE REVIEW

**Review by martin-brennan — APPROVED** [review]
@pmusaraj I would just go ahead and merge this, doesn't seem like there are any objections and this error is _really_ annoying. Thanks for doing this :)

**Comment by pmusaraj** [comment]
@martin-brennan I think you're right. In fact, I pushed a change that sets that ENV variable for all specs, it looks like the middleware spec isn't affected by the environment variable, so we're probably good to set it this way. 

Go ahead and merge if tests pass (late here).

**Comment by davidtaylorhq** [comment]
I think the fundamental issue here is that our 'enforce hostname' middleware doesn't work alongside our `SiteSetting.port` option. If we can fix that, then a lot of these system-spec-specific overrides can be removed and we won't have to try and parse `ARGV`.

I haven't had a chance to test it extensively yet, but I've pushed up this idea which builds on top of this branch: https://github.com/discourse/discourse/compare/fix-svgs-in-system-specs-david

**Comment by pmusaraj** [comment]
@davidtaylorhq That approach looks great to me, I much prefer fixing the middleware vs. avoiding for a subset of specs. 

@martin-brennan please bear with the annoying errors for a tiny bit longer until we test/fine-tune David's fix.

**Comment by martin-brennan** [comment]
@pmusaraj sounds good to me! Thanks @davidtaylorhq for doing this additional fix too :pray:

**Review by davidtaylorhq — APPROVED** [review]

**Comment by davidtaylorhq** [comment]
Pushed my change here and it seems to be passing tests. Also confirmed that svg_sprites are loading correctly when running locally.

I'm happy for this to be merged. Will leave it for someone else to double-check my commit and do a final approve/merge

**Comment by pmusaraj** [comment]
Double-checked locally, works well.

**Pull request merged**
