### PR TITLE
Log username changes

### PR DESCRIPTION
**Pull request by riking**
https://meta.discourse.org/t/admin-name-changes-dont-appear-in-logs/23927

image

### CODE REVIEW

**Comment by coding-horror** [comment]
:+1:

**Comment by ZogStriP** [comment]
Mind squashing the commits? ;)

**Comment by riking** [comment]
@ZogStriP done

**Comment by ZogStriP** [comment]
:+1:

**Comment by dangtrungluong** [comment]
how to disable logs?

**Pull request merged**
