### PR TITLE
FIX: Explicitly set `allowfullscreen` on Wistia Oneboxes

### PR DESCRIPTION
**Pull request by jbrw**

### CODE REVIEW

**Review by pmusaraj — APPROVED** [review]

**Comment by tgxworld** [comment]
I'm not sure but will it be possible to test this change?

**Comment by jbrw** [comment]
> I'm not sure but will it be possible to test this change?

Other Oneboxes have 'response' fixtures which we use to test the various Onebox engines.

In this case the breakage in the Wistia Onebox Engine seems to have been caused by Wistia changing the response they were sending back to us, which we wouldn't have picked up with a test.

Perhaps it's better to test things as they stand today, rather than not test at all. But would that just be giving us a false sense of security?

**Comment by tgxworld** [comment]
> Perhaps it's better to test things as they stand today, rather than not test at all. But would that just be giving us a false sense of security?

I don't think it gives us a false sense of security. By testing things as it is today, we at least ensure that what we have today is working properly and also helps other developers make changes safely in the future.

**Comment by SamSaffron** [comment]
I agree testing would be handy, but the type of testing we need to keep wistia and other oneboxes going is different. 

Maybe we need some sort of daily integration **real** test that we run that walks through all oneboxes and ensures that they all operate as they are supposed to. Something external to our test suite. 

Agree with @jbrw's sentiment here of "what is the point"... if a test would have caught the regression being fixed here, sure I totally support adding it, but what we are proposing here is adding a test that will not catch future issues that lead to this PR in the first place.

**Comment by tgxworld** [comment]
@SamSaffron How do we know that the changes here are even working without tests?

**Comment by tgxworld** [comment]
> My point is, how do we even know if the changes are working with a test?

We use fixtures just like how we do for other oneboxes. The change introduced in this code is based on the current response returned from Wistia. Given the current response, we add a test to ensure what we're doing is actually working. 

> Only way to really find out is make a real onebox request to Wistia and confirm we get a reasonable onebox out of that. Everything else is just playing the mock game that ends up biting you back.

I don't agree that if we can't do an end to end real life integration tests, other tests are just pointless. Note that our entire suite of client side test is basically mocking the server's response. However, that doesn't mean we do not get any value of out the tests.

**Pull request merged**
