### PR TITLE
FIX: confirm email token for user created via social login

### PR DESCRIPTION
**Pull request by techAPJ**

### CODE REVIEW

**Comment by coding-horror** [comment]
what is this in reference to?

**Comment by techAPJ** [comment]
@coding-horror: https://meta.discourse.org/t/auto-add-to-group/60764?u=techapj

Currently users who login via social login method are not getting added to group automatically based on their email domain because their email token is not getting confirmed.

**Comment by coding-horror** [comment]
ok I was just uncertain what this was :+1:

**Comment by ZogStriP** [comment]
There probably shoud be a test here since it's a nasty one ;)

**Pull request merged**
