### PR TITLE
Update discourse_tagging.rb

### PR DESCRIPTION
**Pull request by Toxu-ru**

### CODE REVIEW

**Comment by ZogStriP** [comment]
Mind explaining what does this solve? Also, it would be awesome if there was a test validating the new behavior.

**Comment by Toxu-ru** [comment]
Thank you, write what it makes

**Comment by tgxworld** [comment]
Hi @Toxu-ru, can you please add a test case here :+1:

**Comment by Toxu-ru** [comment]
The correct changes are:

68. - term.gsub!(/[^a-z0-9\.\-\_]*/, '')
68. + term.gsub!(/[^a-z0-9\p{Alnum}\.\-\_]*/, '')

It adds a search to Russian letters in tags. 
Leaving the search for English letters and numbers (a-z0-9).

**Comment by coding-horror** [comment]
Didn't @nlalonde change this recently?

**Comment by nlalonde** [comment]
Yes, I fixed this last week. `clean_tag` is the one place that should be parsing tag inputs.

https://github.com/discourse/discourse/commit/a509146ea561edff1f58c69f155293d9f4688b61

But your other PRs (4881, 4883) are for the advanced search which seems to still be broken.

**Pull request closed without merging**
