### PR TITLE
FIX: Use plugin category name for plugin list

### PR DESCRIPTION
**Pull request by martin-brennan**
Followup to e37fb3042d6f56a27a01614e57bc7029f472b0c9

Some plugins like discourse-ai and discourse-saml do not
nicely change from kebab-case to Title Case (e.g. Ai, Saml),
and anyway this method of getting the plugin name is not
translated either.

Better to use the plugin setting category if it exists,
since that is written by a human and is translated.

### CODE REVIEW

**Comment by nattsw** [comment]
What's the side effect of this change?

**Comment by nattsw** [comment]
Can I check what is the side effect? Discourse AI seems to be ok before the change, but I could be looking at the wrong place.

**Comment by martin-brennan** [comment]
> Can I check what is the side effect? Discourse AI seems to be ok before the change, but I could be looking at the wrong place.

@nattsw the plugin category name for site settings is used:

image

We just did a big pass to update these to the correct thing. Before this change, "Discourse AI" is correct because of my hacky acronym rule, but "Discourse SAML" would show as "Discourse Saml" and any other acronym > 2 letters would do the same. This is much more consistent and uses human-defined, translated names.

**Review by nattsw — APPROVED** [review]

**Comment by nattsw** [comment]
Ship it with your component test! 🚀

**Pull request merged**
