### PR TITLE
DEV: Migrate about config area to Form Kit

### PR DESCRIPTION
**Pull request by OsamaSayegh**

### CODE REVIEW

**Comment by OsamaSayegh** [comment]
@jjaffeux I've noticed that when using fields with custom controls, we don't get titles or subtitles for the field even though they're passed to `<form.Field>`. Is this intentional?

**Comment by jjaffeux** [comment]
> @jjaffeux I've noticed that when using fields with custom controls, we don't get titles or subtitles for the field even though they're passed to `<form.Field>`. Is this intentional?
> 
> 

No that's not, will look

**Comment by OsamaSayegh** [comment]
@jjaffeux I think it's ready now!

**Review by jjaffeux — APPROVED** [review]

**Comment by jjaffeux** [comment]
Nice!

**Comment by OsamaSayegh** [comment]
Thanks for the help and review with this one Joffrey!

**Comment by jjaffeux** [comment]
> Thanks for the help and review with this one Joffrey!

My pleasure

**Pull request merged**
