### PR TITLE
DEV: Drop 'key' column from user_api_keys

### PR DESCRIPTION
**Pull request by udan11**

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Looks good to me, just a couple of test failures in CI to clean up

**Comment by SamSaffron** [comment]
I am fine with this, merge at will

**Comment by davidtaylorhq** [comment]
I think we're waiting on a theme-creator update which @udan11 is working on, then this will be good to merge

**Comment by davidtaylorhq** [comment]
Are we good to merge this now @udan11 ?

**Pull request merged**
