### PR TITLE
the header, in flexbox

### PR DESCRIPTION
**Pull request by awesomerobot**
Requires update to tagging plugin: 

https://github.com/discourse/discourse-tagging/pull/43

tested in:

Firefox
screenshot 2015-09-05 23 57 26

Safari
screenshot 2015-09-05 23 57 43

Chrome
screenshot 2015-09-05 23 58 12

IE11
screenshot 2015-09-05 23 58 55

iOS
screenshot 2015-09-06 01 04 18

### CODE REVIEW

**Comment by coding-horror** [comment]
Thanks for your persistence on this one, I know it has been hard. Much appreciated :pray:

**Comment by coding-horror** [comment]
let's merge this in 1.5 early .. 1.5 will be starting middle of next week

**Comment by ZogStriP** [comment]
I'm closing this since it's not _mergeable_ anymore... This probably needs another pass anyway. Sorry @awesomerobot

**Comment by nlalonde** [comment]
@awesomerobot I have [a branch](https://github.com/discourse/discourse/tree/flexheader) where I've manually merged in your work and made some fixes. It's _almost working_, but there's just one problem left. Can you have a look? My demo site is here:

http://flexheader.neillalonde.com/t/ie11-header-dropdown-toggle-bug/13

-----

On IE11, there's a bug:

afe00ae35f9b1b64edd0c830b95ba39c2f2a453d

The .d-header .icons .header-dropdown-toggle elements have a computed width of 10px, even though we specify 40px. If I remove the width: 40px, then they don't render on top of each other (but are obviously not wide enough).

In IE10, everything renders fine. Sadly, this is only an IE11 bug.

**Pull request closed without merging**
