### PR TITLE
FIX: Censored words filter not applied to title.

### PR DESCRIPTION
**Pull request by tgxworld**
meta: https://meta.discourse.org/t/profanity-filter-not-working-on-titles-topic-subject-line/31093

### CODE REVIEW

**Comment by ZogStriP** [comment]
Thanks :+1:

**Comment by tgxworld** [comment]
@ZogStriP Do you know if there are plans to move the dialect modules to es6? However, I don't think it will work with the V8 interpreter though.

**Comment by ZogStriP** [comment]
Yeah we do have plans to move dialects to ES6. It's super hard though... We might do that at the same time we change to a better markdown engine.

**Comment by tgxworld** [comment]
:+1:

**Pull request merged**
