### PR TITLE
PERF: uses innerHTML to decide if fast-edit is possible

### PR DESCRIPTION
**Pull request by jjaffeux**
We don't need raw to decide if we can fast edit or not, we will fetch the raw later when we do the replacement, but this step can be done directly from innerHTML.

### CODE REVIEW

**Review by CvX — COMMENTED** [review]
Cooked HTML won't work with the current logic:

```js
quoteState.buffer.includes("|") || // tables are too complex
quoteState.buffer.match(/\n/g) || // linebreaks are too complex
```

**Comment by jjaffeux** [comment]
> Cooked HTML won't work with the current logic:
> 
> ```js
> quoteState.buffer.includes("|") || // tables are too complex
> quoteState.buffer.match(/\n/g) || // linebreaks are too complex
> ```

why?

**Comment by CvX** [comment]
Ah, sorry, somehow I thought those matches were made against the post body…

Anyway, is this PR (on its own) a PERF fix if the `postBody` was already available? Where does the performance come from?

**Comment by jjaffeux** [comment]
> Ah, sorry, somehow I thought those matches were made against the post body…
> 
> Anyway, is this PR (on its own) a PERF fix if the `postBody` was already available? Where does the performance come from?

It's not directly a perf improvement, but removing the usage of `postBody` removes one case where we need it and could eventually lead to fully remove relying on it. What do you think we should name this kind of in-progress perf?

**Comment by CvX** [comment]
I'd tag it DEV as it's a kind of a micro-refactor.

**Review by CvX — APPROVED** [review]

**Pull request merged**
