### PR TITLE
UX: Love hearts.

### PR DESCRIPTION
**Pull request by tgxworld**
screenshot from 2015-08-31 00 45 30

### CODE REVIEW

**Comment by ZogStriP** [comment]
@coding-horror do we want that?

**Comment by coding-horror** [comment]
Probably not on the home page per se, but Likes column is not visible by default anyway, so ... maybe it doesn't matter?

**Comment by ZogStriP** [comment]
Yeah I guess it makes it consistent.

**Comment by SamSaffron** [comment]
Nahh I much prefer this in monochrome here ...

**Pull request merged**
