### PR TITLE
FIX: Hashtag length increased to 101 instead of 50 chars.

### PR DESCRIPTION
**Pull request by tomasibarrab**
I increased the char length for the hashtags to 101 characters, in order to solve this bug: https://meta.discourse.org/t/hashtag-linking-to-categories-doesn-t-always-work/41003/7

### CODE REVIEW

**Comment by tomasibarrab** [comment]
I merged my last commit to delete the blanking spaces too. @coding-horror

**Comment by ZogStriP** [comment]
61 files changes for only 1 line changed? Can you rework your pull request and just change the 1 line? (also ccing @tgxworld since he built this)

**Comment by tgxworld** [comment]
Please remove all the blank line changes as we dont accept cosmetic changes which pollute the git history. Otherwise the PR looks good. :+1:

**Comment by tomasibarrab** [comment]
Let me just do it, sorry.

**Comment by tomasibarrab** [comment]
Can we close this? I already made another PR to solve this issue. Thanks! @tgxworld

**Pull request closed without merging**
