### PR TITLE
FIX: Don't attempt to add user again to a group when syncing groups via SSO

### PR DESCRIPTION
**Pull request by OsamaSayegh**
Fixes regression introduced in https://github.com/discourse/discourse/commit/8979adc3afa4cb6c0cd3b47a8d1172583a01a510.

### CODE REVIEW

**Comment by jjaffeux** [comment]
Im wondering if we shouldn't just have an `ON CONFLICT DO NOTHING` when trying to add duplicate? Is there any case where we want to catch this or it should always be a noop?

**Comment by OsamaSayegh** [comment]
It's a bit annoying because we'd have to go full on raw SQL because ActiveRecord doesn't seem to have an option for `ON CONFLICT DO NOTHING` and also we need to know which groups the user actually ends up getting added to so that we can add logs to the groups logs (i.e. we don't want to log that a user is added to a group when they're already a member of that group).

**Comment by jjaffeux** [comment]
I think most of this could be solved with upsert/upsert_all: https://edgeapi.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-upsert_all

Maybe not worth investigating right now, but I think we have had multiple cases of errors due to this and to me adding someone to a group should not be risky and require so much logic.

**Comment by OsamaSayegh** [comment]
Another issue is that `upsert_all` skips all AR callbacks and validations and we do have a number of those in the `GroupUser` model:

https://github.com/discourse/discourse/blob/4b6a5f08faaae9264d1d35a394a4f35b455f1477/app/models/group_user.rb#L7-L16

We'd need to do a fairly big refactor to the callbacks/model so that they can be called without a model object and then manually execute the logic after `upsert_all` for the groups that user was added to. I feel like the complexity/logic would just move from one place to another for very little benefit.

**Comment by jjaffeux** [comment]
> I feel like the complexity/logic would just move from one place to another for very little benefit.

I kinda disagree on this as we already have regressed/failed multiple times on this. But as I said earlier, this might not be something we want to investigate in this PR.

**Comment by OsamaSayegh** [comment]
Yeah I think this is something we can investigate later. We've had quite an eventful week this week and I'd rather not risk breaking SSO and/or groups with a big refactor that using `upsert_all` would require.

**Comment by OsamaSayegh** [comment]
@jjaffeux can you approve if the PR looks good please?

**Review by davidtaylorhq — APPROVED** [review]

**Pull request merged**
