### PR TITLE
DEV: Correctly tag heredocs

### PR DESCRIPTION
**Pull request by CvX**
This allows text editors to use correct syntax coloring for the heredoc sections.

Heredoc tag names we use:

languages: SQL, JS, RUBY, LUA, HTML, CSS, SCSS, SH, HBS, XML, YAML/YML, MF, ICS
other: MD, TEXT/TXT, RAW, EMAIL

### CODE REVIEW

**Comment by eviltrout** [comment]
I was not aware editors used this for syntax highlighting. Vim certainly doesn't. Is it common?

**Comment by CvX** [comment]
I don't know how common, but VSCode does this out of the box I think. There's a plugin for vim as well: https://github.com/joker1007/vim-ruby-heredoc-syntax

**Review by eviltrout — APPROVED** [review]
I think it's a good idea. A gut reaction of mine was that sometimes I like to name these semantically, but I see that it's rarely done that way, and for SQL the language name is often already used.

**Comment by CvX** [comment]
Yeah, the vast majority of heredocs were tagged like this already.

**Pull request merged**
