### PR TITLE
FIX: Mark invites flash messages as HTML safe.

### PR DESCRIPTION
**Pull request by romanrizzi**
Context: https://meta.discourse.org/t/html-tags-are-explicit-after-latest-update/214220

### CODE REVIEW

**Review by nattsw — DISMISSED** [review]

**Review by CvX — COMMENTED** [review]
Did you take into consideration notes from the dev topic (/t/56719)? 😃 i.e. are you positive it's safe?

**Comment by jjaffeux** [comment]
> Did you take into consideration notes from the dev topic (/t/56719)? 😃 i.e. are you positive it's safe?

Yep Im wondering the same, given it can be generated from errors/warnings... is there no way you can craft something so contain valid html in the error generated?

**Comment by romanrizzi** [comment]
Wasn't aware of that. 😅

I'll make sure it's safe first.

**Comment by SamSaffron** [comment]
I want a fix merged prior to release, but we need 100% guarantee on safety here, I would like 2 PR approvals here please.

**Comment by romanrizzi** [comment]
@SamSaffron -  I'm thinking of using the rails HTML sanitizer to sanitize the user input before sending the error back to the client. We already do this for translations and other inputs. We can use this to forbid any HTML since they're either email addresses or domains.

I'll update the PR and ask for a review before EOW.

**Comment by romanrizzi** [comment]
Alright, I looked at all the invite validation errors containing user input and sanitized them before sending them back to the client. This should be ready for review now.

**Review by CvX — APPROVED** [review]

**Review by CvX — APPROVED** [review]

**Review by gschlager — APPROVED** [review]
LGTM

**Comment by davidtaylorhq** [comment]
Why are we 'sanitize`-ing things here? HTML sanitisation is used when we want to **allow** user input to contain HTML, but we want to limit which elements/attributes can be included include. I think in this case we want to ban HTML completely... so shouldn't we be `escape`-ing rather than `sanitize`-ing?

(i.e. `CGI.escapeHTML` in Ruby, `{ escape } from "pretty-text/sanitizer"` in JS)

**Comment by romanrizzi** [comment]
> Why are we `sanitize`-ing things here? HTML sanitisation is used when we want to **allow** user input to contain HTML, but we want to limit which elements/attributes can be included. I think in this case we want to ban HTML completely... so shouldn't we be `escape`-ing rather than `sanitize`-ing?
> 
> (i.e. `CGI.escapeHTML` in Ruby, `{ escape } from "pretty-text/sanitizer"` in JS)

We don't want to ban it at the client level because the error message does include HTML independently of the user input. 

I sanitized the input for each error, but this doesn't stop someone from adding a new error with unsanitized user input in the future, so I thought it was a good idea to add an extra layer of protection.

**Comment by davidtaylorhq** [comment]
Hmm ok, so the use of sanitize on the JS side is deliberate :+1:

> I sanitized the input for each error

This is the key part. Why sanitize the user input? Shouldn't we be escaping it? We don't want people to be use an email address like `<huge>I can break the UI</huge>@gmail.com` to break the UI.

**Comment by romanrizzi** [comment]
> > I sanitized the input for each error
> 
> This is the key part. Why sanitize the user input? Shouldn't we be escaping it? We don't want people to be use an email address like `<huge>I can break the UI</huge>@gmail.com` to break the UI.
 
That wouldn't be a problem because the sanitizer we use forbids any kind of HTML. However, since we're not storing the user input when we raise these errors, I think you're right and it's simpler to just use `escapeHTML`.

**Review by davidtaylorhq — APPROVED** [review]

**Pull request merged**
