### PR TITLE
Update rspec to v3

### PR DESCRIPTION
**Pull request by lucianosousa**
Really appreciate a help here :)

### CODE REVIEW

**Comment by fantasticfears** [comment]
I respect that, bro.

**Comment by lucianosousa** [comment]
today later is done! :sweat:

**Comment by lucianosousa** [comment]
```
Deprecation Warnings:

 The Autospec::Formatter formatter uses the deprecated formatter interface not supported directly by RSpec 3.  To continue to use this formatter you must install the `rspec-legacy_formatters` gem, which provides support for legacy formatters or upgrade the formatter to a compatible version.  Formatter added at: /Users/luciano/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'

````

@ZogStriP can you help me with this? almost finished this wip. just this warning is pending.

**Comment by ZogStriP** [comment]
@lucianosousa guess you need to use the `register` method now instead of subclassing (cf .https://relishapp.com/rspec/rspec-core/docs/formatters/custom-formatters)

**Comment by lucianosousa** [comment]
@ZogStriP can you check this?

Did this:
```
class Autospec::Formatter
  RSpec::Core::Formatters.register self, :example_passed
  RSpec::Core::Formatters.register self, :example_pending
  RSpec::Core::Formatters.register self, :example_failed

  RSPEC_RESULT = "./tmp/rspec_result"

  def initialize(output)
    super
    FileUtils.mkdir_p("tmp") unless Dir.exists?("tmp")
  end

  ...
end
```

But doesn't work.
```
Running Rspec: ./spec/components/cooked_post_processor_spec.rb:134 
/Users/luciano/Dropbox/projects/discourse/lib/autospec/formatter.rb:13:in `initialize': wrong number of arguments (1 for 0) (ArgumentError)
	from /Users/luciano/Dropbox/projects/discourse/lib/autospec/formatter.rb:13:in `initialize'
```

 I've never used custom formatters. Can you take a look how it can be solved?

**Comment by lucianosousa** [comment]
@ZogStriP can you merge just that part? I'll improve the another set later. Looks like some specs are broken here. Also, I'll continue working against the master branch

**Comment by ZogStriP** [comment]
Can you squash the commits into 1 commit ? :heart_eyes:

**Comment by ZogStriP** [comment]
Also, the build failed. Seems like you missed a spot.

**Comment by lucianosousa** [comment]
@ZogStriP done. fixed specs too. just waiting build

**Comment by ZogStriP** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:

**Comment by lucianosousa** [comment]
let's continue working now! :)

**Pull request merged**
