### PR TITLE
Prepare for separate RSpec helper files

### PR DESCRIPTION
**Pull request by andyw8**
Since rspec-rails 3, the default installation creates two helper files:
* `spec_helper.rb`
* `rails_helper.rb`

`spec_helper.rb` is intended as a way of running specs that do not
require Rails, whereas `rails_helper.rb` loads Rails (as Discourse's
current `spec_helper.rb` does).

For more information:

https://www.relishapp.com/rspec/rspec-rails/docs/upgrade#default-helper-files

In this commit, I've simply replaced all instances of `spec_helper` with
`rails_helper`, and renamed the original `spec_helper.rb`.

This brings the Discourse project closer to the standard usage of RSpec in a Rails app.

At present, every spec relies on loading Rails, but there are likely
many that don't need to. In a future pull request, I intend to introduce a
separate, minimal `spec_helper` which can be used in tests which don't
rely on Rails.

### CODE REVIEW

**Comment by SamSaffron** [comment]
I am afraid of this commit, a real side effect we saw in the past when we allowed these huge changes it that your name shows up everywhere when people browse the project on github, I would prefer if the team just slowly moved to this pattern each time we commit changes to a specific spec 

@eviltrout  thoughts?

**Comment by eviltrout** [comment]
I actually have no objections to this commit at all. It's a rename and is probably quite safe. Doesn't bother me if someone's name shows up on github either -- what is the concern there?

**Comment by andyw8** [comment]
I appreciate that wide changes such as this do somewhat pollute the git history.

I think the alternative approach @SamSaffron suggest would difficult to enforce, and it would likely take several years to move everything over, possibly causing confusion in the mean time due the two different styles present.

**Comment by SamSaffron** [comment]
@andyw8  ok I will merge this in if you rebase

**Comment by andyw8** [comment]
@SamSaffron I've rebased.

**Comment by SamSaffron** [comment]
thanks @andyw8  appreciated

**Comment by tgxworld** [comment]
@SamSaffron I think we should notify plugin authors that wrote specs about this. :smile:

**Comment by gdpelican** [comment]
Yarp, I just tripped over this. Assuming I can just rename spec_helper to rails_helper like in here and everything will be fine.

**Pull request merged**
