### PR TITLE
FIX: Clicking 'show more' should not dismiss search dropdown.

### PR DESCRIPTION
**Pull request by tgxworld**
cc/ @SamSaffron

### CODE REVIEW

**Comment by tgxworld** [comment]
O wait... if we're not searching within a topic. Should clicking on `show more` dismiss the dropdown?

**Comment by SamSaffron** [comment]
if we are not within a topic it should dismiss (it also is a standard link)
unless we click show more on category / user.

**Comment by tgxworld** [comment]
@SamSaffron That should fix it. I did come across another bug though (I didn't break that :stuck_out_tongue_closed_eyes: ), if a dropdown is active and we click on a link outside of the dropdown if doesn't dismiss.

**Comment by SamSaffron** [comment]
thanks, yeah looks good

**Pull request merged**
