### PR TITLE
[DEPENDABOT PORT]: Bump dependency versions

### PR DESCRIPTION
**Pull request by sau226**
Exact PR's and release notes can be seen at [https://github.com/sau226/discourse/pulls?q=is%3Apr+is%3Aclosed](https://github.com/sau226/discourse/pulls?q=is%3Apr+is%3Aclosed).

This PR bumps the rubocop, mustache, unicorn, better_errors, aws-sdk-s3, rspec, danger and redis versions. Any other changes will be submitted in later PR's

### CODE REVIEW

**Comment by sau226** [comment]
Also is there really a problem or is Travis just crying wolf again?

**Comment by tgxworld** [comment]
Please rebase to latest as we had a broken spec yesterday.

**Comment by sau226** [comment]
@tgxworld I've synced my branch with master. Will that be enough or should I start fresh?

**Comment by tgxworld** [comment]
@sau226 I think you should rebase your branch against master and force push to your branch. Also, can I find out what the dependabot thing is about? We would prefer to have the commit message be free of `Build(deps)` which doesn't add any value.

**Comment by sau226** [comment]
@tgxworld Dependabot is basically a script that automatically upgrades Ruby dependencies (more info about its proposed use on Discourse [here](https://meta.discourse.org/t/use-dependabot-for-dependency-updates/98823)). As the creator states that their GitHub app requires write access to the Discourse repo to allow for its patches, the app has been presently rejected for Discourse's main repo. I don't have a problem with allowing the app to write to my fork of the repo and my fork is constantly synced with that of the canonical Discourse repo so I don't have a problem with integrating patches into Discourse's master branch.

The bot is making commits to my fork using the message format you stated and to be honest I have no control over what it uses for a commit message. If you prefer I can tell GitHub to use a different merge method (squash merge) so that their commit message doesn't get logged in GitHub (the disadvantage is not giving credit to the app) and I can set something like `UPDATE: Updating dependencies` or similar if you prefer.

**Comment by sau226** [comment]
I'm closing this PR due to a major screwup and I'll try to fix it later (no guarantees though)

**Pull request closed without merging**
