### PR TITLE
Remove extra trailing blank spaces from server.en.yml

### PR DESCRIPTION
**Pull request by AhmadFCheema**
As noted in [this comment](https://github.com/discourse/discourse/pull/7759#issuecomment-501267443).

### CODE REVIEW

**Comment by coding-horror** [comment]
I support this but I think it will break translations @SamSaffron ? So maybe this has to wait until 2.4 beta?

**Comment by eviltrout** [comment]
Not I merged some earlier translations today because I missed the note about holding off for 2.4. @SamSaffron should I revert those?

**Comment by AhmadFCheema** [comment]
If it's relevant, the change affects just three translation strings and there too the translators would have to just re-save the previously translated ones.

**Comment by SamSaffron** [comment]
Definitely can not happen for 2.3, got to wait till next week to merge.

**Comment by gschlager** [comment]
We need to ensure that we don't lose existing translations on Transifex. Some of these minor changes affect quite important strings. I'm assigning this to myself.

**Comment by gschlager** [comment]
Thanks! Merged in https://github.com/discourse/discourse/commit/bfbd97d3b52ac72434102ab80e4d6bfa33b7e7ad

**Pull request closed without merging**
