### PR TITLE
DEV: Remove `{{user-selector}}`

### PR DESCRIPTION
**Pull request by OsamaSayegh**
`{{user-selector}}` was deprecated in https://github.com/discourse/discourse/commit/293fd1f743b1c8165e1cd06b1169134197a231f7 over a year ago and it's time we deleted it.

### CODE REVIEW

**Review by ZogStriP — APPROVED** [review]

**Comment by CvX** [comment]
Confirming as always - nothing in all-the* and in hosted uploaded themes is using the old component? 😃

**Comment by nbianca** [comment]
@OsamaSayegh, how do you feel about adding a deprecation notice user-selector for now and planning its removal in 3.1? I believe we are too close to the release and this can break plugins or themes. I think even we have a few themes that still use it (from a quick grep over all-the-x).

**Comment by OsamaSayegh** [comment]
> adding a deprecation notice to user-selector

Yeah `{{user-selector}}` has been deprecated for a while now:

https://github.com/discourse/discourse/blob/6e65e4a9351619898a361d281b6771d71a620cc5/app/assets/javascripts/discourse/app/components/user-selector.js#L16-L22

I agree this PR should wait until 3.0 is released. I'll review everything in all-the-(plugins|themes) repos before merging this PR.

**Comment by SamSaffron** [comment]
@OsamaSayegh are we good to merge this? (looks like it needs a rebase)

**Pull request merged**
