### PR TITLE
do not require an email in smtp_should_reject handler

### PR DESCRIPTION
**Pull request by evgeni**
It is perfectly OK for an SMTP session not to have a FROM address [1],
and while such mail will probably still be rejected/filtered at a later point
by Discourse, we should not reject it at SMTP time.

Currently, such mails get rejected with:

    450 4.7.1 <recipient@example.com>: Recipient address rejected: Internal error, API request failed

[1] https://datatracker.ietf.org/doc/html/rfc5321#section-4.5.5

### CODE REVIEW

**Comment by tgxworld** [comment]
Thank you for your contribution @evgeni. Is there a test you can add for this fix here?

**Comment by evgeni** [comment]
There are no existing tests for this endpoint in https://github.com/discourse/discourse/blob/main/spec/requests/email_controller_spec.rb, so I am not exactly sure how a test should be structured :(

**Comment by martin-brennan** [comment]
Hi @evgeni sorry for the delay in reviewing here. I am not sure what the benefit of doing this would be since everything within the discourse Email::Receiver flow assumes the `from` address exists, and it rejects emails where its missing. Why not just have this done at SMTP time?

https://github.com/discourse/discourse/blob/3ebd5100debff5981c576a4d8fd3d283759d11f2/lib/email/receiver.rb#L156-L156

As for the tests (a little concerning these don't exist yet...), you would actually need to add them in https://github.com/discourse/discourse/blob/3ebd5100debff5981c576a4d8fd3d283759d11f2/spec/requests/admin/email_controller_spec.rb . You should be able to take a look at the `handle_mail` test and follow along. Mainly you would need to do:

```
post "/admin/email/smtp_should_reject.json", params: { from: "someememail@test.com", to: "otheremail@test.com" }
```

And then you'd need to do the different combinations within each `it "x"` block (e.g. one with no from address, one without a user existing, one with staged users allowed etc)

**Comment by evgeni** [comment]
Hey Martin,

oh gosh, now I need to remember the context of this :cold_sweat: 

I think my reasoning was that with this change, the `handle_bounce` code will still run:
https://github.com/discourse/discourse/blob/3ebd5100debff5981c576a4d8fd3d283759d11f2/lib/email/receiver.rb#L155-L156
Which will allow admins to actually see those bounces in the interface, versus going hunting down logs somewhere on disk.
Plus, it eliminates the weird "internal API error" reject and might produce a useful one instead.

**Comment by jjaffeux** [comment]
> Hey Martin,
> 
> oh gosh, now I need to remember the context of this 😰
> 
> I think my reasoning was that with this change, the `handle_bounce` code will still run:
> 
> https://github.com/discourse/discourse/blob/3ebd5100debff5981c576a4d8fd3d283759d11f2/lib/email/receiver.rb#L155-L156
> 
> 
> Which will allow admins to actually see those bounces in the interface, versus going hunting down logs somewhere on disk.
> Plus, it eliminates the weird "internal API error" reject and might produce a useful one instead.

@martin-brennan just checking you have seen the answer here

**Comment by martin-brennan** [comment]
> Which will allow admins to actually see those bounces in the interface, versus going hunting down logs somewhere on disk.
Plus, it eliminates the weird "internal API error" reject and might produce a useful one instead.

Hey @evgeni , sorry this fell to the wayside over the Christmas period. I am happy with your reasoning, and yes this is fine. Just need to add a spec for this before we merge. Also the PR title/commit needs a `FIX:` prefix.

**Comment by nattsw** [comment]
Closing this due to inactivity. Please feel free to reopen when you have a spec and link it to this PR.

**Pull request closed without merging**
