### PR TITLE
DEV: flexify post actions

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by jjaffeux** [comment]
How do we feel about this ?

**Comment by jjaffeux** [comment]
> Seeing an alignment issue with the replies button, so I think `.post-controls` needs to be flex too?
> 
> Screen Shot 2020-05-29 at 4 50 32 PM

Yes I saw this after indeed, I would have to fix this too, but it's easy. Will update PR.

**Comment by jjaffeux** [comment]
This is how it should look:

Screenshot 2020-05-29 at 23 00 38

**Comment by jjaffeux** [comment]
will wait after beta, this is a little bit tricky

**Comment by SamSaffron** [comment]
Merging as this was approved by @awesomerobot

**Pull request merged**
