### PR TITLE
UX: Add link to Groups in admin dashboard.

### PR DESCRIPTION
**Pull request by nbianca**
The placement of the "Groups" link under "Users" is sometimes confusing.

### CODE REVIEW

**Comment by SamSaffron** [comment]
I know people struggle to find groups but I worry about adding a top level tab that takes you to an entirely different place

**Comment by tgxworld** [comment]
Hmm where was this feature discussed? We removed the groups links from the admin page intentionally.

**Comment by ZogStriP** [comment]
@eviltrout care to elaborate? ;)

**Comment by eviltrout** [comment]
So here is the problem: if `enable_group_directory` is disabled, we hide the link to Groups from the navigation dropdown. (A big gaming company that uses Discourse does this.)

At that point, there is no obvious way to edit groups. We did find a very hidden link if you go Admin > Users > Groups but that is super confusing.

I asked @nbianca to put the link back. We could compromise and only put the link back if `enable_group_directory` is disabled?

**Comment by nbianca** [comment]
I made the link show up only if `enable_group_dictionary` is disabled.

The other commit is to make the UI a little nicer. The admin will see the effect of him changing the site settings immediately. For example, immediately after the badges are disabled, the pill is hidden (a page refresh was required before).

**Comment by SamSaffron** [comment]
I think this is a fine compromise for now!

**Pull request merged**
