### PR TITLE
Move watching-first-post scss to from user to notification option

### PR DESCRIPTION
**Pull request by jomaxro**
Also remove extra classes from scss, made targeting watching-first-post different from all other notification states

### CODE REVIEW

**Comment by tgxworld** [comment]
Thanks @jomaxro

**Comment by jomaxro** [comment]
My pleasure @tgxworld.  This was bothering me when working on some CSS...

**Comment by jomaxro** [comment]
Ooh - @tgxworld it looks like the two file changes were separate commits...is there a way to avoid that in the future? Git isn't my specialty.

**Comment by tgxworld** [comment]
@jomaxro O I didn't notice that too. In the future, you can squash your commits :) 

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by jomaxro** [comment]
That looks to be command line based. I always just edit in the browser. Will lool into working on files locally going forward.

**Pull request merged**
