### PR TITLE
UX: Use a less technical term ("replace") for reseeding

### PR DESCRIPTION
**Pull request by gschlager**
image

image

image

### CODE REVIEW

**Comment by ZogStriP** [comment]
`Go ahead` feels weird... Looks like it's only being used here and in CSV uploads. Can we make it consistent with all other modals?

**Comment by gschlager** [comment]
Sure. I changed it.

image

**Comment by ZogStriP** [comment]
Another feedback. I tried it on an instance on a low-end VPS and it took quite a while to run (like 5-ish seconds). Should we show a loading spinner or at least warn the user it might take a little while?

**Comment by gschlager** [comment]
Good idea. I'll add that tomorrow.

**Pull request merged**
