### PR TITLE
FIX: Added two user badge triggers

### PR DESCRIPTION
**Pull request by sigginet**
Created two triggers that trigger events when a badge is granted or removed.

Trigger 1:
user_badge_granted
 Variable - badge_id
 Variable - user_id

Trigger 2:
user_badge_removed
 Variable - badge_id
 Variable - user_id

### CODE REVIEW

**Comment by sigginet** [comment]
Uhmm .. @discoursebot - I believe I did when I sent my last PR.. ?

**Comment by ZogStriP** [comment]
@sigginet don't mind @discoursebot, (s)he's having a *digital* cold ;)

**Comment by ZogStriP** [comment]
@sigginet Would you mind adding a test for these triggers so that we don't break them in the future?

**Comment by sigginet** [comment]
@ZogStriP Haha .. inject him with some digital anti-biotics! ;)

Working on the tests now.. I'll send an update when it's ready :)

**Comment by nlalonde** [comment]
@sigginet You put an `@` character in front of your username when you signed the cla form. First person to do that!

**Comment by sigginet** [comment]
@nlalonde .. haha .. guess I'm just so used to using the @ ;)

**Comment by sigginet** [comment]
Fixed the badge triggers (they would have broken all badge grants or deletes).

Added tests for the new triggers, but it seems like DiscourseEvent will force a trigger on you for some reason .. explained better in the commit message below.

Maybe I overlooked some option or wrote bad tests?

> NOTE: The DiscourseEvent trigger mechanism is VERY weird.
> If there are ANY triggers triggered in the chain, you can't only list the one you're looking for, you have to list all triggers in the order they will come.

> Example: line 98-100
> :user_created and :user_verified are triggers that are introduced in PR #3237 so if this PR is accepted but not PR #3237 then lines 98-99 need to be removed.

**Comment by ZogStriP** [comment]
Do you stil need this @sigginet? We prefer to includes triggers only when they're in used in a plugin.

**Comment by cmsunu28** [comment]
Hi! I have a plugin that I wrote to notify users with PMs when they get certain badges, and it works great with this notification system. Is there any way I can help get this PR running and merged? It seems like the build is failing due to:

`Failure/Error: DiscourseEvent.expects(:trigger).with(:user_verified, anything).once`

Any theories on why this may be happening? Would love to help out.

**Comment by cmsunu28** [comment]
It appears that tests do not fail when run locally, only in the travis build.

**Comment by cmsunu28** [comment]
@ZogStriP Any thoughts on why this fails in Travis? Works fine on local.

**Comment by eviltrout** [comment]
I'm happy to merge this, it looks good to me.

**Comment by eviltrout** [comment]
After pulling I got a local failure, so fixed the test.

**Comment by cmsunu28** [comment]
Thanks, @eviltrout!! Do you know how long it will take until this gets put into the tests-passed branch?

**Comment by eviltrout** [comment]
@cmsunu28 It should be in tests-passed now, actually it should have been as of 6 days ago.

**Comment by cmsunu28** [comment]
Thank you!

**Pull request merged**
