### PR TITLE
FIX: Local onebox on subfolder installs

### PR DESCRIPTION
**Pull request by xfalcox**
This should fix oneboxing local topics when using the subfolder install feature.

### CODE REVIEW

**Comment by ZogStriP** [comment]
No test?

**Comment by xfalcox** [comment]
Oops @ZogStriP =D

I'll create some later today!

**Comment by xfalcox** [comment]
Hey @ZogStriP  I tried to add some tests. They are mostly the old tests when mocking a subfolder install.

I'm kinda new to rspec if you can point me the error I would be glad to try and fix then.

**Comment by ZogStriP** [comment]
Looks fine, thanks :+1:

**Pull request merged**
