### PR TITLE
Update client.tr_TR.yml

### PR DESCRIPTION
**Pull request by muhyal**
It was replaced by the current Turkish words and grammatical errors have been fixed.

### CODE REVIEW

**Comment by muhyal** [comment]
Hi,

Current Turkish language pack looks very bad. And contains grammatical errors. I update constantly Turkish language pack. I do not use and do not edit some parts on Transifex. I am already using the Discourse on my Turkish websites. I expect you to give me permission in this regard.

Thanks.

**Comment by ZogStriP** [comment]
I'm sorry but we only accept translations updates via transifex. Otherwise, next time we pull the translations form transifex, they'll get overwritten.

**Comment by muhyal** [comment]
I understand no problem @ZogStriP . Then please give privileges on Transifex to edit this files. Thanks. My Transifex username is MuhYal. It deserves more polite language and grammar.

And please look my websites I translate my own XenForo software:
http://www.andronetwork.com (I did all XenForo translations for Turkish language.)
http://www.muhyal.com (WordPress)

http://www.destekforumlari.com (This Discourse Turkish support website.)
http://www.discourse-tr.com (This Discourse Turkish support website.)

I want to use it constantly Discourse on my websites.

Thanks.

Transifex SS:
Transifex SS

**Comment by ZogStriP** [comment]
You're now a reviewer for the Turkish language on transifex ;)

**Comment by muhyal** [comment]
Thanks @ZogStriP , kind regards :wink: .

**Pull request closed without merging**
