### PR TITLE
UX: keyboard shortcuts (j/k) should work with /categories

### PR DESCRIPTION
**Pull request by OsamaSayegh**
Meta: https://meta.discourse.org/t/keyboard-shortcut-k-j-doesnt-work-on-categories-page/15948?u=osama

### CODE REVIEW

**Comment by SamSaffron** [comment]
I worry that we are being a bit too fancy here and carrying too much code. 

Perhaps start with a very very simple PR with none of the tab hijacking that just allows j/k on the topic list. I am not sure we really need fancy j/k navigation in the categories section and can just get away with standard tab if users want to do that.

**Comment by OsamaSayegh** [comment]
Yeah, I was doubtful that a minor improvement like this is worth adding 100+ lines, but I didn't want to make that judgment. Will simplify this early next week.

**Comment by OsamaSayegh** [comment]
@SamSaffron I've simplified this to only support topics lists on /categories -- let me know what you think :comet:

**Comment by SamSaffron** [comment]
much better! merging in 👍

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Pull request merged**
