### PR TITLE
FIX: improve url validation regexp

### PR DESCRIPTION
**Pull request by fantasticfears**

### CODE REVIEW

**Comment by coding-horror** [comment]
I do not feel we should support this, as it is dangerous:

`http://userid:password@example.com:8080/`

also, I am unclear, why do we need to support arbitrary numeric IP addresses here?

**Comment by fantasticfears** [comment]
@coding-horror Sure, I can leave user information part aside.

The numeric IP addresses is still legitimate URL. Webhook is such an advanced feature. So admin should be able to point that to an internal service (IP address) if they insist. Either way, an actual parser should definitely help if we want to restrict them in various of situations.

**Comment by tgxworld** [comment]
@fantasticfears You'll have to open the PR against the `master` branch :)

**Comment by fantasticfears** [comment]
@tgxworld Github now supports changing target branch. Are you sure about changing the branch to master? I think you are asking another rebase here

**Comment by tgxworld** [comment]
@fantasticfears O is the url checker added as part of the webhook project?

**Comment by fantasticfears** [comment]
Yes

**Comment by tgxworld** [comment]
@eviltrout  What do you think about this change? We need a URL validator here and instead of maintaining a giant RegExp. I advised @fantasticfears  to pull in another library instead.  :)

**Comment by eviltrout** [comment]
@tgxworld is it necessary to have such complicated validation client side? I'm wondering if we can keep the basic validation then do the complicated validation server side? Otherwise it's an extra thousand lines of code to carry around

**Comment by fantasticfears** [comment]
Using Ruby `uri` module for validation now. It's more like a parser instead of validator. Anyway, the delivery status would be apparent if any error.

**Comment by tgxworld** [comment]
@fantasticfears  I don't see the validation in the changes?

**Comment by fantasticfears** [comment]
@tgxworld Because it's already there 😉  See https://github.com/discourse/discourse/blob/gsoc_webhooks/app/models/web_hook.rb#L10

**Comment by tgxworld** [comment]
:+1:

**Pull request merged**
