### PR TITLE
FEATURE: Add a trigger for plugins to include their own post processing jobs.

### PR DESCRIPTION
**Pull request by tgxworld**
cc/ @SamSaffron

### CODE REVIEW

**Comment by SamSaffron** [comment]
sure, but let's name it after_trigger_post_process

technically it should probably be named after_trigger_post_post_process... but that name is odd :)

**Comment by tgxworld** [comment]
Updated :)

**Comment by SamSaffron** [comment]
cool !

**Comment by riking** [comment]
@tgxworld You should add another one here:
https://github.com/discourse/discourse/blob/master/lib/cooked_post_processor.rb#L24

**Pull request merged**
