### PR TITLE
UX: Normalize sizing for inputs, buttons, dropdowns

### PR DESCRIPTION
**Pull request by pmusaraj**
This adds consistent sizing for text inputs, dropdowns and buttons across the app. This is important because these elements are often used together in forms, and having different calculated heights causes many layout issues. 

The key part of this PR is the following new mixin: 

```css
$vpad: 0.5em;
$hpad: 0.65em;

@mixin form-item-sizing {
  border: 1px solid transparent;
  font-size: var(--font-0);
  line-height: normal;
  box-sizing: border-box;
  padding: $vpad $hpad;
  .ios-device & {
    font-size: var(--font-size-ios-input);
    padding-top: $vpad * 0.8;
    padding-bottom: $vpad * 0.8;
  }
}
```

This is then used as the baseline style for text inputs, dropdowns and buttons. For better consistency, we want to avoid modifying any properties for these elements that affect height. 

Some explanations on the choices in this mixin: 

- the values I chose for vertical and horizontal padding are the closest I could get to the current sizing in core. I’m not married to them, my goal is to get to consistent sizing with as little visual change as possible.
- I first tried line-height: 1 but it doesn’t work for customized fonts, with some fonts, inputs get a different height when using number-based line heights (due to how each font is designed). line-height: normal works much better, I tested it with several of the fonts we include, and things seem to line up properly.
- To fix the inconsistency between icon-only buttons and other buttons, I added a zero-width character to the icon only buttons. This means that the button’s size is calculated as if it had text.
- the iOS overrides are necessary to avoid triggering Safari's zoom feature, which gets invoked automatically on inputs smaller than 16px

This PR also adds a new helper, `.inline-form` which is used in several places in the app (esp. admin screens) where we have form elements side by side. Here's a screenshot showing the changes in action (from the Input fields page of the styleguide): 

image

This PR also makes a change to the navigation bar: 

Before 
image

After
image

We previously had a slightly bigger font size for the "new topic" button. That causes alignment issues, and keeping it was tricky. So for now, we are switching to a standard button there.

### CODE REVIEW

**Comment by jjaffeux** [comment]
@pmusaraj seems like height test is failing on ember cli

**Comment by jjaffeux** [comment]
Fun times ahead :D

**Comment by jjaffeux** [comment]
> > @pmusaraj seems like height test is failing on ember cli
> 
> Yes, I am aware of it. It's only failing for Firefox 78 and so far haven't been able to repro in BrowserStack or locally.

Im fine with skipping this for now, although we were discussing this with @eviltrout the other day and every failures we fixed due to Firefox ESR were indeed very hard to repro/understand, but they were all legit and were pointing real issues, so I wouldn't reduce their importance.

**Comment by jjaffeux** [comment]
It's very hard to review this kind of PRs, I don't see anything wrong but hard to tell before it's merged. Im more interested in our capacity to keep this standard and improve it than being 100% correct from first shot though.

**Review by jjaffeux — APPROVED** [review]

**Comment by pmusaraj** [comment]
Agree @jjaffeux. This is a slightly unusual test, it indicates a "nice to have" more than a "oh no, something broke". Plus this can only catch a global regression between element sizing, whereas the vast majority of problems here can be local (i.e. a specific input/button/dropdown that has style overrides). 

But, note taken, we should avoid skipping tests in Firefox as much as possible.

**Review by CvX — APPROVED** [review]

**Pull request merged**
