### PR TITLE
UX: show user name and title on about page

### PR DESCRIPTION
**Pull request by techAPJ**
with names enabled:

screen shot 2015-02-27 at 00 55 11

with names disabled:

screen shot 2015-02-27 at 00 54 37

### CODE REVIEW

**Comment by downeym** [comment]
Love this! Thank you!

**Comment by SamSaffron** [comment]
this is a big packet of styling changes for something so small. 

also I do not think we need any conditional logic here, just show full name there regardless and the "title" / "username" / "name" should be styled the same way it is on the posts, black for everything is confusing.

**Comment by techAPJ** [comment]
Updated the "username" / "name" / "title" style to match with posts and removed conditional logic. Screenshot:

screen shot 2015-03-02 at 15 18 05

**Comment by SamSaffron** [comment]
cheers

**Pull request merged**
