### PR TITLE
DEV: Remove legacy tag and category routes

### PR DESCRIPTION
**Pull request by udan11**

### CODE REVIEW

**Comment by eviltrout** [comment]
Hey @udan11 curious if this is still a draft as it's quite old now, and looks like it's out of date?

**Comment by udan11** [comment]
I believe this is ready for review now.

**Comment by danielwaterworth** [comment]
I will look at this today.

**Comment by SamSaffron** [comment]
We have a conflict @danielwaterworth  have you had a chance to have a quick look?

**Comment by danielwaterworth** [comment]
@SamSaffron, yes, we talked via other means.

**Comment by SamSaffron** [comment]
@udan11 are you comfortable with this change, should we go ahead and merge? I am approving this on the ground that I support cleaning up the routes, it is a big change though!

**Review by SamSaffron — APPROVED** [review]

**Comment by udan11** [comment]
@SamSaffron, I added some code in our resolver to replace references to old names and display a deprecation notice. I think we are good. I want @danielwaterworth to have another look at this. 

Unfortunately, some broken themes or theme components are unavoidable. :(

**Comment by SamSaffron** [comment]
Go ahead and merge today, we can deal with the rest of the theme fallout this week.

**Pull request merged**
