### PR TITLE
DEV: group tests related to mentions

### PR DESCRIPTION
**Pull request by AndrewPrigorshnev**
This PR only rearranges tests (groups them into the "with mentions" context).

### CODE REVIEW

**Comment by CvX** [comment]
Can you merge in `main` (to hopefully resolve spec failures 😃)

**Review by CvX — APPROVED** [review]

**Comment by AndrewPrigorshnev** [comment]
@CvX thank you for review!

**Comment by Triple747** [comment]
****

**Comment by Triple747** [comment]
**,666
**@@Triple747 to 💚🧙🧜🧙🧜🧛🏊********

**Comment by Triple747** [comment]
,_

_

**Pull request merged**
