### PR TITLE
Add support for ruby 2.5

### PR DESCRIPTION
**Pull request by jsuchal**
Removed bom|utf-8 since it is not supported in ruby 2.5 anymore.

### CODE REVIEW

**Comment by SamSaffron** [comment]
I saw this on local @techAPJ we need a test to cover why the bom stuff was added in the first place

**Comment by jsuchal** [comment]
Yes, I was kind of surprised that any tests didn't fail after I removed the `bom` part.

**Comment by techAPJ** [comment]
Added a test for BOM via https://github.com/discourse/discourse/commit/6c1ebbb95c184d74b40c7f0c4e1a3c9919b1b970.

The BOM handling was added after it was reported on meta: https://meta.discourse.org/t/ignore-bom-on-csv-when-sending-bulk-invitations/62332

Closing / Re-opening this PR to trigger Travis check. It should be failing now.

**Comment by jsuchal** [comment]
OMG, i somehow messed up the rebase. However I was able to fix the utf|bom thingy.

**Comment by gschlager** [comment]
Yeah, there is something wrong with this PR. I'm closing this for now.
Could you please create a new PR that contains only your changes?

**Comment by jsuchal** [comment]
Here https://github.com/discourse/discourse/pull/5478

**Pull request closed without merging**
