### PR TITLE
FEATURE: Adds support for local js files in themes

### PR DESCRIPTION
**Pull request by SamSaffron**
Due to default CSP web workers instantiated from CDN based assets are still
treated as "same-origin" meaning that we had no way of safely instansiating
a web worker from a theme.

This limits the theme system and adds the arbitrary restriction that WASM
based components can not be safely used.

To resolve this limitation a new type of asset can be registered about.json

```
{
  "name": "Header Icons",
  "local_js_assets" : {
    "worker" : "assets/worker.js"
  }
}
```

This can then be referenced in JS via:

`settings.local_js_urls.worker`

`local_js_assets` are unconditionally served from the site directly and
bypass the entire CDN, using the pre-existing JavascriptCache

Previous to this change this code was completely dormant on sites which
used s3 based uploads, this reuses the very well tested and cached asset
system on s3 based sites.

Note, when creating local_js_assets it is highly recommended to keep the
assets lean and keep all the heavy working in CDN based assets. For example
wasm files can still live on the CDN but the lean worker that loads it can
live on local.

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
This is going to be very useful!

My only slight concern is about the name: `local_js`. This makes a lot of sense for workers, but there are plenty of situations where you might want to supply an extra JS file, but **still use the CDN** to load it. (e.g. the discourse-math plugin does this)

How about calling it `raw_js`, and then making both CDN and local URLs available. So these would all work:

```
settings.raw_js.worker.url
settings.raw_js.worker.local_url
settings.raw_js.mathjax.url
settings.raw_js.mathjax.local_url
```

I see you've added import logic. But I think we also need to make sure that these new fields are exported correctly. IIRC you'll need to add [a FileMatcher](https://github.com/discourse/discourse/blob/720e1ca9e79a00acf72e77a42de3f421ff661081/app/models/theme_field.rb#L496-L496). Also, if we're going for this `about.json`-based strategy, then we'll need [some special-case logic like this](https://github.com/discourse/discourse/blob/main/lib/theme_store/zip_exporter.rb#L55-L60) in the exporter.

However, I think my preference would be to have a dedicated top-level `/raw-javascripts` directory, rather than having to specify individual paths in `about.json`. That would be much easier to use and document, IMO. 🤔

**Comment by SamSaffron** [comment]
Those changes sound great, feel free to push them if you have time to fiddle

**Comment by davidtaylorhq** [comment]
Updated based on those suggestions

**Review by davidtaylorhq — APPROVED** [review]

**Comment by SamSaffron** [comment]
looks good like great progress, but I am not sure we are done.

It makes sense to also bundle `wasm` in components, at the moment this is a rough ride.

raw-javascripts will crash the discourse-theme uploads when you add the wasm to raw-javascripts (eg: https://github.com/discourse/discourse-svgbob/blob/main/assets/svgbob_worker.js#L9) 

You can not include in assets cause it is not in default theme_authorized_extensions.

I think there are a few safeguards we can add here: 

1. Easy... add wasm to theme authorized extensions default, cause it seems reasonable
2. More tricky ... raw-javascripts should not even bother trying to import files that do not end in `.js` it is for JS only. This also means we go with the simpler `settings.raw_js.worker.local_url`
3. Super tricky ... place the wasm in raw-javascripts now and the theme no longer imports due to a null byte

Passing the wasm url to the web worker is ... an adventure ... but workable in a setup message.

Thoughts? ... maybe do a matching PR to the svgbob theme that gets it working with fully embedded assets so we try this out end to end?  

A bit unsure about the name `raw-javascripts` it is so easy to confuse with `raw_javascripts` ... Maybe we carry the assets pattern to avoid confusion and maintain consistency ... I totally get the appeal of automatic, but explicit has some advantages ... not sure.

**Comment by SamSaffron** [comment]
Been thinking about this @davidtaylorhq ...

Perhaps we keep raw js in 

`/javascripts/raw`  

This is technically breaking but in reality I doubt it will at all. Then on client side. 

Then we only scan `*.js` for now, at least until another use case pops up.

So for 

```
javascripts/raw/amazing.js
javascripts/raw/a/b/test.js
```

we would have 

```
settings.javascripts.raw.amazing.url
settings.javascripts.raw.amazing.local_url
settings.javascripts.raw["a/b/test"].url
settings.javascripts.raw["a/b/test"].local_url
```

At lease everything is tidy, we minimize dash use and make stuff reasonably easy to remember.

Feels more coherent ... thoughts? 

Long term if we need to support other js extensions for some crazy reason we can make the non breaking change of, but we can punt on this till needed.  

`settings.javascripts.raw["test.jsx"].url`

**Comment by OsamaSayegh** [comment]
```
javascripts/raw/amazing.js
javascripts/raw/a/b/test.js
```

In my head, "raw javascript" is kind of reserved to the raw handlebars/views system that we have and I feel like having a `raw` subdirectory that's different to the raw views system might cause confusion. How do you feel about naming it `static`?

**Comment by SamSaffron** [comment]
Static is a bit of a tricky term, we don’t use it anywhere else for this, plus the js is static anyway everywhere (it is not dynamically changing like a erb file)

I hear you on the raw problem though 

One alternative may be just to put this in a public folder like we do for themes, it would only support part of the features that public does in themes, but at least there is better parity between systems 

such a tricky problem, naming is so hard

**Comment by SamSaffron** [comment]
>  I think we should supply an absolute path (no protocol/domain) to the client

Yes but.... 

I want us to be efficient by default ... so the default place you get is CDN for S3, just like you do for all other assets. 

Then you can reach elsewhere to grab the local URL. 

If we give people a local URL by default they will forget to wrap it with a CDN.  All the other assets are already safe, why is this one different? 

So full proposal is: 

```
assets: {
   image: "/assets/image.png",
   jsfile: "/assets/jsfile.js"
}
```

```
settings.theme_uploads.jsfile  // S3 CDN url
settings.theme_uploads_local.jsfile // local URL
settings.theme_uploads_local.image // undefined
```

A bit verbose but 

1. 100% backwards compatible 
2. Coherent with current design names are very unlikely to clash ... a setting called `theme_uploads_local` is very unlikely to exist.

**Comment by xfalcox** [comment]
@SamSaffron will this new JS be transpiled or get a cache-buster ?

**Comment by SamSaffron** [comment]
> @SamSaffron will this new file JS be transpiled or get a cache-buster ?

No and Yes :) 

JavascriptCache comes with an automatic cache buster based on content which is rock solid and very well tested. No plans to transpile though cause it would break the semantics of what people expect for uploads.

**Comment by OsamaSayegh** [comment]
> 2\. Coherent with current design names are very unlikely to clash ... a setting called `theme_uploads_local` is very unlikely to exist.

I'm not against this since `theme_uploads` has existed for a while, but I wish we didn't have these special/magic objects that could clash with theme-provided settings. In my ideal world, we'd have a global object called something like `thisTheme` and from it you can access the theme settings, uploads, local uploads and whatever fancy things we may add in future.

Proposal sounds good to me :+1:

**Comment by SamSaffron** [comment]
>  In my ideal world, we'd have a global object called something like thisTheme and from it you can access the theme settings, uploads, local uploads and whatever fancy things we may add in the future.

Agree 100% but I worry it will make this change too big. I fully support a better structured object.

themeData.settings
themeData.assets
themeData.localAssets
themeData.userStore.set("banana", 1)
themeData.userStore.get("banana") 

Perhaps we start some sort of plan to deprecate `settings` further down the line, certainly way too big for this PR.

**Comment by OsamaSayegh** [comment]
Yes, totally, I certainly didn't mean to suggest it should be done in this PR, but like you said it'd be nice to do it at some point in the future.

**Review by xfalcox — APPROVED** [review]

**Comment by SamSaffron** [comment]
Awesome ... closing this in favor of this new implementation then :) 

https://github.com/discourse/discourse/pull/16374

@OsamaSayegh / @xfalcox / @davidtaylorhq how is it looking?

**Pull request closed without merging**
