### PR TITLE
DEV: removes discourse-chat move commit from blame

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by CvX** [comment]
All the chat files will show blank git blame for now? Do we need that commit to be ignored?

**Comment by jjaffeux** [comment]
oh yes you are right we will just have no history anyways :(

**Comment by jjaffeux** [comment]
I guess it's over... we should have done a merge commit

**Comment by romanrizzi** [comment]
I don't think there was a way of preserving history anyways. The chat plugin is no longer a git repo.

**Comment by jjaffeux** [comment]
There might have been... but anyways it's done

**Pull request closed without merging**
