### PR TITLE
Add same site cookie 'None' option to make cross domain systems possible

### PR DESCRIPTION
**Pull request by dave0688**
Added sameSite=None option to be able to send cookies to other domains.

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Looks good to me. @dave0688, please can you sign the CLA using the link above, then we'll get this merged :)

**Comment by dave0688** [comment]
Thanks for the feedback. I signed it already like a week ago, so please feel free to merge :)

**Comment by davidtaylorhq** [comment]
I guess you used the link in [CONTRIBUTING.MD](https://github.com/discourse/discourse/blob/master/CONTRIBUTING.md) - I just realised that it is out of date, since we moved to a new system with GitHub integration. I'll get that link updated now - sorry for the confusion.

So that we have a digital paper-trail, please can you sign the new one against your GitHub account (content is the same): https://cla-assistant.io/discourse/discourse?pullRequest=9374

**Comment by dave0688** [comment]
Ok, now I signed the new version :)

**Pull request merged**
