### PR TITLE
FIX: Blank slug when generate auto slug

### PR DESCRIPTION
**Pull request by dujiajun**

### CODE REVIEW

**Comment by martin-brennan** [comment]
Can you provide some examples of what titles didn't work with the old way? We would need some tests for this as well. This is originally doing the same thing as automatic slug generation for categories:

https://github.com/discourse/discourse/blob/main/app/models/category.rb#L380-L382

**Comment by dujiajun** [comment]
I tried different category names such as 'test' and '测试'. All of them return ''. 
image

**Comment by dujiajun** [comment]
Category slug will always be '' if calls `Slug.for` without `method`. 

Maybe this is the reason that I cannot use #<category name> in the post, if i didn't set the category slug manually.

**Comment by dujiajun** [comment]
Oh, I see. The reason is that my `SiteSetting.slug_generation_method` is `none`. When I change to `encoded`,  everything is ok.

This is not a bug. Sorry to bother.

**Comment by martin-brennan** [comment]
No problem @dujiajun , thanks for investigating further, it's no bother. Closing this now :)

**Pull request closed without merging**
