### PR TITLE
DEV: Prevent Ember from extending string prototype

### PR DESCRIPTION
**Pull request by janzenisaac**
## Ember Upgrade

Context: https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions

### CODE REVIEW

**Comment by CvX** [comment]
I wouldn't merge it in just yet. See /t/66562/7

**Comment by CvX** [comment]
Also, looks like `.htmlSafe()` needs to be replaced too 🙂

**Comment by janzenisaac** [comment]
> Also, looks like `.htmlSafe()` needs to be replaced too 🙂

I am disappointed, I didn't see that in https://api.emberjs.com/ember/3.15/classes/String.

**Comment by pmusaraj** [comment]
Yeah, sadly, we can't disallow this entirely yet. Closing.

**Pull request closed without merging**
