### PR TITLE
FIX: manually adds frowning_face_with_open_mouth

### PR DESCRIPTION
**Pull request by jjaffeux**
This will require a better fix but will prevent broken image for now.

### CODE REVIEW

**Comment by CvX** [comment]
Are the spec failures relevant?

**Comment by eviltrout** [comment]
Looks like it to me @CvX - I think they have hardcoded versions

**Comment by jjaffeux** [comment]
> Looks like it to me @CvX - I think they have hardcoded versions

Yes that's the reason, it shouldn't be, but it is :D will look at fixing it, one is in a plugin though apparently.

**Comment by ZogStriP** [comment]
@jjaffeux any news about this?

**Comment by jjaffeux** [comment]
@ZogStriP should be good

**Review by ZogStriP — APPROVED** [review]

**Pull request merged**
