### PR TITLE
UX: fix group header font color

### PR DESCRIPTION
**Pull request by linc01n**
Change according to group header background color

### CODE REVIEW

**Comment by linc01n** [comment]
More info about this fix:
https://meta.discourse.org/t/group-titles-on-group-pages-are-white-on-white/46425/

**Comment by coding-horror** [comment]
Hmm where is the discourse CLA bot here?

**Comment by tgxworld** [comment]
@coding-horror Ok CLA bot is fixed :)

**Comment by tgxworld** [comment]
Looks good to me. Thanks @linc01n

**Pull request merged**
