### PR TITLE
FIX: start sidekiq process for all queues in non-dev

### PR DESCRIPTION
**Pull request by rossdakin**
Related to discourse/discourse#4735

### CODE REVIEW

**Comment by SamSaffron** [comment]
is there a reason this is required? Our production docker image takes care of it.

**Comment by rossdakin** [comment]
Maybe I'm doing it wrong.

We're using a [Bitnami release](https://github.com/bitnami/bitnami-docker-discourse) that was only processing the default queue. This change fixed it, though I'm not familiar enough with container architecture to know if it's the right thing to do.

**Comment by coding-horror** [comment]
yes bitnami is an unsupported install, so while I appreciate the effort, we have a policy of only supporting our official docker install, to keep our open source support / human power requirements under control. Definitely document it on meta.discourse.org for others though.

**Comment by rossdakin** [comment]
Got it, thanks @coding-horror!

Out of curiosity, is there any down side to this particular code change?

**Comment by SamSaffron** [comment]
Probably no downside except that we need to test it and confirm it has no
weird side effects

**Pull request closed without merging**
