### PR TITLE
Allow periods in the external_id value used in the /users/by-external route.

### PR DESCRIPTION
**Pull request by rcfox**
I'm not at all a Rubyist, so I'm not sure if there was a better way to do this. If nothing else, I hope it can at least inspire a correct solution.

### CODE REVIEW

**Comment by rcfox** [comment]
CLA signed.

**Comment by SamSaffron** [comment]
I want to merge this in but it needs a rebase

**Comment by ZogStriP** [comment]
ping @rcfox

**Comment by rcfox** [comment]
Hey, sorry about that. The merge seemed pretty simple, but I'm not really able to test it at the moment.

**Comment by coding-horror** [comment]
we should pull this in, or synthesize the fix ourselves, unless someone has a compelling reason not to

**Comment by SamSaffron** [comment]
Ill pull this in for now

**Pull request merged**
