### PR TITLE
fix error "extension "hstore" already exists"

### PR DESCRIPTION
**Pull request by bill2004158**
Error executing 'postInstallation': ERROR:  extension "hstore" already exists

I just saw that error from console, hope this can fix that error.

### CODE REVIEW

**Comment by SamSaffron** [comment]
This is probably fine, but unfortunately we can not check this PR till we have a CLA signed 😢

**Comment by tgxworld** [comment]
ping @bill2004158

**Comment by bill2004158** [comment]
already signed?

**Comment by tgxworld** [comment]
Thanks! @bill2004158

**Pull request merged**
