### PR TITLE
Added Lets Encrypt to bonus stuff

### PR DESCRIPTION
**Pull request by djtye**
Don't want to confuse users do we now ;)

### CODE REVIEW

**Comment by coding-horror** [comment]
I don't really like it at the top, it should be with the other HTTPS stuff. I'll make the change the way I want it to be..

**Comment by djtye** [comment]
Okay :)

**Comment by coding-horror** [comment]
It's a good suggestion and I just added it, but I am picky about stuff ;)

**Comment by djtye** [comment]
Well you are the Lead Dev aha, I don't blame you :P

**Pull request closed without merging**
