### PR TITLE
Add more 'use the domain' emails

### PR DESCRIPTION
**Pull request by riking**
As per https://meta.discourse.org/t/change-invited-people-username-name-by-default/38452

### CODE REVIEW

**Comment by coding-horror** [comment]
Seems good to me!

**Comment by gschlager** [comment]
A few more suggestions: `hello`, `mail`, `office` and `contact`

**Comment by coding-horror** [comment]
All sound good to me!

**Comment by coding-horror** [comment]
OK! I went ahead and put all those in plus one of my own at

https://github.com/discourse/discourse/commit/0337964759370ae5a517f7aa5767cf08c7779d9b

**Pull request closed without merging**
