### PR TITLE
Permit in topic search when full name is null

### PR DESCRIPTION
**Pull request by Mittineague**
I wanted to write an RSpec test for this, but fear problems I'm having doing so could stall this fix for an indefinite amount of time.

### CODE REVIEW

**Comment by gschlager** [comment]
Am I missing something? Why use `quote_nullable(u.name)` instead of `COALESCE(u.name, '')`?

**Comment by ZogStriP** [comment]
I agree with @gschlager, `quote_nullable(NULL)` returns `NULL`.

**Comment by Mittineague** [comment]
I don't know if I should / need to squash the commits. 

It looks like the change took effect, but this is my first ever PR so I don't know.

**Comment by Mittineague** [comment]
Should I / need to squash the change commit. 

This is my first ever PR so I don't know

**Comment by ZogStriP** [comment]
> I don't know if I should / need to squash the commits.

We used to ask for squashing but now GitHub allows us to do it automatically when we merge ;)

> It looks like the change took effect, but this is my first ever PR so I don't know.

Awesome 👍

**Pull request merged**
