### PR TITLE
Allow localhost as an embeddable host

### PR DESCRIPTION
**Pull request by acshi**
Hostnames containing localhost do not currently pass embeddable host validations. This prevents the user from embedding comments into a page hosted on localhost.

This fix causes these hostnames to pass validation.

### CODE REVIEW

**Comment by eviltrout** [comment]
This should also have a spec to ensure localhost works.

**Comment by acshi** [comment]
How does that simple spec look? I notice that the existing spec is not very thorough.

Also, is there any reason the regex are set to accept paths when those are already being stripped from the host before validation?

**Comment by acshi** [comment]
@eviltrout Any thoughts on this or need for further changes?

**Comment by eviltrout** [comment]
No, thank you very much!

**Pull request merged**
