### PR TITLE
DEV: use tag description for single tag show

### PR DESCRIPTION
**Pull request by hawm**
It should help search engines know the tags pages better.

### CODE REVIEW

**Comment by tgxworld** [comment]
Thank you for the contribution. Will you be able to add a test for this change here?

**Comment by hawm** [comment]
Yeah, but I thought it wasn't a breaking change, and existing testing should handle it enough.

**Comment by tgxworld** [comment]
Not really a breaking change but we're adding new functionality which we'll like a test to prevent regression for.

**Comment by hawm** [comment]
Sure. But what test should it be here? This PR isn't to add some kind of new functionality but a trivial improvement of existing functionality. That's what I mean the already existing tests should be able to handle it.

**Comment by tgxworld** [comment]
> But what test should it be here? This PR isn't to add some kind of new functionality but a trivial improvement of existing functionality.

In some way, this is adding new functionality because with this commit, we will use the tag's description for the description meta instead of the generic translation string when a single tag is requested. I don't think existing tests will cover this case yet.

**Pull request closed without merging**
