### PR TITLE
FEATURE: add branch option to remote theme import

### PR DESCRIPTION
**Pull request by penguinstampede**
This might be a little too simple, but for testing/staging purposes of a new theme I'd like to have the ability to choose a remote theme's git branch when importing.

I also haven't done much in rails in well over a year so please let me know where I'm doin' it wrong 😨

### CODE REVIEW

**Comment by SamSaffron** [comment]
@penguinstampede  heads up, I just started merging 2.2 stuff. I am going to ask @vinothkannans  to help finish off this PR and merge it in, we have another customer that really wants this feature 👍

**Comment by vinothkannans** [comment]
@SamSaffron I think it's now mergable. The dangerbot error is not specific to this PR.

**Comment by jjaffeux** [comment]
@vinothkannans no theres a spacing missing in customize.scss

```
.modal-body .inputs .branch{
  margin-top: 10px;
}
```

should be

```
.modal-body .inputs .branch {
  margin-top: 10px;
}
```

**Comment by vinothkannans** [comment]
@jjaffeux @SamSaffron it's okay now.

**Comment by SamSaffron** [comment]
This is very very close, one last change we need is to stop assuming default branch is `master`, default value here should be `nil` and then it should be excluded from the git commands.

Git can have custom default branches, it could be called `trunk` or something else. I don't want to shoehorn us into needing a branch called master in every git repo.

**Comment by vinothkannans** [comment]
@SamSaffron it's done.

**Comment by SamSaffron** [comment]
Merging this, but maybe we should properly shows in the UI that branch optional?

**Comment by SamSaffron** [comment]
Thanks @penguinstampede  this is all merged now!

**Comment by vinothkannans** [comment]
@SamSaffron yes, improved the help text in https://github.com/discourse/discourse/commit/ac034a6b2ca7d2bed9e3ec7f4115298a18fe456f.

**Pull request merged**
