### PR TITLE
FIX: Add user id in the admin user routes

### PR DESCRIPTION
**Pull request by fantasticfears**
https://meta.discourse.org/t/usernames-in-admin-urls-cause-routing-problems/31825

### CODE REVIEW

**Comment by ZogStriP** [comment]
This needs a rebase ;)

**Comment by fantasticfears** [comment]
`master` branch seems fail when click to users summary. I'll do rebase later to see what's happening

**Comment by fantasticfears** [comment]
Rebased! @ZogStriP

**Comment by ZogStriP** [comment]
Sorry @fantasticfears, looks like it needs another rebase :(

**Comment by fantasticfears** [comment]
Rebased

**Comment by ZogStriP** [comment]
Cool, I'll wait for the build and then I'll merge it ;)

**Comment by ZogStriP** [comment]
Let's try it ;)

**Pull request merged**
