### PR TITLE
DEV: Introduce a `@debounce(delay)` decorator

### PR DESCRIPTION
**Pull request by CvX**
An example from tests:

```js
class TestStub {
  counter = 0;

  @debounce(50)
  increment() {
    this.counter++;
  }
}

const stub = new TestStub();

stub.increment();
stub.increment();
stub.increment();
await settled();

assert.strictEqual(stub.counter, 1);
```

### CODE REVIEW

**Review by davidtaylorhq — APPROVED** [review]
Nice!

**Review by davidtaylorhq — APPROVED** [review]

**Comment by jjaffeux** [comment]
awesome 🎉

**Comment by jjaffeux** [comment]
@CvX @davidtaylorhq I was thinking of this and I think one thing is missing. We have no way to cancel the debounce created currently right?

Maybe we should add some API for this, autogenerate from the name of the function: `this.cancelDebounce("increment")`
When using @debounce, it would automatically generate something like `this.__generatedDebounce_increment = ...` which would allow this API to cancel it.

**Comment by CvX** [comment]
Yeah, I thought about it, but for now in all the cases I was fixing (https://github.com/discourse/discourse/pull/18673) none of "debounce whole function" were using `cancel`. But if there is a need, I could see us adding that.

**Pull request merged**
