### PR TITLE
DEV: supports actionClick for small actions

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by jjaffeux** [comment]
@CvX thoughts on this pattern?

Mostly it would allow you to do things like:

```javascript
api.addPostTransformCallback((transformed) => {
  if (transformed.actionCode === "foo") {
    transformed.actionClickAction = () => {
      alert("foo");
    };
  }
});
```

**Comment by CvX** [comment]
I can't say I like the repetition in `actionClickAction` name but the pattern itself looks good!

**Comment by jjaffeux** [comment]
> I can't say I like the repetition in `actionClickAction` name but the pattern itself looks good!

Yes I was mixed too... I tried to follow existing naming scheme. I will just go with `actionClick`

**Comment by jjaffeux** [comment]
@CvX ok I renamed and added a test

**Comment by CvX** [comment]
Just a small nit: isn't `clickAction` a better (grammatically correct) name? 😃 Or does that conflict with some existing prop?

**Comment by jjaffeux** [comment]
> Just a small nit: isn't `clickAction` a better (grammatically correct) name? 😃 Or does that conflict with some existing prop?

Yes everything follow the patter: actionCodeWho, actionCodePath, actionCode...

**Review by CvX — APPROVED** [review]

**Comment by jjaffeux** [comment]
I think I will actually remove this @CvX this is annoying me because ultimately it creates a case of nested interactive which is bad for accessibility, I will need to drastically improve small action API instead of this quick win.

**Pull request merged**
