### PR TITLE
Return user_fields and custom_fields on directory_items api call.

### PR DESCRIPTION
**Pull request by kstaikov**
The goal here was to address the request to have custom fields in the user directory: https://meta.discourse.org/t/can-we-display-custom-fields-in-user-directory-list/35506.  

Added user_fields and custom_fields to the user_name_serializer.
This results in the directory_items api call returning the fields,
which allows us to easily include custom fields in the user directory
by lightly customizing some html if we anyone so desires.

### CODE REVIEW

**Comment by kstaikov** [comment]
I could also just make a new serializer and inherits from this one and is called something like DirectoryUserInfoSerializer, whichever is preferred

**Comment by tgxworld** [comment]
Hi thank you for your contribution. However, it doesn't look like we received a valid use case for adding the following fields. Sorry!

**Comment by kstaikov** [comment]
So then if I or anyone else wants to include custom fields in the user directory, how else are we supposed to do it without having a front end plugin that calls the api for each user - which would result in as many extra api calls as there are users?

**Comment by tgxworld** [comment]
Plugins can always add a new serializer and a new API endpoint

**Pull request closed without merging**
