### PR TITLE
FIX: vimeo iframe url when data-original-href is missing

### PR DESCRIPTION
**Pull request by ghassanmas**
This commit make it possible to create vimeo orignal url when
  data-original-href is missing.

  For more info check:
  https://meta.discourse.org/t/vimeo-embed-urls-parsed-incorrectly-in-email/231042

### CODE REVIEW

**Comment by SamSaffron** [comment]
I like this but I feel like we need some tests to ensure this does not regress. also a bit fragile cause `?xyz=1&h=...`

**Comment by ghassanmas** [comment]
I agree, the thing is we need to convert the iframe src to the orignal video uri. 
- We can use same API `https://vimeo.com/api/oembed.json?url=` checking this I found that the api will return the vido link when setting the `url` params to the iframe url. i.e. `https://vimeo.com/api/oembed.json?url=https://vimeo.com/api/oembed.json?url=https://player.vimeo.com/video/508864124?h=fcbbcc92fa`
- Second approach might be handy where we just replace the `h` part with a slash and other query params are shifted, if exists.

**Comment by nachocab** [comment]
> I like this but I feel like we need some tests to ensure this does not regress. also a bit fragile cause `?xyz=1&h=...`

What type of tests are needed to ensure this?

**Comment by jjaffeux** [comment]
@nachocab I fixed conflicts and added a spec, please let me know if it seems correct to you if you have the time, thanks!

**Comment by nachocab** [comment]
@jjaffeux Thanks! Looks good 👍

**Review by jjaffeux — APPROVED** [review]

**Pull request merged**
