### PR TITLE
FIX: prevents i18n helper to return a SafeString

### PR DESCRIPTION
**Pull request by jjaffeux**
For convenience the i18n helper has been made returning a SafeString, but when used with other helpers (eg: replace-emoji), a String is expected and will cause unexpected behaviors.

This is the root cause of the initial bug fixed in https://github.com/discourse/discourse/commit/d2bb127e2c8c4a4df30024883ee36472fc86b688

This commit is kept as it's a better security in case of unexpected behavior.

### CODE REVIEW

**Comment by ZogStriP** [comment]
Not sure I like that change as it will introduce another thing to think about when using translations... Is there another way we could fix the issue?

**Comment by jjaffeux** [comment]
> Not sure I like that change as it will introduce another thing to think about when using translations... Is there another way we could fix the issue?

There's no other thing to think. We were already doing `{{{i18n "foo"}}}` and now it's `{{html-safe (i18n "foo")}}` it's the exact translation of `{{{`. 

The alternative is to make every helper work with text or SafeString which basically means to do things like: `text.string || text` I'm not sure we want to change all the helpers code.

**Comment by jjaffeux** [comment]
Another alternative could be to have a {{safe-i18n}} helper

**Comment by ZogStriP** [comment]
> There's no other thing to think. We were already doing `{{{i18n "foo"}}}` and now it's `{{html-safe (i18n "foo")}}` it's the exact translation of `{{{`.

Oh, I think I misunderstood. I thought we would have to change all the `{{i18n ...}}`. Now if the `{{{` syntax is being deprecated, then `{{safe-html (i18n ...)}}` is fine 👍

**Pull request merged**
