### PR TITLE
FEATURE: better email reply parsing

### PR DESCRIPTION
**Pull request by techAPJ**
Meta topic for discussion: https://meta.discourse.org/t/better-email-reply-parsing-email/36495

### CODE REVIEW

**Comment by techAPJ** [comment]
I will merge this PR after 24 hours if nobody objects.

**Comment by techAPJ** [comment]
Build failure is unrelated.

```
PrettyText Cooking off topic quoting can correctly populate topic title
```

**Comment by ZogStriP** [comment]
:+1:

**Comment by techAPJ** [comment]
:balloon: :email: :balloon:

**Pull request merged**
