### PR TITLE
Create group request membership for user

### PR DESCRIPTION
**Pull request by tgxworld**
https://meta.discourse.org/t/new-members-cant-request-to-join-a-group/63626/11?u=tgxworld

### CODE REVIEW

**Comment by coding-horror** [comment]
This is rate limited?

**Comment by coding-horror** [comment]
the group name should be in the PM title, IMO

**Comment by tgxworld** [comment]
> This is rate limited?

Yup this is rate limited. 

> the group name should be in the PM title, IMO

OK I can add that in

**Comment by tgxworld** [comment]
Merged in https://github.com/discourse/discourse/commit/a5d3abc9b6888c382e0094ba03074aff8a450fec

**Pull request closed without merging**
