### PR TITLE
Do not load javascripts for disabled plugins

### PR DESCRIPTION
**Pull request by davidtaylorhq**

### CODE REVIEW

**Comment by SamSaffron** [comment]
You got to lint that file 😸

**Comment by davidtaylorhq** [comment]
Doh! 🙈

Will do

**Comment by SamSaffron** [comment]
@eviltrout I am leaving this to you!

**Comment by coding-horror** [comment]
Perhaps @ZogStriP can review this? Nice one

**Comment by ZogStriP** [comment]
Looks good to me

**Pull request merged**
