### PR TITLE
FIX: vBulletin bulk importer: emails and stats

### PR DESCRIPTION
**Pull request by quangbuule**
This includes like count stats for the post_thanks hack.

### CODE REVIEW

**Comment by quangbuule** [comment]
I signed the CLA already, please take a look when you guys have a tick.

**Comment by ZogStriP** [comment]
This is awesome! Thanks for this! 😍

**Comment by quangbuule** [comment]
Haha, that's really quick review @ZogStriP, I've never had that at work. 😛

**Comment by techAPJ** [comment]
@quangbuule: @ZogStriP is the best! :wink: 

And, thanks a lot for this PR! :+1: I was about to start working on this myself. :)

**Pull request merged**
