### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by darkpixlz** [comment]
The title should probably be a bit more descriptive. And also, maybe leave it up to the Discourse team to pick a new forum?

**Comment by tgxworld** [comment]
Thank you for the contribution but we will unfortunately not be accepting this change. The problem with the broken link will be fixed in https://github.com/discourse/discourse/pull/18236.

**Comment by Justman10000** [comment]
> The title should probably be a bit more descriptive. And also, maybe leave it up to the Discourse team to pick a new forum?

The one with the title is on purpose! First, it's irrelevant since my commits always say what they do... Second, it's practically, if a 2nd or more different commits should come along...

**Comment by Justman10000** [comment]
> Thank you for the contribution but we will unfortunately not be accepting this change. The problem with the broken link will be fixed in #18236.

And a question for you! Why don't you merge this instead of stealing my idea and using it on your behalf? If you should bane problems with commits here... I CAN UPDATE IT!

**Comment by Justman10000** [comment]
> Thank you for the contribution but we will unfortunately not be accepting this change. The problem with the broken link will be fixed in #18236.

And a question for you! Why don't you merge this instead of stealing my idea and using it on your behalf? If you should have problems with commits here... I CAN UPDATE IT! Because that's how you lose users! 

And it's really nice that a user who isn't even on the discourse team has these fucking rights! Will I still support Discourse... I'll think about it

**Comment by Justman10000** [comment]
> Thank you for the contribution but we will unfortunately not be accepting this change. The problem with the broken link will be fixed in #18236.

Serious? Instead of just taking my PR? Are you stealing my idea Idiot! No more PRs coming from me!

**Pull request closed without merging**
