### PR TITLE
FIX: allowed href scheme link can start with a +

### PR DESCRIPTION
**Pull request by majakomel**
It makes it possible to add links for international phone numbers that start with a plus sign
meta: https://meta.discourse.org/t/tel-links-not-working-with-plus-sign/76483

### CODE REVIEW

**Comment by coding-horror** [comment]
can we scope this to only mailto: ? I am worried about security implications of allowing extra characters in _all_ hrefs

**Comment by majakomel** [comment]
I have updated the code so it allows + only for tel:

**Comment by SamSaffron** [comment]
can we add a test for this, either in pretty_text_spec.rb or the js one?

**Comment by majakomel** [comment]
yep, added

**Pull request merged**
