### PR TITLE
FIX: Advanced Search to utilize Category Selector so it can distingui…

### PR DESCRIPTION
**Pull request by cpradio**
…sh uncategorized from no category selected

### CODE REVIEW

**Comment by cpradio** [comment]
@tgxworld, you will notice, I changed searchedTerms.category to '' instead of null, as you can see, username does that too, it seems autocomplete likes empty string over null, otherwise, it kicks all sorts of errors and I didn't want to mess with the category selector too much in fear of breaking other usages.

**Comment by cpradio** [comment]
Should the Time Out be increased for qunit's rake task? I feel like all of my checkins keep hitting it.

**Comment by cpradio** [comment]
Ah, is that a way to trick it to re-run the tests? I've been wondering how that can be done :+1:

**Comment by tgxworld** [comment]
Yup :)

**Comment by tgxworld** [comment]
@cpradio  Looks good to me :+1:  Thank you for the work :smile:

**Pull request merged**
