### PR TITLE
Update poll readme to include warning about the topic prefix.

### PR DESCRIPTION
**Pull request by darix**
Multiple users stumbled upon this issue already.

### CODE REVIEW

**Comment by coding-horror** [comment]
CLA signed?

**Comment by ZogStriP** [comment]
Thanks @darix but since I'm working on revamping polls that won't be necessary anymore ;)

**Comment by darix** [comment]
Even if you are working on it ... until it is committed .. this warning would be good to have in the documentation. I will sign the later CLA today.

**Comment by ZogStriP** [comment]
sure, ping me when you do, I'll merge that PR ;)

**Comment by darix** [comment]
just clicked submit on the CLA thing.

**Comment by ZogStriP** [comment]
Thanks :+1:

**Pull request merged**
