### PR TITLE
PERF: Delay updating Group user_count

### PR DESCRIPTION
**Pull request by xfalcox**
In events where *many* users are created quickly, the counter_cache
automatic behavior can become a bottleneck.

counter_cache will issue an UPDATE to PostgreSQL on every new object,
which will hold a lock over the group row on the table, and the table
bloat generated by the constant UPDATE churn will not help too.

Since we already have a recurrent backgroup job to ensure_consistency!
of those counts, we can safely remove the counter_cache annotation from
the association and let the count be updated only via the backgroud
routine.

### CODE REVIEW

**Comment by tgxworld** [comment]
> In events where many users are created quickly

Aren't such users extremely rare and does not reflect a real world scenario? 

My concern here is that the ensure consistency job is only run every 24 hours so this change introduces a delay into the accuracy of the count.

**Comment by xfalcox** [comment]
> Aren't such users extremely rare and does not reflect a real world scenario?

Yes. Proposed fix here is because of a site hitting that in a perf test and asking for a fix.

> My concern here is that the ensure consistency job is only run every 24 hours so this change introduces a delay into the accuracy of the count.

It's 12h nowadays, but we can do slice it anyway we want it. There is PeriodicalUpdates every 15 minutes, or even we could run it every minute elsewhere. Just a matter of picking what we want here.

**Comment by davidtaylorhq** [comment]
I think this change will lead to a lot of confusion in the groups UI. Group membership counts are very visible in the UI. If adding/removing users doesn't instantly update the count, it's going to feel like a bug.

I think if we need optimisation here it should either seamless, behind a flag, or only apply to massive groups.

**Comment by xfalcox** [comment]
Super seeded by #19256

**Pull request closed without merging**
