### PR TITLE
UX: Differentiate focus state from hover state

### PR DESCRIPTION
**Pull request by pmusaraj**
image

This only applies to buttons. The main change is that when a button gets a focused state via keyboard, it is highlighted a bit more than the hover (or sometimes selected) state of the button. This helps differentiate the button, especially when navigation via keyboard.

### CODE REVIEW

**Comment by CvX** [comment]
cc: @discourse/designers

**Comment by chapoi** [comment]
Why is the standard `d--selected` not good enough to use here?

**Comment by pmusaraj** [comment]
@chapoi good question. I didn't think about using `--d-selected` initially at all. And in looking into it now, it's not used in buttons, and I suspect it's going to have adverse effects if we were to introduce it here. 

And adding `darken-background($hover-bg-color, 0.1)` to the focus-visible state means it's a subtle overlay on the the other states of the buttons, in all their variations.  Note that `darken-background` just adds a thin, transparent image over the existing background of the button (see `mixins.scss:67`.

**Comment by chapoi** [comment]
> other states of the buttons, in all their variations.

What do you mean by this? They have other states?

The class is not used in buttons (yet) maybe because it's still fairly new, but it's added for this specific reason: do have a distinction between what's hovered and what's selected/focussed.

Also, when a user starts to select things via keyboard, the hover should actually be gone imo, because this is the same type of state and we don't want 2 visual "selections" on screen at the same time. See also new cmd-k modal that works this way.  That would also solve the original problem you're trying to fix with darken. Wdyt?

**Comment by pmusaraj** [comment]
So we have different types of butons and different states. The types are default, flat, primary, danger. States are regular, hover, active and in some cases current/selected (the screenshot in OP has the bell as a selected state button). 

If a user is using the keyboard to tab through the elements in a page, chances are they'll focus buttons that are in different states, and we want some kind of effect to show that. I don't think we can use a flat color for the focused state, there are too many different kinds of buttons: 

image

> Also, when a user starts to select things via keyboard, the hover should actually be gone imo, because this is the same type of state and we don't want 2 visual "selections" on screen at the same time. 

I'm not sure we can remove the hover state, we can't override the browser there. The added `focus-visible` styling is an extra indication for the browser, when it decides to set focus (usually, when keyboard navigating). 

Also, note that in most cases, the difference is very very subtle, here are before/after screen recordings for the post menu buttons: 


https://github.com/discourse/discourse/assets/368961/96cf5784-4298-42f5-aa50-7e52c1eb6f27


https://github.com/discourse/discourse/assets/368961/26379139-f6c6-4b6c-bb3f-5de06bfeca4e

(on focus-visible + hover, there is a subtle difference in the second video)

**Comment by chapoi** [comment]
Okay I thought it was specific about the notification panel, misunderstood.

**Review by chapoi — APPROVED** [review]

**Pull request merged**
