### PR TITLE
latest.json: last topic from first page appears on the second page as well

### PR DESCRIPTION
**Pull request by nbianca**
Fixes [this](https://meta.discourse.org/t/off-by-one-error-in-latest-json-page-1/58622/8).

### CODE REVIEW

**Comment by tgxworld** [comment]
Can we look into adding a test here? Thank you :+1:

**Comment by SamSaffron** [comment]
@nbianca  can you add a test here, I would love to close this off.

**Comment by coding-horror** [comment]
Can we merge this @eviltrout

**Comment by eviltrout** [comment]
Looks like we took too long to get around to the patch. It looks good but it can't be merged right now. @nbianca could you please rebase it so we can merge it?

**Comment by nbianca** [comment]
Done. Sorry, did not notice that earlier.

**Comment by eviltrout** [comment]
Thanks!

**Pull request merged**
