### PR TITLE
UX: Add printer-friendly.scss to make short topics print nicely.

### PR DESCRIPTION
**Pull request by cpradio**
UI
image

Print
faq_guidelines - staff - discourse

### CODE REVIEW

**Comment by riking** [comment]
Don't bother targeting `.ember-view` in any CSS rules - it's useless and might cause your CSS to break later.

**Comment by cpradio** [comment]
Thanks @riking, references to ember-view have been removed/replaced with class names.

**Comment by SamSaffron** [comment]
I thought the correct way of doing print is adding an extra stylesheet

eg:

```
<link rel="stylesheet" href="print.css" type="text/css" media="print" />
```

that way we don't load any of this stuff for desktop.

**Comment by coding-horror** [comment]
yeah I'd pull this into the media="print" stylesheet

**Comment by cpradio** [comment]
@SamSaffron, last I knew that was incorrect. The browser downloads both regardless, it just may defer the download by a few seconds.
https://zoompf.com/blog/2009/12/browser-performance-problem-with-css-print-media-type

Using a media query reduces the load by 1 HTTP request.

**Comment by cpradio** [comment]
I also proved it works the same on Mobile. It will download both (from what I can tell), the media query approach lessens the extra HTTP request and it honors the print styling.

**Comment by cpradio** [comment]
Okay, I talked with a few CSS gurus, Paul O'Brien being one of them and did a lot of article searching. In short, everyone says to use media queries over a separate print stylesheet.

A List Apart, uses the print media query for their printing needs and I believe everyone holds them up in high regards. I seriously believe the way I handled this, to be the best method for Discourse.

**Comment by SamSaffron** [comment]
ok, its such a small amount of extra rules, lets merge it.

**Pull request merged**
