### PR TITLE
FIX: Use array to keep best link for each onebox

### PR DESCRIPTION
**Pull request by nbianca**
Use a Map to hold the best link element for each Onebox HTML element.

Using an Object did not work as intended because Object can use only
Strings or Symbols as keys. Using HTML elements (representing oneboxes)
as keys most probably converted them to some generic string and sometimes
different Oneboxes were associated same key. It seems to be browser and
content dependent, without any clear indication of what is happening
internally.

This bug caused link counts to show only for the last Onebox because
the best link from the last Onebox was considered for all the other
Oneboxes.

### CODE REVIEW

**Comment by CvX** [comment]
Wouldn't it be better to use `Map()` instead?

**Comment by ZogStriP** [comment]
I agree with @CvX, looks like `Map()` would be a better fit here - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#objects_vs._maps

**Comment by nbianca** [comment]
TIL about Map. I did not know such thing existed and by the looks of it, it should be always preferred over {}.

**Comment by ZogStriP** [comment]
> by the looks of it, it should be always preferred over {}.

Depends no the use case. `Map()` is a pretty recent feature in JS and wasn't available everywhere until not that long ago... So `{}` was used as a map instead.

**Review by ZogStriP — APPROVED** [review]

**Comment by CvX** [comment]
> until not that long ago...

It's been available everywhere (even in IE!) for 7 years or more now. 😁

**Comment by ZogStriP** [comment]
> It's been available everywhere (even in IE!) for 7 years or more now. 😁

What now? 🤯

Got that part wrong then 🤦‍♂️

**Pull request merged**
