### PR TITLE
DEV: Drop `enable_long_polling` and `long_polling_interval` settings

### PR DESCRIPTION
**Pull request by tgxworld**
Scheduled to drop in 2.9.

### CODE REVIEW

**Review by Flink — APPROVED** [review]

**Comment by wzrdtales** [comment]
how do we disable it now then? There is a known issue on bitnami on passenger being incapable handling long polling properly.

**Comment by tgxworld** [comment]
It can still be disabled via global settings by setting the ENV `DISCOURSE_ENABLE_LONG_POLLING: false`

**Comment by tgxworld** [comment]
Do you mind opening a support topic on meta.discourse.org. We’ll need to assign this to someone to have a look. Thank you!

**Comment by wzrdtales** [comment]
https://meta.discourse.org/t/official-cloud-native-docker-image-from-discourse/228568

**Pull request merged**
