### PR TITLE
FIX: Force string conversions to UTF-8 "bytes"

### PR DESCRIPTION
**Pull request by chenyxuan**

### CODE REVIEW

**Review by ZogStriP — CHANGES_REQUESTED** [review]
Looks good 👍 

Can you also add a test with a poll with Chinese options to ensure it works properly in the future?

**Review by ZogStriP — APPROVED** [review]

**Comment by ZogStriP** [comment]
Looks like there are trailing whitespaces in the specs. Can you remove them?

**Comment by chenyxuan** [comment]
Thanks Zog. It's nice collaborating with you.

**Comment by ZogStriP** [comment]
Thanks a lot @chenyxuan 👍

**Pull request merged**
