### PR TITLE
Disallow access to raw email for non-staff users

### PR DESCRIPTION
**Pull request by communiteq**
As discussed in this topic on meta: https://meta.discourse.org/t/clicking-the-envelope-does-not-work-for-non-staff-users/232242

### CODE REVIEW

**Comment by tgxworld** [comment]
Thank you for your contribution here :) Is there a test we can add here for this change?

**Comment by communiteq** [comment]
TL;DR Not really

The change does not break existing tests. There could be additional tests but I think those are out of scope for the change.
Also, since the logic is pretty simple (basically: `is_staff?`)  any tests would replicate the code its attempting to test.

**Comment by tgxworld** [comment]
> There could be additional tests but I think those are out of scope for the change.

I'm not sure I understand here because a test that asserts that a non-admin users cannot view raw emails is going to help us in preventing this fix from regressing. This is especially important because this change is somewhat security related.

**Comment by communiteq** [comment]
My point was in the second line of my comment.

The code looks like this

```
  def can_view_raw_email?(post)
    post && is_staff?
  end
```

So a test would look like this

       expect(can_view_raw_email?(post)).to eq(is_staff?)

which just replicates the logic that's already there, since both the logic and the test 100% depend on `is_staff?` working correctly.

**Review by tgxworld — APPROVED** [review]

**Comment by tgxworld** [comment]
Spec added in https://github.com/discourse/discourse/pull/18245

**Pull request merged**
