### PR TITLE
DEV - add ‘workbox’ to list of versioned JS packages

### PR DESCRIPTION
**Pull request by jbrw**
‘workbox’ package is now written to a versioned directory, eg:

  public/javascripts/workbox/4.3.1/

Additionally, config/public_js_versions.yml is created to allow the Rails app to easily have access to the pathnames, etc., and the versioned workbox is referenced from service-worker.js.erb

### CODE REVIEW

**Review by pmusaraj — COMMENTED** [review]
Looks good, I'm guessing you opted to have a second file containing the plugin versions because it was too tricky to extract that info from the JS module in Ruby?

**Comment by jbrw** [comment]
I saw there was code to parse some of those other generated files (eg [js_constants_spec.rb](https://github.com/discourse/discourse/blob/master/spec/integrity/js_constants_spec.rb), but that felt a bit hacky and weird to me. But, yes, there is a risk the two files could get out of sync and so there is a trade-off.

Perhaps the answer is to write to a single YAML file to `public/javascript/` and have loadScript load, parse and memoize that, and have the backend code refer to the same file?

**Comment by pmusaraj** [comment]
I think as is is probably easier to reason about than with YAML in JS, that sounds complicated to handle in `loadSCript`.

**Comment by SamSaffron** [comment]
@jbrw closing this. I do support making workbox versioned but probably given ember cli we should take care of it as part of the ember cli work?

**Pull request closed without merging**
