### PR TITLE
FIX: converts html to text to use it as title attribute

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by gschlager** [comment]
Do you have an example of what this method is solving? I wanted to understand what it's doing, so I created [a fiddle](https://jsfiddle.net/x0u8hvjw/1/).

**Comment by jjaffeux** [comment]
try to have a string with this char for example https://www.codetable.net/hex/27

and use it as title attribute of an element

Envoyé de mon iPhone

**Comment by SamSaffron** [comment]
I think we should have a test here to at least cover an edge case, will allow us to swap the implementation later if we wish.

**Comment by jjaffeux** [comment]
@SamSaffron fair enough :+1:

@gschlager I added a test should be easier to understand

**Review by gschlager — APPROVED** [review]

**Pull request merged**
