### PR TITLE
FEATURE: Import Script for Fusionforge

### PR DESCRIPTION
**Pull request by wagner-intevation**
This is an import script for the forum/development platform https://www.fusionforge.org/projects/fusionforge imports users, forums and posts including attachments

### CODE REVIEW

**Comment by wagner-intevation** [comment]
The script is ready for review now.
We used a slightly adapted variant of the script (with some SQL `WHERE` statements to limit what is to be imported) to migrate a FusionForge forum to https://forum.gnupg.org/

**Comment by wagner-intevation** [comment]
> This pull request has been automatically marked as stale because it has been open for 60 days with no activity. To keep it open, remove the stale tag, push code, or add a comment. Otherwise, it will be closed in 14 days.

well, feel free to review and merge this PR. Not sure what else I should do?

**Review by gschlager — APPROVED** [review]

**Comment by gschlager** [comment]
Thank you!

**Comment by wagner-intevation** [comment]
Thank you for merging this addition!

**Pull request merged**
