### PR TITLE
DEV: Remove old deprecations

### PR DESCRIPTION
**Pull request by CvX**

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
I suspect this is going to break a lot of sites. In particular the `{{themeSetting.blah}}`, `Discourse.Site` and `Discourse.User` changes. We should proceed with extreme caution if we want to finally remove these.

**Review by jjaffeux — APPROVED** [review]

**Comment by jjaffeux** [comment]
As David I think we should at least wait after the bump.

**Comment by CvX** [comment]
I didn't find any `{{themeSetting.blah}}` in all-the repos, and the `Discourse` global doesn't seem to be used in any official plugins anymore, but I agree we should wait with the merge after the bump. In the meantime I'll see if there are any (maintained) 3rd-party plugins that could use a PR.

**Comment by K-adot** [comment]
upgrade

**Review by K-adot — COMMENTED** [review]
Good

**Comment by SamSaffron** [comment]
Are we good to merge this shortly after 2.8?

**Comment by davidtaylorhq** [comment]
Sounds good to me :+1:

By the way, if we're dropping the old `themeSetting.blah` syntax, we should make sure to drop the custom hbs-AST manipulation as well

https://github.com/discourse/discourse/blob/1d0e5ae4c89464ba4908d38b0813b5571449e5f0/lib/theme_javascript_compiler.rb#L14-L15

https://github.com/discourse/discourse/blob/1d0e5ae4c89464ba4908d38b0813b5571449e5f0/lib/theme_javascript_compiler.rb#L99-L100

**Comment by CvX** [comment]
Opened PRs:
1. https://github.com/danskdynamit/discourse-links-category/pull/11
2. https://github.com/muhlisbc/discourse-automatic-night-mode-theme/pull/2
3. https://github.com/jgujgu/discourse-guest-gate/pull/6
4. Robin submitted https://github.com/mozilla/discourse-expose-emails-in/pull/3 last year, but there's no response
5. Robin submitted https://github.com/hms-networks/discourse-private-topic/pull/24 last year, no response
6. See above ^ https://github.com/debtcollective/discourse-sentry/pull/4
7. Ditto ^ https://github.com/discourse-league/dl-license-keys/pull/1

Skipping:
1. [rux-pizza/discourse-awesome-bbcodes](https://github.com/rux-pizza/discourse-awesome-bbcodes/blob/master/assets/javascripts/jquery/autocomplete-tag.js.es6#L293-L293) because the plugin wasn't updated in almost 5 years
2. [paviliondev/discourse-topic-previews](https://github.com/paviliondev/discourse-topic-previews/blob/master/assets/javascripts/discourse/lib/utilities.js.es6#L34-L34) because it was deprecated in favor of [merefield/discourse-topic-list-previews-theme](https://github.com/merefield/discourse-topic-list-previews-theme)
3. https://github.com/nbianca/discourse-favorites - it wasn't updated in a while (@nbianca I think I already asked you some time ago if I should open PR or remove it from all-the*, but I don't remember your answer 😅)

**Comment by davidtaylorhq** [comment]
## `Discourse.User` / `Discourse.Site`
I think we should maintain `Discourse.User` and `Discourse.Site` for now. Note that we actually had to **add** support for these shortcuts under Ember CLI recently, because of the huge amount of breakage the removal was causing (cd460155aa, e46048eac2).

We are tracking this kind of deprecation issue internally (https://dev.discourse.org/t/59812), so I think we should wait until that topic is resolved before making these removals.

## `{{themeSettings.blah}}`
I just did a search on our internal usage of this, and it turns out we're still using this old syntax in a number of places. I'll DM you the details

---
The other removals feel safer, although I think we can still expect some breakage...

Can I suggest that we separate these removals out into individual commits / PRs? That way, we don't need to block merging all of them due to concerns about some of them? It will also make it easier to revert if we run into issues.

**Comment by SamSaffron** [comment]
Where are we on this @CvX ... maybe just skip the deprecations that @davidtaylorhq recommended and merge away... today is a good day to merge this :)

**Comment by SamSaffron** [comment]
Shall we merge @CvX  ?

**Comment by CvX** [comment]
Rebased, restored the three discussed APIs, removed `dropFrom` in their deprecation notices and updated one of the messages. Merging!

**Pull request merged**
