### PR TITLE
Incremental membership editing on /groups/xxx/members

### PR DESCRIPTION
**Pull request by jmay**
First cut at feature for https://meta.discourse.org/t/improved-group-members-management/16768/14

This is not ready for merge and there are no tests. I'm a novice with the Ember stuff, hopefully I'm not far wrong in the approach. Perhaps @eviltrout could take a look?

### CODE REVIEW

**Comment by jmay** [comment]
I have not touched the `/admin` group management stuff, focusing for now on building a new one under `/groups/members`.

Was trying to reuse the existing `user-selector` widget for adding users to a group, but could not find a way to make it just do single user entry rather than multiple. @eviltrout is this possible? That's an intimidating piece of code and I don't want to break it.

Various things seem to have broken in here from Ember updates & other changes that occurred over the holidays. I'll try to reduce this to smaller pieces & start with API as @sam suggested.

**Comment by ZogStriP** [comment]
@jmay strongly suggest you have a look at 060cda77729cb1c4a827560e09e89a7b22078ba9.

**Comment by jmay** [comment]
@ZogStriP Thanks! I'll rebuild this feature on top of this. Looks like more smaller PRs are better than fewer large ones. I'll break this thing down into smaller pieces, starting with the API side of the group manager role.

**Comment by ZogStriP** [comment]
yeah, we :heart: small PRs ;)

**Comment by SamSaffron** [comment]
I am closing this for now, lets work on smaller PRs

**Pull request closed without merging**
