### PR TITLE
Add a permalink normalization prefix setting for phpbb3

### PR DESCRIPTION
**Pull request by curiousdannii**
[As discussed in the forum](https://meta.discourse.org/t/importing-from-phpbb3/30810/421), I used this in a test migration to enable you to set a prefix for the permalink normalisations.

It's not very rigorous though. Is there a good way to strip slashes from the beginning and end, and to escape any slashes found in the middle?

Edit: or considering all this does is add some text to the regexs, maybe it would be better to just add some docs, rather than trying to make the code foolproof.

### CODE REVIEW

**Comment by gschlager** [comment]
I think the following code snippet should do the trick. It removes the leading/trailing slashes and escapes the remaining slashes in the prefix. There's no need for the warning about slashes in the settings file anymore.

```ruby
      if @settings.normalization_prefix.present?
        prefix = @settings.normalization_prefix[%r|^/?(.*?)/?$|, 1]
        normalization = "/#{prefix.gsub('/', '\/')}\\#{normalization}"
      end
```

**Comment by SamSaffron** [comment]
@gschlager can you merge this in with that amendment?

**Comment by curiousdannii** [comment]
I am intending to add the suggested patch, but if someone else gets there first I won't mind!

**Comment by gschlager** [comment]
@curiousdannii Thanks for the initial implementation. I added my proposed solution in https://github.com/discourse/discourse/commit/24369a81663b25c16b8fccd7e6e33fd4a44284f8

**Pull request closed without merging**
