### PR TITLE
FEATURE: Allow `rowspan` and `colspan` attributes on HTML tables

### PR DESCRIPTION
**Pull request by Juanc1to**
Augment the `allowList` for HTML tables to allow the `rowspan` and `colspan` attributes on `th` and `td` elements.

### CODE REVIEW

**Comment by Juanc1to** [comment]
I'm still interested in this functionality, if anyone is willing to work with me to get this PR reviewed.

**Comment by SamSaffron** [comment]
it feels safe to me... but not merging cleanly, can you try to rebase it?

**Comment by Juanc1to** [comment]
> it feels safe to me... but not merging cleanly, can you try to rebase it?

Okay, I think I rebased it... but maybe there was a problem? (I see that the GitHub workflow says that there are "conflicting files", but I didn't get any conflicts when I fetched, rebased, and then fast-forwarded. I am new to this, though, so I could easily be doing something wrong.)

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
Thank you! sorry for the huge delay here

**Comment by Juanc1to** [comment]
> Thank you! sorry for the huge delay here

Well, truly, a big part of the delay involved waiting for me to put the rebase together. Thanks for working with me on this!

**Pull request merged**
