### PR TITLE
UX: adds emoji in the table-title of admin-report-table

### PR DESCRIPTION
**Pull request by Ahmedgagan**
@jjaffeux  To test it out locally, do try it with this PR https://github.com/discourse/discourse-reactions/pull/73
Screenshot 2021-04-13 at 11 37 28 PM

### CODE REVIEW

**Comment by jjaffeux** [comment]
Can you just try to convert emoji code from title with emojiUnescape before displaying it ?

Also we just need the emoji, no need for text + emoji

**Comment by Ahmedgagan** [comment]
> Can you just try to convert emoji code from title with emojiUnescape before displaying it ?
I think converting emoji from the title might act weird when coincidentally title is an emoji name. Then we will display the emoji and hide the title. thoughts?

**Comment by Ahmedgagan** [comment]
Screenshot 2021-04-15 at 11 51 01 PM

**Comment by jjaffeux** [comment]
No it's ok to convert. we have the helper for it, just use it. If we have :laughing: in a text, it's expected to be converted

**Comment by Ahmedgagan** [comment]
Sure, that's right 😅

**Comment by jjaffeux** [comment]
I wonder if you can't actually convert it directly from discourse-reactions code

**Comment by Ahmedgagan** [comment]
> I wonder if you can't actually convert it directly from discourse-reactions code

From discourse reactions, we don't need to convert, as we are taking titles that are entered using emoji-picker

**Comment by Ahmedgagan** [comment]
Also, In this our first column is a date, and if we take the title as emoji, it converts date to an emoji. Is it okay?
Screenshot 2021-04-16 at 3 02 06 PM

**Comment by Ahmedgagan** [comment]
Screenshot 2021-04-16 at 5 30 21 PM
Screenshot 2021-04-16 at 5 29 28 PM

**Comment by Ahmedgagan** [comment]
@jjaffeux Added emoji's `img` tag from backend & done minimal changes here. Do have a look

**Review by ZogStriP — APPROVED** [review]

**Review by davidtaylorhq — APPROVED** [review]

**Pull request merged**
