### PR TITLE
Log error when optimized image file fails to store.

### PR DESCRIPTION
**Pull request by schungx**

### CODE REVIEW

**Comment by eviltrout** [comment]
Seems reasonable to me! Thanks.

**Comment by schungx** [comment]
@eviltrout  I have been thinking whether it is necessary to put in also a `rescue` section because `store_optimized_image` may throw (in external stores at least) when the store fails for any reason.

If it throws, it will probably leave the temp file open dangling, and create an `OptimizedImage` record with no `url`.

**Comment by eviltrout** [comment]
@schungx you might want a follow up PR for that then.

**Comment by schungx** [comment]
Guess I'll leave it until there appears to be mysterious image store failings... ;-)

**Pull request merged**
