### PR TITLE
DEV: Switch sidebar section link identifier to data attribute

### PR DESCRIPTION
**Pull request by tgxworld**
Data attribute is less restrictive than relying on the class attribute

### CODE REVIEW

**Review by lis2 — APPROVED** [review]

**Comment by martin-brennan** [comment]
@tgxworld you may need to leave the class in at first to be able to fix up other plugins, and then remove it in a subsequent PR.

**Comment by martin-brennan** [comment]
Also linting is failing, test failures are legit too.

**Comment by tgxworld** [comment]
@martin-brennan I've fixed the failing tests in core :)

**Comment by martin-brennan** [comment]
Thanks @tgxworld !

**Pull request merged**
