### PR TITLE
Escape term for category autocomplete regex

### PR DESCRIPTION
**Pull request by Elberet**
See https://meta.discourse.org/t/error-when-text-entered-in-category-select-box-contains-invalid-regex-syntax/27999?u=elberet

### CODE REVIEW

**Comment by SamSaffron** [comment]
that regex is making me cringe, why not just check that the string is in the other string with indexOf or something.

**Comment by riking** [comment]
Maybe we need a regexEscape() function that we can use in all the spots we need a regexp escape.

**Comment by Elberet** [comment]
What's so bad about the regex? It matches a single character from character class container characters that have special meaning for JS regexes... the only reason it's hard to read is all the escaping.
Using indexOf "or something" would add two or three local variables and a loop.

**Comment by DeanMarkTaylor** [comment]
I would recommend using a less escape crazy version:
```JavaScript
function escapeRegExp(string){
  return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
```
Taken from: https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by riking** [comment]
@Elberet it's not the regex per se, but more the fact that this function - escaping for use in a regex - is present in multiple places in Discourse, so there should be one place with the function that gets used every time.

**Comment by Elberet** [comment]
Yeah, I'm on it. I'll follow up on Monday. ^^

**Comment by ZogStriP** [comment]
ping @Elberet

**Comment by ZogStriP** [comment]
Closing this for now. @Elberet feel free to ping us when you have time to work on it.

**Pull request closed without merging**
