### PR TITLE
TopicStatusView: Convert statuses to property.

### PR DESCRIPTION
**Pull request by caugner**
Allows plugins (esp. `discourse-solved`) to add custom statuses to the topic list in the categories overview.

### CODE REVIEW

**Comment by SamSaffron** [comment]
I am not against this, but we need some tests here that at least exercise the new API and demo how it works.

**Comment by caugner** [comment]
@SamSaffron I am demonstrating how it works in https://github.com/discourse/discourse-solved/pull/29 (which depends on this PR), but I'm willing to provide tests. Could you direct me to an existing test whose pattern I could adapt? I looked in `test/javascripts/components/`, but couldn't find any that tests a Ember component like this.

My idea would be the following:
```js
import TopicStatusComponent from 'discourse/components/topic-status';

TopicStatusComponent.reopen({
  statuses: function() {
    const results = this._super();
      results.push({
        name: 'bell',
        key: 'topic.bell',
      });
      return results;
  }.property()
});

// TODO Somehow call TopicStatusComponent.renderString().
// TODO Verify that result contains the bell icon.
```

**Comment by caugner** [comment]
@SamSaffron Any ideas regarding my previous question?

**Comment by coding-horror** [comment]
@eviltrout any suggestions here?

**Comment by eviltrout** [comment]
I am not a fan of depending on plugins to reopen a class to add functionality. If a plugin has an `import` statement of one of our classes and we rename it for example, it will break the plugin in a hard way.

Instead this functionality should be added to the `pluginApi` as a method like:

```javascript
api.addTopicStatus(topic => {
  if (topic.get('alarm')) {
    return { name: 'bell', key: 'topic.bell' };
  }
});
```

**Comment by caugner** [comment]
@eviltrout I agree that it would be better if the `pluginApi` would support this. I might be wrong, but doesn't this mean that topic status handling would need to be properly centralised for this to work (so that the same status icons appear everywhere, i.e. not only in lists – where it "works" – and in overviews – where my PR aimed at –, but also in other places, such as search results and email digests).

Then [this spot](https://github.com/discourse/discourse-solved/blob/master/assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6#L196-L209) in the *discourse-solved* plugin could hopefully be refactored as well (which hooks in [topic-status.js.es6](https://github.com/discourse/discourse/blob/be3a5a56ccc284b352aa65080fc6b955f73cc72a/app/assets/javascripts/discourse/views/topic-status.js.es6#L5-L61) in the same way as my PR).

**Comment by eviltrout** [comment]
Probably a good idea to centralize that logic, yes! Although we could start with making it work for your case and then add it for others later (using the API)

**Comment by coding-horror** [comment]
Should this be closed as it is nearly 6 months old now?

**Comment by caugner** [comment]
@coding-horror Sorry for the delay, I'm currently too busy to follow up on this, so closing is fine.

**Comment by coding-horror** [comment]
We just upgraded to Ember 2.10 (latest, from 18 month old Ember 1.12) so a _lot_ of stuff changed on our end as well particularly w/r/t plugins.

**Pull request closed without merging**
