### PR TITLE
FEATURE: Adds transliteration of German umlauts in slugs

### PR DESCRIPTION
**Pull request by gschlager**
https://meta.discourse.org/t/please-replace-german-umlauts-in-urls-with-their-respective-digraphs/24489/7

- Moves the already existing transliteration rules into `transliterations.en.yml` (there's no need to translate this for every language). The same goes for the stringex configuration.
- Doesn't calculate the default slug for *zh_CN* and *ja* anymore. It hasn't been used anyway since stringex is used instead.
- Removes a wrong comment from the Russion transliteration file (I hate wrong comments)

### CODE REVIEW

**Comment by riking** [comment]
Can you add these for the Vietnamese transliterations? https://meta.discourse.org/t/vietnamese-slug-support-for-better-seo/22422/9?u=riking

**Comment by gschlager** [comment]
OK, I've done that using the values from https://github.com/thangngoc89/discourse-vietnamese-slug
However, I don't think this will be usable until the Vietnamese translations are actually added to Discourse. There are no locale files for vi_VN yet.

**Comment by gschlager** [comment]
Travis error doesn't seem to be related to this.

**Comment by riking** [comment]
> vi_VN

Use just `vi`, as that's what's in plurals.rb.

**Comment by gschlager** [comment]
Done.
BTW: The tests seem to be rather flaky at the moment.

**Comment by SamSaffron** [comment]
@nlalonde something is super odd with our report specs, they always seem to fail erratically

**Comment by SamSaffron** [comment]
I am fine with this change, moving transliteration out of transifex makes sense.

**Pull request merged**
