### PR TITLE
Fix structural problems with the openapi spec

### PR DESCRIPTION
**Pull request by Kyle-Ye**
rswag is extremely permissive; way moreso than the actual OAS standard, or JSON schema!

It will cause a downstream parsing issue which using openapi.json produced by this repo. (Hosted here https://github.com/discourse/discourse_api_docs)

See more info here: https://github.com/mattpolzin/OpenAPIKit/issues/277#issuecomment-1599019608

Historically, we have fixed such problems, but they have not been completely repaired. And such problems may be added again later.
> See history fix: https://github.com/discourse/discourse/pull/16710
> See bug introduce: https://github.com/discourse/discourse/pull/21028

Some follow up needed:
- After this PR is merged. Please trigger a bot to make an update for https://github.com/discourse/discourse_api_docs repo.
- Add some strict OpenAPI spec test in case such permissive syntax show up again in a later commit/PR.

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
```swift
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid YAML.", underlyingError: Optional(Expected `items` value in .content['application/json'].schema.properties.actions_summary for the status code '200' response of the **GET** endpoint under `/posts/{id}.json` to be parsable as Mapping but it was not.)))
```

There is still something to update to fully compatible with OpenAPI 3.1.0

**Comment by Kyle-Ye** [comment]
This is due to the original output of 
```
.content['application/json'].schema.properties.actions_summary for the status code '200' response of the **GET** endpoint under `/posts/{id}.json`
```
is
```
actions_summary:
type: array
items:
- type: object
  additionalProperties: false
  properties:
    id:
      type: integer
      description: "`2`: like, `3`, `4`, `6`, `7`, `8`: flag"
    count:
      type: integer
    acted:
      type: boolean
    can_undo:
      type: boolean
    can_act:
      type: boolean
  required:
  - id
```

On line 4, an extra `-` before "type" cause this issue.

**Comment by Kyle-Ye** [comment]
Fixed all issue for me and test it with locally.

**Review by oblakeerickson — APPROVED** [review]

**Comment by oblakeerickson** [comment]
Thanks!

**Comment by Kyle-Ye** [comment]
> Thanks!

Could you help trigger a Github Action PR here. Thanks 

https://github.com/discourse/discourse_api_docs

**Comment by oblakeerickson** [comment]
It auto triggers every 24hours

**Comment by Kyle-Ye** [comment]
> Add some strict OpenAPI spec test in case such permissive syntax show up again in a later commit/PR.

One more thing here, is there anything we can do to prevent such issue happens again?

Maybe add a pipeline which pass generated `openapi.yml` (made by `rake rswag:specs:swaggerize`) to an OpenAPI 3.1.0 linter.

**Pull request merged**
