### PR TITLE
FIX: make sure every user instance has correct status tracking counter

### PR DESCRIPTION
**Pull request by AndrewPrigorshnev**
On the user model, `_subscribersCount` and `_clearStatusTimerId` are internal fields that support tracking of user status.

Every user model has to have its own counters and those counters should be initialized with default values (0 or null) during initialization of a model. 

But it's possible that some code will try to  pass let's say `_subscribersCount: 2` to the _create_ method (for example, when using a previously cached user object). This PR makes sure that  `_subscribersCount` and `_clearStatusTimerId` behave like private fields and never get set during initialization of the user model.

This is something that could be implemented by making these fields private, but sadly, `EmberObject` doesn't support private fields.

### CODE REVIEW

**Comment by tgxworld** [comment]
> But it's possible that some code will try to pass let's say _subscribersCount: 2 to the create method (for example, when using a previously cached user object).

I feel like the right fix here is to fix the spots that are passing the wrong arguments in during initialisation instead. 

I'm definitely missing something but where are we using the `_subscribersCount` field?

**Comment by AndrewPrigorshnev** [comment]
> I'm definitely missing something but where are we using the `_subscribersCount` field?

Oh, sorry, that counter was added in another PR that isn't reviewed yet – https://github.com/discourse/discourse/pull/17497, here:

https://github.com/discourse/discourse/blob/b323af91e6b3d3958e7e1fe9cde18cb68b31c6c4/app/assets/javascripts/discourse/app/models/user.js#L1182

It's a private counter, and it doesn't suppose to be used anywhere outside the user model. The chat does some cashing of user-model-like objects and ends up copying these "private" fields, since in fact there aren't private, `EmberObject` cannot enforce private fields. I didn't find the exact place where that copying is happening, even if I find that place and add a fix there, I still absolutely want us to enforce it on the user model level, the only way the `_subscribersCount` counter could increase should be a call to `user.trackStatus()`.

Also, it's just simpler to enforce it once, then fix and path it in every new place where we discover it.

In the future, when we switch to using js native classes, we could use a real private field for this counter, and we'll drop this path.

**Comment by tgxworld** [comment]
> I didn't find the exact place where that copying is happening, even if I find that place and add a fix there, I still absolutely want us to enforce it on the user model level, the only way the _subscribersCount counter could increase should be a call to user.trackStatus().

This reminds of a comment I made previously about `User.reopen` and I suggested moving the logic into a dedicated class of its own with its own state. I think we can avoid this problem entirely if the status tracking and its state lives in a class of its own right? I

**Comment by AndrewPrigorshnev** [comment]
> This reminds of a comment I made previously about `User.reopen` and I suggested moving the logic into a dedicated class of its own with its own state. I think we can avoid this problem entirely if the status tracking and its state lives in a class of its own right?

That's true, that problem will be solved then. 

Here is that discussion - https://github.com/discourse/discourse/pull/17236#discussion_r910687188. After working at some other places with status, I decided to leave it as is – implemented in the User class because I still felt it's a better tradeoff.

In the same time, I see the pros of the implementation you suggested. And the problem we're discussing here is another argument in favor of your version.

But I wonder If we can refactor that later in a separate PR, this PR blocks merging of a couple of other PRs for chat.

**Review by tgxworld — APPROVED** [review]

**Comment by tgxworld** [comment]
Yup we can certainly review this again in the future. No need to block this PR now.

**Comment by AndrewPrigorshnev** [comment]
@tgxworld, thank you for review!

**Pull request merged**
