### PR TITLE
Stop Rails from escaping the HTML in this description.

### PR DESCRIPTION
**Pull request by begrif**
This will let links in descriptions actually work. Yay.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Can you confirm that nothing weird happens if a category description is `<script>`

**Comment by begrif** [comment]
Yes. I just tried it. In (first post in About topic for meta):

`**This** is the *place* to <s>vent</s> explain what's :frowning_face: wrong. Still.<script>Alert(1)</script> (And not a distillery)`

Out:
`<strong>This</strong> is the <em
>place</em> to <s>vent</s> explain what's  wrong. Still. (And not a distillery)`

And in console:
```
[3] pry(main)> cats =  CategoryList.new
[5] pry(main)> cats.categories[1].description
=> "<strong>This</strong> is the <em>place</em> to <s>vent</s> explain what's  wrong. Still. (And not a distillery)"
```

I have not traced the code to figure out where that is getting sanitized. When I saw the emojis being filtered I was not concerned, but it is a good question to ask.

**Comment by SamSaffron** [comment]
cool, let's merge it then. thanks!

**Comment by begrif** [comment]
:+1:

**Pull request merged**
