### PR TITLE
FEATURE: Allow group owners to edit group name and avatar flair.

### PR DESCRIPTION
**Pull request by tgxworld**
screenshot from 2016-11-30 16-15-30

screenshot from 2016-11-30 16-09-47

### CODE REVIEW

**Comment by tgxworld** [comment]
cc @eviltrout Can you review this? Thank you!

**Comment by chenyingyin** [comment]
default

**Comment by SamSaffron** [comment]
not sure about allowing them to edit group name, seems like it is risky to me.

**Comment by tgxworld** [comment]
Hmm that is true. All existing mentions will have to be changed. Strange we don't have that warning in the admin panel.

**Pull request merged**
