### PR TITLE
FEATURE: unbind font awesome icon in share button

### PR DESCRIPTION
**Pull request by fantasticfears**
- extract font awesome class from share link
- add another share services

PS: `<input>` is a void element which doesn't need to close itself in HTML5. So I removed it.

### CODE REVIEW

**Comment by ZogStriP** [comment]
Why did you do make the share button icon unbound? Are there any performance issues?

**Comment by fantasticfears** [comment]
Simply because there are icons not existing in the font awesome. At least I need a way to use a icon when add a custom service by plugin.

I don't know how to measure the performance in this case. Ember Inspector told me they rendered under 1ms.

**Comment by eviltrout** [comment]
The assumption I made is that it would be a font awesome icon which indeed is always the case in stock discourse.

I'm definitely in favor of letting people use images for icons but I think repurposing "icon" seems a bit odd.

I'd prefer if we changed icon to be `'faIcon` with the existing behavior, and then `htmlIcon` for custom HTML.

**Comment by fantasticfears** [comment]
@eviltrout done

**Comment by SamSaffron** [comment]
we can't be adding redit linkedin and tumblr by default that just feels wrong to me cc @coding-horror

**Comment by coding-horror** [comment]
yes agreed the defaults should not change. Extensibility is the goal here, not changing the defaults.

**Comment by fantasticfears** [comment]
They were removed

**Comment by SamSaffron** [comment]
sorry, needs a rebase

**Comment by fantasticfears** [comment]
@SamSaffron Rebased. The branch was forced updated.

**Comment by ZogStriP** [comment]
:+1: Thanks

**Pull request merged**
