### PR TITLE
DEV: Use site setting mandatory_values for chat allowed groups

### PR DESCRIPTION
**Pull request by martin-brennan**
For both `chat_allowed_groups` and `chat_message_flag_allowed_groups`,
this commit removes the `is_staff?` guardian check, and instead
adds both `moderators` and `admins` auto groups as `mandatory_values`
to those settings, as part of an ongoing effort to do this for
group-based setting values.

### CODE REVIEW

**Comment by SamSaffron** [comment]
I like this, but does this need any kind of migration? what happens to existing site settings here that don't have it set?

**Comment by martin-brennan** [comment]
@SamSaffron No it's not necessary; the way this `mandatory_values` code works is that it injects these values no matter what, both in the `get` and the `set` for the site setting. So if you call `SiteSetting.chat_allowed_groups`, and the database already had group `99|76` in it, you would get back `1|2|99|76`. And if you did `SiteSetting.chat_allowed_groups = "54"` we save the mandatory values too, so you will also get back `SiteSetting.chat_allowed_groups => '1|2|54'`

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
approved but just double checking, will this handle duplication?

**Comment by martin-brennan** [comment]
> will this handle duplication?

@SamSaffron as in, if I do `SiteSetting.chat_allowed_groups = "54"` multiple times it won't keep adding `1|2` on forever until we get `1|2|1|2|1|2|1|2|1|2`? If so yes that was handled by Kris when he made this mandatory values thing :)

**Review by Drenmi — APPROVED** [review]

**Pull request merged**
