### PR TITLE
FEATURE: Introducing admin `Uploads`

### PR DESCRIPTION
**Pull request by khalilovcmded**
discourse uploads

### CODE REVIEW

**Comment by terraboss** [comment]
Is there any way to sort and filter files by size and extension? Delete them individualy?

**Comment by eviltrout** [comment]
Is there a dev topic to discuss this new feature? I'd like to know the background and use case.

**Comment by khalilovcmded** [comment]
@eviltrout Yes, sorry for not [linking it](https://meta.discourse.org/t/list-of-all-uploaded-files/63714/3) earlier.

**Comment by khalilovcmded** [comment]
@terraboss perhaps there could be a way, I guess this all falls to [this interesting line of questioning](https://meta.discourse.org/t/list-of-all-uploaded-files/63714/5) by Sam.

**Comment by SamSaffron** [comment]
@khalilovcmd would love you to work on this, but I feel we got to come up with a plan first prior to the PR, love that you experimented here!

**Pull request closed without merging**
