### PR TITLE
 new plugin-outlet named: full-page-search-result

### PR DESCRIPTION
**Pull request by itsazzad**
Can you please add the following plugin outlet ? : full-page-search-result

### CODE REVIEW

**Comment by itsazzad** [comment]
Signed already!

**Comment by erlend-sh** [comment]
Thanks for the contribution!

Sorry about the trouble with the CLA bot, but did you by any chance sign the CLA with a different account? If you've already signed the CLA the bot should recognise this and post a confirmation message accordingly.

**Comment by itsazzad** [comment]
Just now signed again!

**Comment by ZogStriP** [comment]
@itsazzad Would you mind explaining why do you need these plugin outlets?

**Comment by itsazzad** [comment]
I need like these using adplugin:
screen shot 2018-02-05 at 7 06 32 pm
screen shot 2018-02-05 at 7 07 22 pm

**Comment by itsazzad** [comment]
Any update?

**Comment by SamSaffron** [comment]
hmmm but why is {{plugin-outlet name="discovery-list-container-top"}} being added, this seems nothing to do with full page search. it should not have discovery outlets there.

**Comment by tgxworld** [comment]
@itsazzad Could you open a topic on meta.discourse.org with your request for the above mentioned outlets to see what the rest of the team thinks about it? I'm personally not keen on the outlets as the positions of the outlets are a little odd and the only thing it is used for right now is to display ads.

**Pull request closed without merging**
