### PR TITLE
Feature: (WIP) Set locale from Accept-Language header

### PR DESCRIPTION
**Pull request by scossar**
For forums that allow user's to select their locale, this PR sets the locale for anonymous users from the Accept-Language header. It also automatically adds a locale property when a new user is created. This property is set from the I18n.locale. The reason for setting the locale on signup is so that new users can begin using the site in their preferred language without having to navigate the their user preferences to change it. This functionality is very similar to how google/facebook/twitter deal with locale.

It is using the http_accept_language gem to detect the user's preferred language: https://github.com/iain/http_accept_language

### CODE REVIEW

**Comment by coding-horror** [comment]
Can you review this Australia Monday, Sam? We have a customer interested in this

**Comment by ZogStriP** [comment]
Looks like this needs a rebase

**Comment by scossar** [comment]
I can do it later today.

**Comment by scossar** [comment]
It should be good now.

**Comment by coding-horror** [comment]
Ok is this safe to merge @zogstrip?

**Comment by ZogStriP** [comment]
:+1:

**Comment by MuthukkumarNicheSoft** [comment]
I have cloned this code and put it in discourse but no luck. could some one please tell me how to fix the issue of user language selection.

**Pull request merged**
