### PR TITLE
DEV: Enable parallel system specs in GitHub actions CI

### PR DESCRIPTION
**Pull request by davidtaylorhq**

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Example of how browser logs are now printed:

Screenshot 2022-12-22 at 17 22 26

**Comment by jjaffeux** [comment]
The second failure should have been fixed on main. And the first one is new flakey:

```
 1) Archive channel when archiving is enabled when admin user when archiving failed can be retried
     Failure/Error: example.run

     Capybara::ElementNotFound:
       Unable to find css ".chat-channel-archive-status a"

     [Screenshot Image]: /__w/discourse/discourse/tmp/capybara/failures_r_spec_example_groups_archive_channel_when_archiving_is_enabled_when_admin_user_when_archiving_failed_can_be_retried_397.png
```

I will look at it :+1:

**Comment by jjaffeux** [comment]
I noticed it does print this:

```
     ~~~~~~~ JS LOGS ~~~~~~~
     ~~~~~ END JS LOGS ~~~~~
```

We probably want to check if we actually have something to log

**Comment by jjaffeux** [comment]
We did merge it already right? I mean the parallel part. It's only few refinements or Im missing something?

**Review by jjaffeux — APPROVED** [review]

**Pull request merged**
