### PR TITLE
Updated highlight.js

### PR DESCRIPTION
**Pull request by phw**
This updates highlightjs to the latest version, which provides additional syntax definitions and fixes to existing ones.

Please note that there was a cleanup of the highlight.js CSS, see https://github.com/isagalaev/highlight.js/blob/master/CHANGES.md and the new class reference at http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html. I have tried to adapt the existing stylesheets to the new rules and tried to evaluate the affected languages. Given the amount of languages slight differences in highlighting are a possibility and in some cases unavoidable (e.g. for diff there was previously a distinction between "addition" and "change", now there is only the "addition" class for both cases).

### CODE REVIEW

**Comment by coding-horror** [comment]
thanks! @SamSaffron will need to review this.

**Comment by Freso** [comment]
@phw Perhaps update to pull in latest changes for taggerscript from hljs? :)

**Comment by phw** [comment]
@Freso Done, I rebased the PR against master to keep it simple.

**Comment by SamSaffron** [comment]
I worry about manual work here, we have a rake task for updating it, can you update it and run it here? otherwise we are setting us up a timebomb.

**Comment by phw** [comment]
The update was performed with

    bin/rake update:highlights

The only manual work was updating the Discourse specific CSS to reflect the styling changes in highlight.js 0.9 :)

**Comment by SamSaffron** [comment]
cool, sounds good then!

**Comment by SamSaffron** [comment]
hmmm lang-auto is playing up big time for me ... no highlighting unless a lang is specified

**Comment by SamSaffron** [comment]
ok added some code to strip lang-auto cause highlightjs is being strict about it.

**Comment by phw** [comment]
Interesting. I only tested with explicit languages to see the highlighting, sorry for that

**Pull request merged**
