### PR TITLE
Add styling & assets for google docs placeholder oneboxes

### PR DESCRIPTION
**Pull request by riking**
https://github.com/discourse/onebox/pull/307

http://setup.googleapps.com/Home/user-resources/google-icons-and-logos/guidelines-for-using-google-brand-features

> - Use these Google icons and logos in the materials you create for your organization in conjunction with your deployment. You can be creative and involve other staff at your organization, but please always be aware of the way in which you are using Google Brand Features.
> - If you are using a Google trademark, distinguish the trademark from the surrounding text in some way. Capitalize the first letter, capitalize or italicize the entire mark, place the mark in quotes, use a different type style or font for the mark than for the generic name.
> - Use the trademark only as an adjective, never as a noun or verb, and never in the plural or possessive form.
> - Use a generic term following the trademark, for example: GOOGLE search engine, Google search, GOOGLE web search.
> - Use only Google-approved artwork when using Google's logos.

This PR provides the image assets for the onebox PR so that we have no iframe flashing in the composer preview for Docs embeds.

image

### CODE REVIEW

**Comment by ZogStriP** [comment]
Is that still required @techAPJ? I think that specific onebox changed recently

**Comment by techAPJ** [comment]
@ZogStriP I just merged the accompanying onebox PR: https://github.com/discourse/onebox/pull/307

Merging in this one too.

**Comment by ZogStriP** [comment]
:+1:

**Comment by riking** [comment]
Yeah, looks like none of the code changed in the meantime.

@ZogStriP this needs to be done for ALL oneboxes that render an `<iframe>`.

**Pull request merged**
