### PR TITLE
FEATURE: Warn admins when installing a theme that's already installed

### PR DESCRIPTION
**Pull request by OsamaSayegh**
Installing multiple copies of the same theme/component is possible, but you rarely need to actually have multiple copies installed. We've seen many times new admins installing duplicates of components because they were unaware it was already installed. This PR makes the theme installer modal loop through the existing themes when you click on 'install', and if there is a theme with a URL that matches the URL you entered, a warning will show up and you will need to click 'install' again to proceed.

Screenshot:

image

### CODE REVIEW

**Comment by jjaffeux** [comment]
Also Im not sure why we dont use bootbox for this?

**Comment by OsamaSayegh** [comment]
@jjaffeux I didn't use bootbox because the install UI is a modal itself and I think it'd be odd to show a modal on top of another.

**Comment by jjaffeux** [comment]
> @jjaffeux I didn't use bootbox because the install UI is a modal itself and I think it'd be odd to show a modal on top of another. 

indeed it will just not work in fact

**Comment by OsamaSayegh** [comment]
@jjaffeux was there something else you wanted say? You started your comment with "Also" which makes me think you made 2 comments but one of them didn't go through?

**Comment by jjaffeux** [comment]
> @jjaffeux was there something else you wanted say? You started your comment with "Also" which makes me think you made 2 comments but one of them didn't go through?

no I dont think so 🤷‍♂️ lgtm

**Review by jjaffeux — APPROVED** [review]

**Pull request merged**
