### PR TITLE
FEATURE: enforce tagging on categories

### PR DESCRIPTION
**Pull request by techAPJ**
Meta discussion: https://meta.discourse.org/t/the-option-to-enforce-tagging/69527/

TLDR: This PR adds a setting for each category to set "minimum required tags".

Client side validation is pending. (cc @jjaffeux)

### CODE REVIEW

**Comment by jjaffeux** [comment]
@techAPJ Hi Arpit, I just merged https://github.com/discourse/discourse/commits/master So you can now do:

`{{mini-tag-chooser minimum=2 ...}}` and also `{{mini-tag-chooser minimum=2 minimumLabel="category.minimum_tags"}}`

Let me know if you need help.

**Comment by techAPJ** [comment]
@jjaffeux Awesome, thank you!

@SamSaffron This PR is now ready to be merged. However, I wanted to verify the validation logic with you.

The minimum tag validation on a category will _not_ happen if:

- tagging is disabled globally
- acting user is staff
- acting user does not have sufficient trust level to use/add tags

Does the above looks good to you?

**Comment by SamSaffron** [comment]
One question I have is how do you just set a single default? Otherwise you have to enter every single category?  @coding-horror what is your call here do you want a site-setting for min-tags or is forcing people to work through every category enough here? 

The validation logic seems fine

**Comment by coding-horror** [comment]
probably per category is best for now?

**Comment by techAPJ** [comment]
Yeah, for now the setting is per category, but we can probably add a global site setting that will be given second priority.. i.e. if category setting is `0` then global site setting will be considered.

**Comment by boomsky** [comment]
> @techAPJ Hi Arpit, I just merged [f0fe16d](https://github.com/discourse/discourse/commit/f0fe16d824abda98de23d7d7de80afbad429e4df) So you can now do:
> 
> `{{mini-tag-chooser minimum=2 ...}}` and also `{{mini-tag-chooser minimum=2 minimumLabel="category.minimum_tags"}}`
> 
> Let me know if you need help.

how can i find this file~~

**Pull request merged**
