### PR TITLE
A typo fix

### PR DESCRIPTION
**Pull request by rizka10**
Mailinglist --> Mailing list

### CODE REVIEW

**Comment by gschlager** [comment]
Thanks, but you shouldn't change the key, otherwise this won't work anymore.

**Comment by rizka10** [comment]
Ah, true. I should have updated the key in the code, too of course. Sorry, that was pretty stupid. But I guess the key's name doesn't even matter.

**Comment by gschlager** [comment]
Yeah, I suggest you update only the text and leave everything else alone.

**Comment by SamSaffron** [comment]
ok fixed this by editing the text thanks for the PR

**Pull request closed without merging**
