### PR TITLE
FIX: Uploads cannot be mapped due to the cook-text's element attr being null

### PR DESCRIPTION
**Pull request by romanrizzi**

### CODE REVIEW

**Comment by romanrizzi** [comment]
@eviltrout The `cook-text` component will always fail to resolve upload URLs because the `tagName` is always ""

```javascript
const CookText = Component.extend({
  tagName: "",
  cooked: null,

[...]
```

I suspect this started happening after this commit:

https://github.com/discourse/discourse/commit/f0620e7118a76a1faea0ca15ac554818f8bb1bcf

**Comment by eviltrout** [comment]
@romanrizzi  can you explain a little more? In particular I'm not sure why a missing `<div>` would cause uploads not to resolve?

**Comment by romanrizzi** [comment]
I just noticed that I linked the wrong commit, sorry. I was talking about this one:

https://github.com/discourse/discourse/commit/293467a37ae33c5fd8fd40bbfc05bffa578b90ed

To resolve the upload's URL, we pass `this.element` to the module:

```javascript
next(() =>
        window
          .requireModule("pretty-text/upload-short-url")
          .resolveAllShortUrls(ajax, this.siteSettings, this.element)
      );
```

`this.element` is always null because we explicitly set tagName to be `""` by default. It wasn't a problem before the commit I linked because we used to search the whole document if there was no element.

If we keep this default, the `cook-text` component will always fail to resolve uploads unless a tagName gets passed to it. IMO, this could lead to unexpected behavior. We should set a different default for this component or fallback to searching the whole document as we used to.

**Comment by CvX** [comment]
Maybe we should remove `tagName: ""` from the `cook-text` component? Now that I look at my PR (https://github.com/discourse/discourse/pull/10097) it makes no sense for it to be tagless by default because it won't work… 😬

**Comment by eviltrout** [comment]
If the assumption is we need a tag we should add it back.

**Comment by romanrizzi** [comment]
Removing the `tagName: ""` also does the trick. It also solves the issue of manually having to set it every time the component is called. It seems better than searching the whole document. What do you think, @eviltrout?

**Comment by eviltrout** [comment]
Yes that's what I was suggesting, we add the div back by removing `tagName`.

**Comment by romanrizzi** [comment]
Oh, I thought you were talking about searching the whole document by default. I'll do that then!

**Pull request merged**
