### PR TITLE
Fixes for vBulletin bulk importer

### PR DESCRIPTION
**Pull request by ldmosquera**
Small fixes after a vBulletin v4.2.4 migration

### CODE REVIEW

**Review by techAPJ — APPROVED** [review]
LGTM 👍🏼

**Comment by gschlager** [comment]
@ldmosquera Should we merge this?

**Comment by ldmosquera** [comment]
Sorry for the giant lapse; I had quite a few more related fixes and improvements which I never got around to tidy up for a PR; here they are.

---

The last 7 commits, from 28a27d80 and on, deduplicate users with the same email by doing rolling UserMerger runs, which can take a very long time and is thus paralellized with the Parallel gem (which I had to add as a dependency).

Not sure if it's worth it in general, but for a particular migration there were A TON of such duplicate users and the deduplication took some 4-5 hs even paralellized.

**Comment by ldmosquera** [comment]
Force push after rebasing to `main`

**Review by gschlager — APPROVED** [review]

**Pull request merged**
