### PR TITLE
Add three reports

### PR DESCRIPTION
**Pull request by michebs**
This PR adds the following reports requested on this [PM](https://dev.discourse.org/t/create-tl-changed-and-new-user-engagement-reports-in-the-admin-dashboard/51394/3):
* Top Users by likes received
* Top Users by likes received from a user with a lower trust level
* Top Users by likes received from a variety of people

### CODE REVIEW

**Comment by jjaffeux** [comment]
@michebs there are linting errors can you have a loop please?

**Comment by michebs** [comment]
> @michebs there are linting errors can you have a look please?

Done.

**Comment by michebs** [comment]
> @michebs there are linting errors can you have a look please?

done

**Review by Flink — COMMENTED** [review]
SQL queries look fine to me :+1: 
It would be best to have specs for these new reports IMO but I guess it’s your call @jjaffeux :wink:

**Comment by techAPJ** [comment]
Did you had a chance to look into this @michebs?

**Comment by michebs** [comment]
> Did you had a chance to look into this @michebs?

Added the other two tests based on the test you did. Thanks

**Review by techAPJ — APPROVED** [review]

**Pull request merged**
