### PR TITLE
DEV: Fixed n+1 query in ReviewableClaimedTopicsController

### PR DESCRIPTION
**Pull request by jdmartinez1062**
**Context**
While checking for issues in the reviewables claiming process I came across this N+1 query executed by this piece of code `reviewable.log_history(:claimed, current_user)` that ends up calling `reviewable_histories.create!` on each reviewable. Previously when this was run we got these SQL queries to the DB:
```
Reviewable Load (0.8ms)  SELECT "reviewables".* FROM "reviewables" WHERE "reviewables"."topic_id" = 11 ORDER BY "reviewables"."id" ASC LIMIT 1000
  TRANSACTION (0.7ms)  BEGIN
  ReviewableHistory Create (0.6ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (1, 3, 0, 4, '2024-05-14 19:24:13.088159', '2024-05-14 19:24:13.088159') RETURNING "id"
  TRANSACTION (3.0ms)  COMMIT
  TRANSACTION (1.2ms)  BEGIN
  ReviewableHistory Create (0.6ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (2, 3, 0, 4, '2024-05-14 19:24:13.095169', '2024-05-14 19:24:13.095169') RETURNING "id"
  TRANSACTION (4.6ms)  COMMIT
  TRANSACTION (0.9ms)  BEGIN
  ReviewableHistory Create (1.4ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (3, 3, 0, 4, '2024-05-14 19:24:13.106981', '2024-05-14 19:24:13.106981') RETURNING "id"
  TRANSACTION (2.8ms)  COMMIT
  TRANSACTION (0.6ms)  BEGIN
  ReviewableHistory Create (0.8ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (4, 3, 0, 4, '2024-05-14 19:24:13.114645', '2024-05-14 19:24:13.114645') RETURNING "id"
  TRANSACTION (3.3ms)  COMMIT
  TRANSACTION (0.7ms)  BEGIN
  ReviewableHistory Create (0.6ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (5, 3, 0, 4, '2024-05-14 19:24:13.123327', '2024-05-14 19:24:13.123327') RETURNING "id"
  TRANSACTION (3.4ms)  COMMIT
```

With the implemented changes, the SQL queries now look like 

```


TRANSACTION (0.6ms)  BEGIN
  Reviewable Load (0.9ms)  SELECT "reviewables".* FROM "reviewables" WHERE "reviewables"."topic_id" = 11 ORDER BY "reviewables"."id" ASC LIMIT 1000
  ReviewableHistory Load (0.8ms)  SELECT "reviewable_histories".* FROM "reviewable_histories" WHERE "reviewable_histories"."reviewable_id" IN (1, 2, 3, 4, 5)
  ReviewableHistory Create (1.5ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (1, 3, 0, 4, '2024-05-14 19:40:12.464250', '2024-05-14 19:40:12.464250') RETURNING "id"
  ReviewableHistory Create (3.5ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (2, 3, 0, 4, '2024-05-14 19:40:12.467009', '2024-05-14 19:40:12.467009') RETURNING "id"
  ReviewableHistory Create (0.6ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (3, 3, 0, 4, '2024-05-14 19:40:12.471937', '2024-05-14 19:40:12.471937') RETURNING "id"
  ReviewableHistory Create (0.6ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (4, 3, 0, 4, '2024-05-14 19:40:12.473400', '2024-05-14 19:40:12.473400') RETURNING "id"
  ReviewableHistory Create (0.6ms)  INSERT INTO "reviewable_histories" ("reviewable_id", "reviewable_history_type", "status", "created_by_id", "created_at", "updated_at") VALUES (5, 3, 0, 4, '2024-05-14 19:40:12.474885', '2024-05-14 19:40:12.474885') RETURNING "id"
  TRANSACTION (4.0ms)  COMMIT
```
**Solution**
  Wrap the method that calls the creation of ReviewablesHistories in a transaction to avoid making a query to the DB for each reviewable claimed

### CODE REVIEW

**Comment by jjaffeux** [comment]
@jdmartinez1062 Can you write a commit message and simplify the commit title please? Detail what you did to fix each N+1

**Comment by jjaffeux** [comment]
That feels incorrect to me to call it "Fixed N+1", we are not reducing the number of queries here, only avoiding a transaction for each call, or am I missing something?

**Comment by ZogStriP** [comment]
I agree with @jjaffeux - you are wrapping the queries in a transactions, not fixing an N+1 issue.

Otherwise, looks fine.

**Review by ZogStriP — APPROVED** [review]
Make sure you change commit message before merging 👍

**Comment by jjaffeux** [comment]
@jdmartinez1062 @featheredtoast what are we doing of this PR?

**Comment by ZogStriP** [comment]
ping @jdmartinez1062 / @featheredtoast

**Pull request closed without merging**
