### PR TITLE
DEV: remove user_profile events added for akismet

### PR DESCRIPTION
**Pull request by mrfinch**
cc @tgxworld

### CODE REVIEW

**Comment by tgxworld** [comment]
This will break code that is still subscribed to the existing event. For what you're working on, you can do the following.

```
on(:user_profile_updated) do |user|
  if self.bio_raw_previous_changed?
    # do stuff
  end
end
```

**Comment by mrfinch** [comment]
> This will break code that is still subscribed to the existing event. For what you're working on, you can do the following.
> 
> ```
> on(:user_profile_updated) do |user|
>   if self.bio_raw_previous_changed?
>     # do stuff
>   end
> end
> ```

@tgxworld , it is not used anywhere. I added it for Akismet plugin itself a week back.

**Comment by tgxworld** [comment]
In that case, we don’t need the events. You can just add callbacks directly in the plugin. There is no need to use callbacks to trigger events that is then consumed.

**Comment by mrfinch** [comment]
> In that case, we don’t need the events. You can just add callbacks directly in the plugin. There is no need to use callbacks to trigger events that is then consumed.

I didn't know I could do that directly. I have made changes accordingly in that PR: https://github.com/discourse/discourse-akismet/pull/19 , can you have a look if it's fine? I'm updating this PR to remove the user_profile events. @tgxworld

**Comment by ZogStriP** [comment]
Let's remove them since they're not useful.

**Pull request merged**
