### PR TITLE
Max password length

### PR DESCRIPTION
**Pull request by rimian**
This removes some redundancy when checking user passwords. :)

### CODE REVIEW

**Comment by ZogStriP** [comment]
Thanks @rimian but I'm not sure I see the point of this PR. You are basically testing if `>` works properly in Ruby...

**Comment by rimian** [comment]
Here's a good [example](https://github.com/choiceaustralia/discourse-donations/blob/master/app/controllers/discourse_donations/charges_controller.rb#L18) of why I refactored it. :)

I've removed the duplicated code that needs to be cut and pasted every time someone needs to check if the password is valid.

**Comment by ZogStriP** [comment]
I don't understand how "`User.password_too_long?`" is any better than "`password.size > User.max_password_length`"

**Comment by rimian** [comment]
It isn't any better on its own. But it does occur about 5 times in the code base which is bad code smell.

I refactored these duplicates because it breaks the DRY principle which is: "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system." What we have here is a single calculation being duplicated over and over. Refactor! :)

I found a reference which coincidentally comes from @coding-horror! Funny! [See Point 11](https://blog.codinghorror.com/a-pragmatic-quick-reference/).

I understand this isn't the ideal solution because there is other code that breaks DRY.

**Comment by SamSaffron** [comment]
I am so sorry, we have a policy on this this:

https://meta.discourse.org/t/discourse-development-contribution-guidelines/3823 

This is not making any functional change to our codebase.

**Pull request closed without merging**
