### PR TITLE
allow extra whitespace when asking discobot to perform a bot command

### PR DESCRIPTION
**Pull request by mayfieldiv**
https://meta.discourse.org/t/discobot-mentions-and-space-trimming/234568

### CODE REVIEW

**Comment by SamSaffron** [comment]
looks good, any reason this is a draft?

**Comment by SamSaffron** [comment]
oh I see, the test is not passing so the fix is not quite right :) looks like a more involved change.

**Comment by mayfieldiv** [comment]
> oh I see, the test is not passing so the fix is not quite right :) looks like a more involved change.

yeah my bad. the unit test included a newline character, but I hadn't noticed that gets cooked to a <br>, which I assume is not worth making the regex more complex to support.. so I just made the unit test validate multiple spaces like mentioned in the original request

**Comment by mayfieldiv** [comment]
the test failure looks like an unrelated flaky frontend test

**Pull request merged**
