### PR TITLE
FIX: faster delete_post_replies while moving posts

### PR DESCRIPTION
**Pull request by lis2**
Just before New Year, I was investigating moving post errors - https://meta.discourse.org/t/moving-posts-returns-502-bad-gateway/75654

I noticed that delete post replies query takes on large database around ~4s

image

I decided to check if there is a missing index or something similar, however, I could not find an easy solution.

My next step was to run EXPLAIN ANALYSE
```
EXPLAIN ANALYZE DELETE
        FROM post_replies pr USING moved_posts mp, posts p, posts r
        WHERE (pr.reply_post_id = mp.old_post_id OR pr.post_id = mp.old_post_id) AND
~         p.id = pr.post_id AND r.id = pr.reply_post_id AND p.topic_id <> r.topic_id;
 Delete on post_replies pr  (cost=3863135.12..7472915.92 rows=159479286 width=24) (actual time=7352.193..7352.193 rows=0 loops=1)
   ->  Merge Join  (cost=3863135.12..7472915.92 rows=159479286 width=24) (actual time=7352.192..7352.192 rows=0 loops=1)
         Merge Cond: (pr.post_id = ((~ p.id)))
         Join Filter: ((p.topic_id <> r.topic_id))
         ->  Sort  (cost=1989220.41..1990142.92 rows=369005 width=34) (actual time=2463.458..2463.458 rows=1 loops=1)
               Sort Key: pr.post_id
               Sort Method: quicksort  Memory: 25kB
               ->  Hash Join  (cost=914786.76..1945009.34 rows=369005 width=34) (actual time=2443.342..2463.453 rows=1 loops=1)
                     Hash Cond: (pr.reply_post_id = r.id)
                     ->  Nested Loop  (cost=15.36..983736.31 rows=369005 width=20) (actual time=0.013..0.015 rows=1 loops=1)
                           ->  Seq Scan on moved_posts mp  (cost=0.00..19.70 rows=970 width=10) (actual time=0.003..0.003 rows=1 loops=1)
                           ->  Bitmap Heap Scan on post_replies pr  (cost=15.36..1010.34 rows=380 width=14) (actual time=0.009..0.010 rows=1 loops=1)
                                 Recheck Cond: ((reply_post_id = mp.old_post_id) OR (post_id = mp.old_post_id))
                                 Heap Blocks: exact=1
                                 ->  BitmapOr  (cost=15.36..15.36 rows=380 width=0) (actual time=0.007..0.007 rows=0 loops=1)
                                       ->  Bitmap Index Scan on index_post_replies_on_reply_post_id  (cost=0.00..4.33 rows=1 width=0) (actual time=0.004..0.004 rows=0 loops=1)
                                             Index Cond: (reply_post_id = mp.old_post_id)
                                       ->  Bitmap Index Scan on index_post_replies_on_post_id  (cost=0.00..10.84 rows=379 width=0) (actual time=0.002..0.002 rows=1 loops=1)
                                             Index Cond: (post_id = mp.old_post_id)
                     ->  Hash  (cost=785656.40..785656.40 rows=7032640 width=22) (actual time=2430.081..2430.081 rows=6993842 loops=1)
                           Buckets: 65536  Batches: 128  Memory Usage: 3493kB
                           ->  Seq Scan on posts r  (cost=0.00..785656.40 rows=7032640 width=22) (actual time=0.036..1581.054 rows=6993842 loops=1)
         ->  Materialize  (cost=1873914.71..1909077.91 rows=7032640 width=22) (actual time=3559.089..4474.844 rows=6993842 loops=1)
               ->  Sort  (cost=1873914.71..1891496.31 rows=7032640 width=22) (actual time=3559.086..4099.536 rows=6993842 loops=1)
                     Sort Key: ((~ p.id))
                     Sort Method: external merge  Disk: 260080kB
                     ->  Seq Scan on posts p  (cost=0.00..785656.40 rows=7032640 width=22) (actual time=0.032..1504.690 rows=6993842 loops=1)
 Planning time: 0.349 ms
 Execution time: 7370.900 ms
```

I think that the biggest problem in that query is that 2 joins to the posts table which is usually very big (posts p and posts r).

I started thinking if it has to be done by that big SQL, most of the posts don't have hundreds of replies. So I decided to try a simplified approach to get potential post replies to delete and then make additional queries to decide if they should be deleted.

```
def delete_post_replies
  post_replies = ActiveRecord::Base.connection.execute("SELECT post_id, reply_post_id FROM post_replies pr INNER JOIN moved_posts mp ON (pr.reply_post_id = mp.old_post_id OR pr.post_id = mp.old_post_id)")
  post_replies.each do |post_reply|
    post1 = Post.find_by(id: post_reply['post_id'])
    post2 = Post.find_by(id: post_reply['reply_post_id'])
    next if !post1 || !post2
    PostReply.delete_by(post_id: post_reply['post_id'], reply_post_id: post_reply['reply_post_id']) if post1.topic_id != post2.topic_id
  end
end
```

Of course, the big query is gone now but it doesn't mean that code is actually faster so I decided to run a simple benchmark like:

```
t = Time.now
delete_post_replies
puts "EXECUTION TIME: #{Time.now - t}"
```

And with SQL query we got EXECUTION TIME: 1.9503399
and with smaller queries EXECUTION TIME: 0.0016596

I am not sure if that is a better approach, I decided to create draft PR, to start a discussion what do you think about that.

### CODE REVIEW

**Comment by ZogStriP** [comment]
> And with SQL query we got EXECUTION TIME: 1.9503399
> and with smaller queries EXECUTION TIME: 0.0016596

**Comment by gschlager** [comment]
I'm seeing different results with the original SQL:

```
Delete on post_replies pr  (cost=6.59..20462.62 rows=2254 width=24) (actual time=2.580..2.580 rows=0 loops=1)
  ->  Nested Loop  (cost=6.59..20462.62 rows=2254 width=24) (actual time=0.086..2.557 rows=4 loops=1)
        Join Filter: (p.topic_id <> r.topic_id)
        Rows Removed by Join Filter: 328
        ->  Nested Loop  (cost=6.16..16845.77 rows=2254 width=26) (actual time=0.020..1.886 rows=332 loops=1)
              ->  Nested Loop  (cost=5.74..13257.09 rows=2254 width=20) (actual time=0.016..1.361 rows=332 loops=1)
                    ->  Seq Scan on moved_posts mp  (cost=0.00..19.70 rows=970 width=10) (actual time=0.002..0.028 rows=263 loops=1)
                    ->  Bitmap Heap Scan on post_replies pr  (cost=5.74..13.63 rows=2 width=14) (actual time=0.004..0.005 rows=1 loops=263)
                          Recheck Cond: ((reply_post_id = mp.old_post_id) OR (post_id = mp.old_post_id))
                          Heap Blocks: exact=278
                          ->  BitmapOr  (cost=5.74..5.74 rows=2 width=0) (actual time=0.004..0.004 rows=0 loops=263)
                                ->  Bitmap Index Scan on index_post_replies_on_reply_post_id  (cost=0.00..2.87 rows=1 width=0) (actual time=0.001..0.001 rows=1 loops=263)
                                      Index Cond: (reply_post_id = mp.old_post_id)
                                ->  Bitmap Index Scan on index_post_replies_on_post_id_and_reply_post_id  (cost=0.00..2.87 rows=1 width=0) (actual time=0.002..0.002 rows=1 loops=263)
                                      Index Cond: (post_id = mp.old_post_id)
              ->  Index Scan using posts_pkey on posts p  (cost=0.42..1.59 rows=1 width=14) (actual time=0.001..0.001 rows=1 loops=332)
                    Index Cond: (id = pr.post_id)
        ->  Index Scan using posts_pkey on posts r  (cost=0.42..1.59 rows=1 width=14) (actual time=0.001..0.002 rows=1 loops=332)
              Index Cond: (id = pr.reply_post_id)
Planning Time: 0.305 ms
Execution Time: 2.600 ms
```

Output from `Benchmark.measure` for `delete_post_replies`:
```
  0.002667   0.000000   0.002667 (  0.002623)
```

Note: I've been testing it on PostgreSQL 11, with a database containing 571095 posts and after running `VACUUM ANALYZE`.

When I'm running your proposed code, I'm seeing much higher numbers from `Benchmark.measure`:
```
  1.312873   0.072397   1.385270 (  1.356314)
```

How large was the database you tested this on? How many posts?
I'll give it another try on my laptop with PostgreSQL 10 and see if that makes a difference in the explain plan.

**Comment by gschlager** [comment]
Okay, here's the result with the same, large database with PostgreSQL 10 on my much slower laptop:

```
Delete on post_replies pr  (cost=6.59..20284.63 rows=2242 width=24) (actual time=2.937..2.937 rows=0 loops=1)
  ->  Nested Loop  (cost=6.59..20284.63 rows=2242 width=24) (actual time=0.144..2.923 rows=4 loops=1)
        Join Filter: (p.topic_id <> r.topic_id)
        Rows Removed by Join Filter: 328
        ->  Nested Loop  (cost=6.16..16756.78 rows=2253 width=26) (actual time=0.034..2.046 rows=332 loops=1)
              ->  Nested Loop  (cost=5.74..13257.09 rows=2253 width=20) (actual time=0.026..1.435 rows=332 loops=1)
                    ->  Seq Scan on moved_posts mp  (cost=0.00..19.70 rows=970 width=10) (actual time=0.006..0.046 rows=263 loops=1)
                    ->  Bitmap Heap Scan on post_replies pr  (cost=5.74..13.63 rows=2 width=14) (actual time=0.004..0.005 rows=1 loops=263)
                          Recheck Cond: ((reply_post_id = mp.old_post_id) OR (post_id = mp.old_post_id))
                          Heap Blocks: exact=278
                          ->  BitmapOr  (cost=5.74..5.74 rows=2 width=0) (actual time=0.004..0.004 rows=0 loops=263)
                                ->  Bitmap Index Scan on index_post_replies_on_reply_post_id  (cost=0.00..2.87 rows=1 width=0) (actual time=0.002..0.002 rows=1 loops=263)
                                      Index Cond: (reply_post_id = mp.old_post_id)
                                ->  Bitmap Index Scan on index_post_replies_on_post_id_and_reply_post_id  (cost=0.00..2.87 rows=1 width=0) (actual time=0.002..0.002 rows=1 loops=263)
                                      Index Cond: (post_id = mp.old_post_id)
              ->  Index Scan using posts_pkey on posts p  (cost=0.42..1.55 rows=1 width=14) (actual time=0.002..0.002 rows=1 loops=332)
                    Index Cond: (id = pr.post_id)
        ->  Index Scan using posts_pkey on posts r  (cost=0.42..1.55 rows=1 width=14) (actual time=0.002..0.002 rows=1 loops=332)
              Index Cond: (id = pr.reply_post_id)
Planning time: 0.294 ms
Execution time: 2.974 ms
```

And the output from `Benchmark.measure`:
```
  0.000000   0.004000   0.004000 (  0.007198)
```

The explain plan looks the same on first glance and I didn't even run `VACUUM`.

**I don't think we should merge this PR.**

**Comment by coding-horror** [comment]
Ok let’s close it out then.

**Pull request closed without merging**
