### PR TITLE
DEV: New s3_private_bucket_policy site setting flag

### PR DESCRIPTION
**Pull request by varuncjain**
Introduce new site setting for specifying if S3 bucket policy blocks all public access

### CODE REVIEW

**Comment by xfalcox** [comment]
Hey @varuncjain can you please explain the need for this at https://meta.discourse.org/t/s3-storage-with-no-public-access/251560/6?u=falco ?

**Comment by varuncjain** [comment]
> 
Hi @xfalcox , I have added the comment to our discussion. Is there someway we can link this PR to the discussion?

**Comment by jjaffeux** [comment]
@varuncjain thanks for taking the time to make this PR, sadly we don't want to support this ATM.

**Comment by denysvitali** [comment]
> @varuncjain thanks for taking the time to make this PR, sadly we don't want to support this ATM.

Any particular reason for that?

**Comment by jjaffeux** [comment]
> > @varuncjain thanks for taking the time to make this PR, sadly we don't want to support this ATM.
> 
> Any particular reason for that?

Doesn't seem necessary at this point, we need more reasons to think a significant number of people would need this setting.

**Comment by varuncjain** [comment]
@jjaffeux the change should be non intrusive for any existing installations, if and when upgraded, as it is disabled by default. What would it take to reconsider this rejection?

**Pull request closed without merging**
