### PR TITLE
A11Y: Focus last viewed topic in topic lists (take 3)

### PR DESCRIPTION
**Pull request by OsamaSayegh**
Another attempt at fixing https://meta.discourse.org/t/discourse-with-a-screen-reader/178105/88?u=osama. Previous PR (reverted): #16240.

The problems with the previous PR were:

1. As you scrolled down a topics list, the first topic of every new batch of topics would receive focus and the indicator would show up.
2. Similar to 1, clicking the `See X new or updated topics` notice would also focus a random topic from the new topics that were just loaded.
3. Topics in the suggested topics list received focus too
4. Our custom focus indicator appeared on mobile, but it shouldn't.

### CODE REVIEW

**Comment by tgxworld** [comment]
Is there a client side acceptance test we can add for this or is there a video to demonstrate how the feature should work here? The code looks safe to me but I'm unable to tell how it should work :grin:

**Comment by OsamaSayegh** [comment]
There is this screenshot that I posted in #16240:



Basically when you click on a topic (let's say from latest) and then you navigate back, the blue border will appear on the topic and the topic row will be focused so that screen reader users can continue going down list from the topic they entered previously. Without the focus, they have to start from the top every time which is very frustrating.

Let me see if I can add a test for this, shouldn't be too difficult (famous last words? 😬)

**Comment by OsamaSayegh** [comment]
@tgxworld I've written a test for this, but since we're testing focus, the test will only pass if window that's running the test has focus. If for example you have browser on the side and your IDE window has focus, then the test will fail. I don't think we can add this test.

**Review by tgxworld — APPROVED** [review]

**Comment by tgxworld** [comment]
Thank you for the work here :+1:

**Comment by OsamaSayegh** [comment]
> I don't think we can add this test.

After discussing this with @tgxworld privately, we decided to go ahead and add the test because:

* it passes in CI
* and it tests an important accessibility fix

The only potential problem is that this test may become annoying for developers who run the full test suite in their browser. I don't think anyone actually runs the full test suite, but if there's then we can revisit this decision.

Thank you for the review @tgxworld!

<small>(will merge this in a few hours)</small>

**Pull request merged**
