### PR TITLE
REFACTOR: merges redirectTo implementation into one function

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by jjaffeux** [comment]
@eviltrout I'm especially interested in your opinion of my lib url changes.

I thought it was confusing to have two redirectTo function in the same file, with a slightly different implementation. Also the top one was hard to stub.

**Review by davidtaylorhq — APPROVED** [review]

**Comment by jjaffeux** [comment]
Sadly this is not very usable in the end, as it can't calls something that doesn't exist...

**Comment by davidtaylorhq** [comment]
The API might still be generally useful for other plugins, even if we can't use it in styleguide? Plus the refactoring of redirectTo is useful?

**Comment by jjaffeux** [comment]
Hmmmm... I'm kinda reluctant to keep things that don't have direct use case... but ok, let's see what robin thinks.

**Comment by jjaffeux** [comment]
@eviltrout I have updated the PR to only contain the lib/url change

**Review by davidtaylorhq — APPROVED** [review]

**Pull request merged**
