### PR TITLE
FIX: focus not moving to user menu or hamburger when opened from keyboard

### PR DESCRIPTION
**Pull request by htanata**
https://meta.discourse.org/t/focus-does-not-move-to-profile-menu-whjen-opened-from-keyboard/34925

I'm not familiar with Ember, so my approach might be wrong here.

### CODE REVIEW

**Comment by tgxworld** [comment]
Hello @htanata :smile:

Hmm @eviltrout is [porting our header](https://github.com/discourse/discourse/tree/vdom-header) to use a vdom implementation so perhaps things might have changed.

**Comment by eviltrout** [comment]
I haven't changed master, so it's likely an older regression. I've bookmarked this to make sure it continues to work in my new branch too.

**Comment by htanata** [comment]
Hey @tgxworld!

Looks like`app/assets/javascripts/discourse/controllers/header.js.es6` has changed in master. Should I fix this pull request?

**Comment by tgxworld** [comment]
Hey @htanata! Sorry for the delay in getting back.

The logic for the header has been refactored into a [widget](https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/widgets/header.js.es6). I think the user menu has been fixed but the hamburger menu is alittle broken

screenshot from 2016-05-17 17-18-27

**Comment by htanata** [comment]
Got it. I'll look into it when I have the time, but no promise. I'm closing this PR.

**Pull request closed without merging**
