### PR TITLE
FEATURE: Add a preview to the poll builder

### PR DESCRIPTION
**Pull request by CvX**
Closes https://meta.discourse.org/t/show-preview-in-poll-builder/117323/6

poll builder preview

Shout out to @pmusaraj for the recent poll [builder tweaks](https://github.com/discourse/discourse/commit/78500fb77017ae1defd9d1a77f26164493847624). Saved me some CSS tweaking! 😃

I've hardcoded both column widths, which isn't ideal, but modal's `max-width` means that it expands horizontally as you type (until it reaches that max width). As far as I know, there is no way to force a flex element to fill all the available space up to the `max-width`. I'm open to suggestions. 😉 

Oh, and the `poll-ui-builder.hbs` diff looks messy only because I've wrapped all the poll options in a `<div class="options">`.

### CODE REVIEW

**Comment by eviltrout** [comment]
(confirmed CLA was signed)

**Comment by eviltrout** [comment]
This looks quite good to me. Do you have any feedback @jjaffeux ?

**Comment by jjaffeux** [comment]
Also minor but one .poll-ui-builder-form is in a poll.scss file and ther other in poll-ui-builder.scss file, should we move all in poll.scss or have another poll-ui-builder.scss for mobile?.

**Comment by CvX** [comment]
Both are good points @jjaffeux, I've updated the PR. 🙂

**Comment by CvX** [comment]
Tests failed due to an unrelated flaky test. Forcing rebuild.

**Comment by eviltrout** [comment]
Thanks, merging it in.

**Pull request merged**
