### PR TITLE
Update rtl.scss

### PR DESCRIPTION
**Pull request by Qasem-h**
Rtl update
This work 100%fix

### CODE REVIEW

**Comment by Qasem-h** [comment]
Screenshot:https://meta.discourse.org/t/update-rtl-support-for-discourse/27335

**Comment by Qasem-h** [comment]
@ZogStriP cods have problems ?

**Comment by SamSaffron** [comment]
give us time to review your PRs please.

**Comment by SamSaffron** [comment]
I do not think this is needed anymore

**Pull request closed without merging**
