### PR TITLE
FIX: stop downloading images from post processor

### PR DESCRIPTION
**Pull request by SamSaffron**
Previously we would unconditionally fetch all images via HTTP to grab
original sizing from cooked post processor.

This unconditionally fails for secure uploads leading to internal edge cases

PR is not quite done, I want to add a test here...

### CODE REVIEW

**Comment by SamSaffron** [comment]
kind of hoping a test will fail :) lets see...

**Comment by martin-brennan** [comment]
> This unconditionally fails for secure uploads leading to internal edge cases

Shouldn't the secure upload request work because of this?

https://github.com/discourse/discourse/blob/b3abf8f0453e825989fc425b0cd3c3755268fcb0/lib/cooked_processor_mixin.rb#L178-L182

I added that here https://github.com/discourse/discourse/commit/4646a38ae6595c97dc3736dd67ec2c1edd72de93 . Maybe I am just misunderstanding the problem?

**Review by martin-brennan — APPROVED** [review]
The changes you made look good, especially the mock changes. I am still not seeing how secure upload URLs would unconditionally fail though.

**Comment by SamSaffron** [comment]
Yeah I am confused about the failure but have a repro... when using graphviz on local and setting to non-svg mode I was seeing stuff onebox just fine on local but it was broken on dev. When I wrote a test for graphviz I noticed the call in cooked post processor was reaching out to fastimage, notice how there were 2 spots I patched.

**Pull request merged**
