### PR TITLE
DEV: replaces unecessary (action (mut .*)) by (mut .*)

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Review by eviltrout — COMMENTED** [review]
I like it but it looks like there are failures.

**Comment by jjaffeux** [comment]
@eviltrout should be good now

**Comment by CvX** [comment]
@jjaffeux do you know why `fn` is required in some cases?

**Comment by jjaffeux** [comment]
> @jjaffeux do you know why `fn` is required in some cases?

Yes it's generally due to this kind of cases or similar: https://github.com/discourse/discourse/blob/master/app/assets/javascripts/select-kit/addon/components/icon-picker.js#L96

What happens here is that mut gives us a mutable cell, not a function, so we can't use it as a function, I could do some type checking or something... but I think this is fine like this, also I should get rid of these legacy hacks some day.

**Review by eviltrout — APPROVED** [review]

**Pull request merged**
