### PR TITLE
UX: Remove Active cursor from dead button

### PR DESCRIPTION
**Pull request by darkpixlz**
CONTEXT:
https://meta.discourse.org/t/suggested-topics-activity-column-sort-clickable-no-action/236632

There is a broken link or dead button in the Suggested Topics list, this removed the clickable cursor.
Before:
image
After:
image

### CODE REVIEW

**Review by pmusaraj — CHANGES_REQUESTED** [review]
Thanks for this @darkpixlz and sorry for the delay. 

From a quick inspection of this element, it looks like the style for it is set here: 

https://github.com/discourse/discourse/blob/main/app/assets/stylesheets/desktop/topic-list.scss#L124-L133 

Can you think of a reason why we shouldn't simply remove `span { cursor: pointer }` there?

**Comment by darkpixlz** [comment]
We can definitely remove it there, I will fix when I'm out of class.

**Comment by pmusaraj** [comment]
Awesome, thanks @darkpixlz

**Comment by darkpixlz** [comment]
@pmusaraj Fixed in a different pull
https://github.com/discourse/discourse/pull/18244

**Pull request closed without merging**
