### PR TITLE
Add pluralization rule to fr

### PR DESCRIPTION
**Pull request by Qasem-h**
It adds a pluralization rule to french

### CODE REVIEW

**Comment by SamSaffron** [comment]
why do we need this cc @ZogStriP  ?

**Comment by Qasem-h** [comment]
It adds a pluralization rule to fr.js.erb. The rule always returns 'other'. This is because the fr translation files do not use the 'one' key for pluralization.
french does not distinguish between the singular and plural forms
of nouns in the same way as English does. For numbered elements,
always return the 'other' key from the translation file.

**Comment by ZogStriP** [comment]
> french does not distinguish between the singular and plural forms

Yeah? Where did you get that from? As a French, I'm pretty sure we do.

**Comment by Qasem-h** [comment]
@ZogStriP some one reported this in forum , franch translate is 99% but not works some strings in it

**Comment by ZogStriP** [comment]
so?

**Comment by Qasem-h** [comment]
So i think need this for fixing it

**Pull request closed without merging**
