### PR TITLE
UX: align modals to top and full width on mobile

### PR DESCRIPTION
**Pull request by jjaffeux**
Discourse Meta - The Official Support Forum for Discourse

### CODE REVIEW

**Comment by jjaffeux** [comment]
@awesomerobot how do you feel about this ?

**Comment by CvX** [comment]
Hm, not sure about this one. It reduces reachability of the UI for no upside. (other than a bit of visual alignment?)

**Comment by jjaffeux** [comment]
At the very least I think the width makes sense.

It's very annoying to have all modals with various widths.

**Comment by pmusaraj** [comment]
I think modals look better center-aligned, both vertically and horizontally. It would be good to have uniform widths, but I would prefer at least some left/right margin.

**Comment by jjaffeux** [comment]
Ok Ok :p I will rethink this

**Pull request closed without merging**
