### PR TITLE
FIX: use discourse route_for function to check url route

### PR DESCRIPTION
**Pull request by mrfinch**
it takes care if there is a relative url root

https://meta.discourse.org/t/unable-to-grant-custom-badge-for-non-empty-reason-field/82299

### CODE REVIEW

**Comment by ZogStriP** [comment]
Thanks. Can you add a test as well?

**Comment by mrfinch** [comment]
> Thanks. Can you add a test as well?

I have added the test-case. You can review now. Thanks

**Comment by mrfinch** [comment]
Bump :bowing_man:

**Comment by tgxworld** [comment]
Merged with some slight changes in https://github.com/discourse/discourse/commit/99856478d6d890000379282c8d2cac7b4bf19101

**Comment by tgxworld** [comment]
Thank you @mrfinch

**Pull request closed without merging**
