### PR TITLE
DEV: Add plugin API for customizing user menu items

### PR DESCRIPTION
**Pull request by OsamaSayegh**

### CODE REVIEW

**Comment by OsamaSayegh** [comment]
@tgxworld I'm curious to hear your thoughts on these APIs. I've designed them with discourse-encrypt's use case in mind, but I've tried to make them as generic as possible so that they can potentially used by other plugins with similar use cases. See https://github.com/discourse/discourse-encrypt/pull/214.

**Comment by tgxworld** [comment]
Just looking at the specific case for encrypt, I do wonder if the API for changing how a topic title is displayed should be exposed as an API because I imagine that de-crypting the topic title is going to useful in alot more spots than just the user menu. Instead, core exposes a `api.addopicTitleProcessor` of some sort and anywhere we need to render a topic title we will use a helper like `processedTopicTitle(topicTitle)`.

**Comment by SamSaffron** [comment]
cc @davidtaylorhq 

Yeah I am torn here as well, the API is somewhat complex. 

I like the idea of `api.addTopicTitleProcessor` but there are a few complexities here.

1. We need more than the title we need context (full notification class, full topic class), cause the data is there. 
2. We need to pass in an `async` function, and handling rendering with async is super hard for core (render blank, wait for promise, render thing) 

At a minimum is there a way just to have 1 api method here? the list processor is very hard to understand.

**Comment by OsamaSayegh** [comment]
So something like this?

```
api.addTopicTitleProcessor((originalTitle, item) => {
  if (item.encrypted_title && item.topic_key && item.topic_id) {
    return decrypt(...);
  } else {
    return originalTitle;
  }
});
```

It could work, but it's also a bit tricky to make it a generic API that works everywhere because the `item` object could be anything (e.g. notification, bookmark, reviewable, assign etc.) and the encrypt would have to do some guesswork to figure out what it's working with. For example, when we're dealing with the messages list in the user menu, the `item` is a topic object and the plugin will need to use `item.id` instead of `item.topic_id`.

**Comment by SamSaffron** [comment]
> (e.g. notification, bookmark, reviewable, assign etc.) 

I guess the upside though is that the entire hack is isolated to 1 method, so it will be easier to reason about?  How do you handle the async nature of things though?

**Comment by SamSaffron** [comment]
also ... translate may want to lean on this longer term ... eg translating topic titles in a list is very similar to decrypting a list.

**Comment by tgxworld** [comment]
Instead of relying on an object, we can just pass in the required arguments in order for us to process the topic title because as you've rightly pointed out, trying to figure out what object we're working with is going to be a nightmare. Instead the API needs to enforce that interface. So something like `processedTopicTitle(topicTitle, topicId, etc.. etc...)` which is then passed to the processor which is registered.

**Comment by tgxworld** [comment]
> also ... translate may want to lean on this longer term ... eg translating topic titles in a list is very similar to decrypting a list and also async.

Ahh the stars are lining up because we currently have a PR to add support for translating the topic title: also ... translate may want to lean on this longer term ... eg translating topic titles in a list is very similar to decrypting a list and also async.

**Comment by SamSaffron** [comment]
> So something like processedTopicTitle(topicTitle, topicId, etc.. etc...)

I don't think we can do this, cause core has no clue what the plugin needs, it could be properties it never heard about. I think opaque context is the best we can do here and have the plugin do the fishing. Give up if the fishing expedition fails.

**Comment by OsamaSayegh** [comment]
> At a minimum is there a way just to have 1 api method here? the list processor is very hard to understand.

> How do you handle the async nature of things though?

This is why I've added the "processor" API. I tried very hard to make this a single API, but I couldn't due to the async nature of the plugin. The plugin uses the processor API to return a promise that resolves when all the encrypted titles in the list are decrypted, and then rendering of the list begins. The user sees a loading spinner until everything is decrypted.

**Comment by tgxworld** [comment]
> I don't think we can do this, cause core has no clue what the plugin needs, it could be properties it never heard about. I think opaque context is the best we can do here and have the plugin do the fishing. Give up if the fishing expedition fails.

Another way is to register the additional context in core when registering the processor. Plugin has to specific the type of object and the additional context it needs core to fish out.

**Comment by davidtaylorhq** [comment]
IMO the best thing would be for Encrypt to make its transformations at model load time (which is already a promise), rather than doing it at render time. The rest of the JS app would just see a regular topic. That would solve a huge number of bugs that Encrypt has at the moment.

**Comment by SamSaffron** [comment]
It would have to plug a lot of models though? We would need a ton of APIs here? 

Plus deferring here has some advantages, you can show "this thing is encrypted" on the screen for a split second prior to showing the decrypted thing. 

With translate it is even more pronounced.

**Comment by OsamaSayegh** [comment]
> Encrypt to make its transformations at model load time (which is already a promise), rather than doing it at render time.

I think that's kind of what I'm doing right now, no? In pseudocode, this is what happens when the user opens the menu:

```
ajax("<some_path>").then((items) => runPLuginProcessors(items))
```

`runPLuginProcessors` performs all the decrypting that the plugin needs to do and only when that's finished does rendering of the items begin.

> Another way is to register the additional context in core when registering the processor. Plugin has to specific the type of object and the additional context it needs core to fish out.

So something like this:

```
api.registerTopicTitleDecoratorContext(<type>, <list_of_attrs>);

api.registerTopicTitleDecoratorContext("bookmark", ["id", "topic_key", "encrypted_title"]);
```

And then the API `addTopicTitleProcessor` is given the type and if it's `bookmark` the plugin can safely assume the item object has the `id`, `topic_key`, `encrypted_title` attributes? I think that could work, but I think it also shares the same disadvantages of the the APIs in this PR (you have to do something for every type, some people may find it hard to understand the API)

**Comment by davidtaylorhq** [comment]
> @SamSaffron ~ It would have to plug a lot of models though? We would need a ton of APIs here?

Yeah I suppose so - but we're gonna need a ton of APIs anyway to handle all the places encrypt is currently monkey-patching rendering.

> @SamSaffron ~ deferring here has some advantages, you can show "this thing is encrypted" on the screen for a split second prior to showing the decrypted thing.

That's how encrypt used to work, but the jumpy UX was very painful (internal topic `/t/30681`)

> @OsamaSayegh I think that's kind of what I'm doing right now, no? 

Right, I see 👌  The 'processor' API is indeed the kind of thing I was thinking of. I see this PR also introduces a custom Renderer API - is that required for discourse-encrypt as well?

I was imagining the the Processor API could be part of the `Notification` model. TBH, the AJAX call should probably be happening in a static method on the Model as well?

Then we could introduce a generic "TransformModel" API which `Notification`, `Bookmark`, `Topic`, `Post`, etc. could hook into. Kinda like a 'middleware' for loading models. So plugins would be able to do something like this:

```javascript
api.registerModelTransformer("notification", async (notification) => {
  if(notification.encrypted_title){
    notification.title = await decryptTitle(notification.encryptedTitle);
  }
  return notification;
});
```

**Comment by SamSaffron** [comment]
I am supportive of api.registerModelTransformer but prefer it takes in a list vs a single item , it is more efficient and most cases have a list going 

why don’t we just start there and only implement the parts needed for notifications for the first iteration?

**Comment by OsamaSayegh** [comment]
I like the model transformer idea! I think this is the full picture of how it will work:

1. We create a model for every type that we want to plugin transformations to apply to

2. Each model has 2 async static methods*:

   * A `create` method that returns a instance of the model will all plugin transformations applied (this needs to be async because plugin transformations can be async)
   * A `fetch` method that fetches an array of items and returns an array of model instances for each item (each instance is created using the `create` method)

3. When the user menu is opened, we call the `fetch` method of the appropriate model which will give us an array of model instances with plugin transformations already applied to them (and in case of the Encrypt plugin, the generic `fancy_title` will be replaced with the actual decrypted title of the message).

4. We don't need the `replaceUserMenuItemRenderer` API because the transformer can just mutate the model.

Does this sound in line with that you're thinking?

\* we need to split these methods into 2 because some menus display mixed content from 2 models (e.g. the bookmarks tab displays unread notification first and then fills up the rest of the menu with bookmarks).

**Comment by OsamaSayegh** [comment]
> why don’t we just start there and only implement the parts needed for notifications for the first iteration?

So for now we just apply the model transformation to the notifications list and do bookmarks, assigns etc. later?

**Comment by SamSaffron** [comment]
Yeah keeping the prs small has massive advantages, we can sort out the full user menu over a few prs

**Comment by OsamaSayegh** [comment]
Got it, happy to do notifications only in this PR.

**Comment by davidtaylorhq** [comment]
> We create a model for every type that we want to plugin transformations to apply to

We already have [`models/notification.js`](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/models/notification.js) and [`models/bookmark.js`](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/models/bookmark.js), so I think we can use those?

> A create method that returns a instance of the model will all plugin transformations applied (this needs to be async because plugin transformations can be async)
> A fetch method that fetches an array of items and returns an array of model instances for each item (each instance is created using the create method)

I was thinking that the transformations would be applied within the fetch method, leaving the existing `create` method unchanged.  That would also make it easier to apply @SamSaffron's suggestion of making the API list-based, rather than one-record-at-a-time.

Many of our models already have 'fetch'-like methods. For example, [`TopicList.find`](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/models/topic-list.js#L200-L203), so that might be a useful reference. I guess ideally, all this would be handled by the RestModel / adapter / store... but maybe that's a step too far for this PR. 🤔

**Comment by OsamaSayegh** [comment]
OK, since we're just doing notifications in this PR, we can apply the transformations within the fetch method.

I mentioned having a separate `create` method because in some lists, like the bookmarks list, the REST API endpoint that we fetch the items from returns 2 lists: one for unread bookmark reminder notifications and one for bookmarks:

https://github.com/discourse/discourse/blob/3b1a46ff37683d9e3f4c04a8801278d3ee382739/app/assets/javascripts/discourse/app/components/user-menu/bookmarks-list.js#L48-L69

The `data.notifications` in there is just a list of POJOs that needs to be converted to a list of model instances with transformations applied to them. To do that cleanly, we'd need to extract the logic that applies plugin transformations into a separate method that the static `find`/`fetch` method can use, and also any place we have a list of notifications that isn't fetched with the model's static `fetch`/`find` method.

Or maybe we can just do apply the transformations in a constructor (or the `init` method if the model isn't a native class)?

**Comment by davidtaylorhq** [comment]
Ah I see. Making a static async `applyTransformations` method makes sense, so that other places can apply it manually :+1:

I don't think we can do it in the constructor/init because it needs to be async 😢

**Comment by SamSaffron** [comment]
I just want to make sure you are not blocked here @OsamaSayegh , do you feel you have a simple path forward to restore part of the old functionality. 

I would say priority `#1` would be the messages tab, notifications is priority `#2` and you can use multiple PRs here.

**Comment by OsamaSayegh** [comment]
Nope, not blocked at all. I should have something to show here by the end of Wednesday.

**Pull request closed without merging**
