### PR TITLE
FIX: clean up cooked group bio when bio is removed

### PR DESCRIPTION
**Pull request by majakomel**
https://meta.discourse.org/t/group-bio-cant-be-deleted/119777

### CODE REVIEW

**Comment by tgxworld** [comment]
@majakomel We can clear the `bio_cooked` in a callback on save instead of doing it at run time all the time.

**Comment by SamSaffron** [comment]
@tgxworld I am confused `cook_bio` is called from `before_save`

merging this, looks good to me

**Comment by tgxworld** [comment]
O I thought this was the serializer, my bad. @SamSaffron Is there a way you determine when a test is required vs when it isn't?

**Comment by SamSaffron** [comment]
These days on local I just break code around where I made the change and
run the full test suite, then at least I can tell the code is covered

In this case we actually had a faulty spec that this fix corrected thus
broke the build

**Pull request merged**
