### PR TITLE
DEV: convert chat components to .gjs

### PR DESCRIPTION
**Pull request by chancancode**
image

https://github.com/discourse/discourse/assets/55829/f62eb075-6207-45de-8dbb-3627dca27150

This converts most of the components in chat to use `.gjs` with proper imports. This is designed to be reviewable commit-by-commit.

* The first commit pulls in https://github.com/embroider-build/embroider/pull/1632 because without it the server crashes a lot during these renames
* The second commit renames all of the refactored `.js` files into `.gjs` without changing their content. Some of these files are quite small – if we do the rename and inlining of the template in the same commit, Git may not recognize that as a rename as the resulting files are too different. This forces Git to track that as a move/rename, thus preserving the lineage/history.
* The subsequent commits convert one file at a time. It write the changes to both `.gjs` and the `.hbs` file. This is so that you can easily tell what actually changed in the template's content.
* The final commit removes the leftover `.hbs` files.

After review, we can probably squash the individual commits + the final cleanup commit if we want, but to keep the Git history in tact we will want to at least keep the rename commit separate.

This is converted by a custom codemod built off of what @Ignacemaes started in #24162. See: https://github.com/IgnaceMaes/ember-codemod-template-tag/pull/8 This can be further tweaked to convert components in the rest of the app.

It should be possible to convert most of the skipped files with some light refactoring in a forthcoming PR. This first batch is just those that can be converted mechanically without intervention.

```
Successfully converted 68 files:

- discourse/components/chat-channel-archive-status.hbs
- discourse/components/chat-channel-card.hbs
- discourse/components/chat-channel-leave-btn.hbs
- discourse/components/chat-channel-metadata.hbs
- discourse/components/chat-channel-preview-card.hbs
- discourse/components/chat-channel-status.hbs
- discourse/components/chat-channel-title.hbs
- discourse/components/chat-channel-unread-indicator.hbs
- discourse/components/chat-composer-dropdown.hbs
- discourse/components/chat-composer-message-details.hbs
- discourse/components/chat-composer-upload.hbs
- discourse/components/chat-drawer/channel.hbs
- discourse/components/chat-drawer/header.hbs
- discourse/components/chat-drawer/header/back-link.hbs
- discourse/components/chat-drawer/header/channel-title.hbs
- discourse/components/chat-drawer/header/close-button.hbs
- discourse/components/chat-drawer/header/full-page-button.hbs
- discourse/components/chat-drawer/header/left-actions.hbs
- discourse/components/chat-drawer/header/right-actions.hbs
- discourse/components/chat-drawer/header/toggle-expand-button.hbs
- discourse/components/chat-drawer/index.hbs
- discourse/components/chat-emoji-avatar.hbs
- discourse/components/chat-full-page-header.hbs
- discourse/components/chat-mention-warnings.hbs
- discourse/components/chat-message-in-reply-to-indicator.hbs
- discourse/components/chat-message-separator-date.hbs
- discourse/components/chat-message-separator-new.hbs
- discourse/components/chat-message-text.hbs
- discourse/components/chat-message-thread-indicator.hbs
- discourse/components/chat-notice.hbs
- discourse/components/chat-notices.hbs
- discourse/components/chat-replying-indicator.hbs
- discourse/components/chat-side-panel-resizer.hbs
- discourse/components/chat-side-panel.hbs
- discourse/components/chat-skeleton.hbs
- discourse/components/chat-upload-drop-zone.hbs
- discourse/components/chat-upload.hbs
- discourse/components/chat-user-display-name.hbs
- discourse/components/chat/admin/export-messages.hbs
- discourse/components/chat/composer/button.hbs
- discourse/components/chat/composer/separator.hbs
- discourse/components/chat/message-creator.hbs
- discourse/components/chat/message-creator/channel-row.hbs
- discourse/components/chat/message-creator/user-row.hbs
- discourse/components/chat/message-creator/user-selection.hbs
- discourse/components/chat/message/avatar.hbs
- discourse/components/chat/message/error.hbs
- discourse/components/chat/message/info.hbs
- discourse/components/chat/message/left-gutter.hbs
- discourse/components/chat/modal/archive-channel.hbs
- discourse/components/chat/modal/channel-summary.hbs
- discourse/components/chat/modal/delete-channel.hbs
- discourse/components/chat/modal/move-message-to-channel.hbs
- discourse/components/chat/modal/new-message.hbs
- discourse/components/chat/modal/thread-settings.hbs
- discourse/components/chat/modal/toggle-channel-status.hbs
- discourse/components/chat/notices/mention_without_membership.hbs
- discourse/components/chat/scroll-to-bottom-arrow.hbs
- discourse/components/chat/thread-list/item.hbs
- discourse/components/chat/thread-list/item/unread-indicator.hbs
- discourse/components/chat/thread/header-unread-indicator.hbs
- discourse/components/chat/thread/threads-list-button.hbs
- discourse/components/chat/user-card-button.hbs
- discourse/components/full-page-chat.hbs
- discourse/components/reviewable-chat-message.hbs
- discourse/components/styleguide/organisms/chat.hbs
- discourse/components/toggle-channel-membership-button.hbs
- discourse/connectors/user-preferences-nav/chat-preferences.hbs


Skipped 37 files:

- discourse/components/channels-list.hbs
  The template contains usage of the {{action}} keyword, but the JS side imports { action } from @ember/object. It would have shadowed the template keyword.
- discourse/components/chat-browse-view.hbs
  The template contains usage of the {{action}} keyword, but the JS side imports { action } from @ember/object. It would have shadowed the template keyword.
- discourse/components/chat-channel-chooser-header.hbs
  It appears to be a classic class, convert it to native class first!
- discourse/components/chat-channel-chooser-row.hbs
  It appears to be a classic class, convert it to native class first!
- discourse/components/chat-channel.hbs
  Identifier 'ChatMessage' has already been declared. (50:7)
- discourse/components/chat-composer-uploads.hbs
  It appears to be a classic class, convert it to native class first!
- discourse/components/chat-composer.hbs
  Command failed: yarn eslint --fix "/Users/godfrey/code/discourse/plugins/chat/assets/javascripts/discourse/components/chat-composer.gjs"
error Command failed with exit code 1.
- discourse/components/chat-drawer.hbs
  It appears to be a classic class, convert it to native class first!
- discourse/components/chat-emoji-picker.hbs
  The template contains usage of the {{action}} keyword, but the JS side imports { action } from @ember/object. It would have shadowed the template keyword.
- discourse/components/chat-message-collapser.hbs
  Failed to resolve lazy-video (Component)
- discourse/components/chat-thread.hbs
  Identifier 'ChatMessage' has already been declared. (41:7)
- discourse/components/chat-to-topic-selector.hbs
  It appears to be a classic class, convert it to native class first!
- discourse/components/chat/modal/create-channel.hbs
  The template contains usage of the {{action}} keyword, but the JS side imports { action } from @ember/object. It would have shadowed the template keyword.
- discourse/components/chat/modal/edit-channel-description.hbs
  The template contains usage of the {{action}} keyword, but the JS side imports { action } from @ember/object. It would have shadowed the template keyword.
- discourse/components/chat/modal/edit-channel-name.hbs
  The template contains usage of the {{action}} keyword, but the JS side imports { action } from @ember/object. It would have shadowed the template keyword.
- discourse/components/collapser.hbs
  It appears to be a classic class, convert it to native class first!
- discourse/components/styleguide/chat-composer-message-details.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-composer.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-header-icon.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-message.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-archive-channel.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-channel-summary.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-create-channel.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-delete-channel.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-edit-channel-description.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-edit-channel-name.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-move-message-to-channel.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-new-message.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-thread-settings.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-modal-toggle-channel-status.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/styleguide/chat-thread-list-item.hbs
  Failed to resolve styleguide-example (Component)
- discourse/components/user-menu/chat-notifications-list-empty-state.hbs
  cannot find class
- discourse/connectors/below-footer/chat-channel-message-emoji-picker-connector.hbs
  It does not appear to be a component!
- discourse/connectors/below-footer/chat-drawer-outlet.hbs
  It does not appear to be a component!
- discourse/connectors/below-footer/chat-message-actions-desktop-outlet.hbs
  It does not appear to be a component!
- discourse/connectors/below-footer/chat-message-actions-mobile-outlet.hbs
  It does not appear to be a component!
- discourse/connectors/user-card-below-message-button/chat-button.hbs
  It does not appear to be a component!
```

### CODE REVIEW

**Comment by chancancode** [comment]
oops. Sometimes the changes to the hbs files are missing because my script ran template-lint/prettier on the hbs file prior to the commit, but they don’t like those kind of camelcase naming conventions in standalone hbs files, and changed it right back 🙃

**Comment by chancancode** [comment]
Updated and rebased for https://github.com/discourse/discourse/pull/24189

**Comment by jjaffeux** [comment]
I would prefer to merge this next week, and you might have other conflicts tomorrow or friday.

That's awesome though 🚀

**Comment by chancancode** [comment]
Had to back out `chat/message-creator` for `{{component}}` usage, and updated the codemod to detect and reject that. Let's see if tests pass now 👀

**Comment by chancancode** [comment]
> I would prefer to merge this next week, and you might have other conflicts tomorrow or friday.

Pretty sure I can keep the pile of hacks working for at least one week :D

I can probably make it work with most of the code by then, maybe we just pick a day on the calendar to watch the codemod run and land a single giant commit across the codebase o_0

**Comment by chancancode** [comment]
Tests are passing now, so pretty sure I have fixed the problem in the codemod, should be good to run it again whenever

**Comment by jjaffeux** [comment]
> > I would prefer to merge this next week, and you might have other conflicts tomorrow or friday.
> 
> Pretty sure I can keep the pile of hacks working for at least one week :D
> 
> I can probably make it work with most of the code by then, maybe we just pick a day on the calendar to watch the codemod run and land a single giant commit across the codebase o_0

Yes Im fine with that, chat has a lot of tests too, so I'm not too afraid of breaking everything. And I will manually test your PR too. Let's try to aim for next tuesday if that's ok for you, I will warn you if there's some delay.

**Comment by jjaffeux** [comment]
This is good to rebase and review. Ping me when you are ready, and I will review/test it :+1:

**Comment by chancancode** [comment]
@jjaffeux just re-ran the codemod against the latest main branch!

```
Successfully converted 61 files:

- discourse/components/channels-list.hbs
- discourse/components/chat-channel-archive-status.hbs
- discourse/components/chat-channel-card.hbs
- discourse/components/chat-channel-leave-btn.hbs
- discourse/components/chat-channel-metadata.hbs
- discourse/components/chat-channel-preview-card.hbs
- discourse/components/chat-channel-status.hbs
- discourse/components/chat-channel-unread-indicator.hbs
- discourse/components/chat-composer-dropdown.hbs
- discourse/components/chat-composer-message-details.hbs
- discourse/components/chat-composer-upload.hbs
- discourse/components/chat-drawer/channel.hbs
- discourse/components/chat-drawer/header.hbs
- discourse/components/chat-drawer/header/back-link.hbs
- discourse/components/chat-drawer/header/channel-title.hbs
- discourse/components/chat-drawer/header/close-button.hbs
- discourse/components/chat-drawer/header/full-page-button.hbs
- discourse/components/chat-drawer/header/left-actions.hbs
- discourse/components/chat-drawer/header/right-actions.hbs
- discourse/components/chat-drawer/header/toggle-expand-button.hbs
- discourse/components/chat-drawer/index.hbs
- discourse/components/chat-emoji-avatar.hbs
- discourse/components/chat-mention-warnings.hbs
- discourse/components/chat-message-in-reply-to-indicator.hbs
- discourse/components/chat-message-separator-date.hbs
- discourse/components/chat-message-separator-new.hbs
- discourse/components/chat-message-text.hbs
- discourse/components/chat-message-thread-indicator.hbs
- discourse/components/chat-notice.hbs
- discourse/components/chat-notices.hbs
- discourse/components/chat-replying-indicator.hbs
- discourse/components/chat-side-panel-resizer.hbs
- discourse/components/chat-side-panel.hbs
- discourse/components/chat-skeleton.hbs
- discourse/components/chat-upload-drop-zone.hbs
- discourse/components/chat-upload.hbs
- discourse/components/chat-user-display-name.hbs
- discourse/components/chat/admin/export-messages.hbs
- discourse/components/chat/composer/button.hbs
- discourse/components/chat/composer/separator.hbs
- discourse/components/chat/message/avatar.hbs
- discourse/components/chat/message/error.hbs
- discourse/components/chat/message/info.hbs
- discourse/components/chat/message/left-gutter.hbs
- discourse/components/chat/modal/archive-channel.hbs
- discourse/components/chat/modal/channel-summary.hbs
- discourse/components/chat/modal/delete-channel.hbs
- discourse/components/chat/modal/edit-channel-name.hbs
- discourse/components/chat/modal/move-message-to-channel.hbs
- discourse/components/chat/modal/thread-settings.hbs
- discourse/components/chat/modal/toggle-channel-status.hbs
- discourse/components/chat/notices/mention_without_membership.hbs
- discourse/components/chat/scroll-to-bottom-arrow.hbs
- discourse/components/chat/thread-list/item.hbs
- discourse/components/chat/thread-list/item/unread-indicator.hbs
- discourse/components/chat/user-card-button.hbs
- discourse/components/full-page-chat.hbs
- discourse/components/reviewable-chat-message.hbs
- discourse/components/styleguide/organisms/chat.hbs
- discourse/components/toggle-channel-membership-button.hbs
- discourse/connectors/user-preferences-nav/chat-preferences.hbs

Skipped 35 files:

- It does not appear to be a component!
  - discourse/connectors/below-footer/chat-channel-message-emoji-picker-connector.hbs
  - discourse/connectors/below-footer/chat-drawer-outlet.hbs
  - discourse/connectors/below-footer/chat-message-actions-desktop-outlet.hbs
  - discourse/connectors/below-footer/chat-message-actions-mobile-outlet.hbs
  - discourse/connectors/user-card-below-message-button/chat-button.hbs
- It appears to be a classic class, convert it to native class first!
  - discourse/components/chat-channel-chooser-header.hbs
  - discourse/components/chat-channel-chooser-row.hbs
  - discourse/components/chat-composer-uploads.hbs
  - discourse/components/chat-drawer.hbs
  - discourse/components/chat-to-topic-selector.hbs
  - discourse/components/collapser.hbs
- Cannot find class
  - discourse/components/user-menu/chat-notifications-list-empty-state.hbs
- The template contains usage of the {{action}} keyword, but the JS side imports { action } from @ember/object. It would have shadowed the template keyword.
  - discourse/components/chat-browse-view.hbs
  - discourse/components/chat-emoji-picker.hbs
  - discourse/components/chat/modal/create-channel.hbs
  - discourse/components/chat/modal/edit-channel-description.hbs
- Failed to resolve styleguide-example (Component)
  - discourse/components/styleguide/chat-composer-message-details.hbs
  - discourse/components/styleguide/chat-composer.hbs
  - discourse/components/styleguide/chat-header-icon.hbs
  - discourse/components/styleguide/chat-message.hbs
  - discourse/components/styleguide/chat-modal-archive-channel.hbs
  - discourse/components/styleguide/chat-modal-channel-summary.hbs
  - discourse/components/styleguide/chat-modal-create-channel.hbs
  - discourse/components/styleguide/chat-modal-delete-channel.hbs
  - discourse/components/styleguide/chat-modal-edit-channel-description.hbs
  - discourse/components/styleguide/chat-modal-edit-channel-name.hbs
  - discourse/components/styleguide/chat-modal-move-message-to-channel.hbs
  - discourse/components/styleguide/chat-modal-new-message.hbs
  - discourse/components/styleguide/chat-modal-thread-settings.hbs
  - discourse/components/styleguide/chat-modal-toggle-channel-status.hbs
  - discourse/components/styleguide/chat-thread-list-item.hbs
- Failed to resolve lazy-video (Component)
  - discourse/components/chat-message-collapser.hbs
- Identifier 'ChatMessage' has already been declared. (51:7)
  - discourse/components/chat-channel.hbs
- Identifier 'ChatMessage' has already been declared. (41:7)
  - discourse/components/chat-thread.hbs
- Command failed: yarn eslint --fix "/Users/godfrey/code/discourse/plugins/chat/assets/javascripts/discourse/components/chat-composer.gjs"
error Command failed with exit code 1.
  - discourse/components/chat-composer.hbs
```

Some of these can be fixed easily with some modification to the pre-conversion code, but since this PR is big enough as it as, I think we should leave those for another time and just focus on the mechanically convertible ones here.

For the merging logistics, if we want to preserve the Git history lineage, we would want to ensure the first commit makes it into the main branch on its own, and everything else after that can be squashed. Otherwise, squashing the whole PR is fine too, I think on some smaller files Git would recognize it as a delete and add, rather than rename, so when, etc, `git blame`-ing or history diving in the future, that creates a bit of an inconvenience.

**Comment by jjaffeux** [comment]
Agreed on just getting the big PR out of the way ASAP, and we can look at remaining files after. Having this around for too long will just cause merging issues. Im looking at it right now

**Review by jjaffeux — APPROVED** [review]

**Pull request merged**
