### PR TITLE
DEV: use structured data in crawler-linkback-list for referencing only

### PR DESCRIPTION
**Pull request by rr-it**
This simplifies the crawler-linkback-list to only be a point of reference to the actual DiscussionForumPosting objects.

See "Summary page": https://developers.google.com/search/docs/advanced/structured-data/carousel?hl=en#summary-page
> [It] defines an ItemList, where each ListItem has only three properties: @type (set to ListItem), position (the position in the list), and url (the URL of a page with full details about that item).

### CODE REVIEW

**Comment by ZogStriP** [comment]
Thanks @rr-it 👍 

Would you mind adding a test as well to ensure we're properly formatting the structured data in the view?

**Comment by rr-it** [comment]
I don't see feasible unit tests here. It looks testable by integration test with a mocked topic-view only.
E.g. a test like https://github.com/discourse/discourse/pull/16013/commits/23d78894c4b1365f6296b30ecffba692f46ac1b0

**Comment by ZogStriP** [comment]
@nbianca can you take this one over the finish line?

**Comment by jjaffeux** [comment]
Fixed the conflict, and will merge it tomorrow.

**Review by jjaffeux — APPROVED** [review]

**Comment by jjaffeux** [comment]
@rr-it I just merged it, thanks

**Pull request merged**
