### PR TITLE
DEV: introduces {{concat-class}} helper

### PR DESCRIPTION
**Pull request by jjaffeux**
Usage:

```
<button class={{concat-class "foo" this.bar (if true "baz")}} />
```

### CODE REVIEW

**Comment by jjaffeux** [comment]
@CvX thoughts on this one too please? :p

**Comment by CvX** [comment]
In abstract I'd recommend composition of smaller helpers, e.g. `{{compact (concat "a" this.b @c)}}` but I guess this particular case is common enough that it justifies a dedicated helper. 😃 

Though regarding the name – can we think of any other places other than `class` attributes that could use this helper? If there are any, we'd have to go for a more generic name.

**Comment by jjaffeux** [comment]
I can't really think of anything else having so much use cases in the codebase.

**Review by CvX — APPROVED** [review]
Yeah, I looked at the places where `(concat`/`{{concat` is used and only `class=` fits the bill. 👍

**Pull request merged**
