### PR TITLE
Admin button "Change Timestamp" should read "Change Timestamp..."

### PR DESCRIPTION
**Pull request by chrisbeach**

### CODE REVIEW

**Comment by chrisbeach** [comment]
@jomaxro - apologies - this is a rogue commit in this PR due to my lack of git finesse! I'll revert that commit

**Comment by jomaxro** [comment]
No need to apolgize!  I like the original commit, I was just confused what the second one was.  Hopefully the Discourse team likes this change too!

**Comment by tgxworld** [comment]
Thanks for the PR :+1:  Could you remove the commits that are not relevant to the PR. 

Also, you'll only have to update `client.en.yml`. The changes for the other translations will be pulled it from Transifex

**Comment by chrisbeach** [comment]
Hi @tgxworld - thanks for the tip about Transifex. Makes it much easier! I will sort out the branch as soon as possible after work today, and get this PR into a clean state. Appreciate your patience with my rookie git skills :-)

**Comment by chrisbeach** [comment]
@tgxworld @jomaxro should be okay now I think

**Comment by chrisbeach** [comment]
@tgxworld @jomaxro  nope... broken it again... sorry  :-(

**Comment by jomaxro** [comment]
Git is a finicky thing if you don't fully understand it (which I certainly do not).  You may find it easier to make a new branch, push 1 commit with the en.yml change, then make a new PR.  Once that works close this one.

**Comment by chrisbeach** [comment]
I will create a new clean branch.

**Pull request closed without merging**
