### PR TITLE
FIX: use the latest version of `puppeteer-core` package to fix `page.click` issue

### PR DESCRIPTION
**Pull request by vinothkannans**
If we use `page.click` then it's randomly failing open the user card UI. So we're now using the `document.querySelector` to retrive the element and click it.

### CODE REVIEW

**Comment by tgxworld** [comment]
What is the root cause of why `page.click` is failing randomly? Our smoke test is meant to simulate what a user will try to do and this change is not reflecting what a user will normally do.

**Comment by vinothkannans** [comment]
@tgxworld the issue is happening only if we run the tests in headless mode. So, it doesn’t look like an issue from our side. I can see many similar reports about puppeteer’s click method on the web.

**Comment by tgxworld** [comment]
Hmm do you have the links to such reports? I’ll like to have a look because if a simple action like clicking something can be so unreliable in puppeteer, then I don’t think we should be using it.

**Comment by vinothkannans** [comment]
https://stackoverflow.com/a/73113570
https://github.com/puppeteer/puppeteer/issues/2959

@tgxworld here are some examples. Should we try updating the puppeteer to the latest version? I thought we can't do much here since this is only happens in "headless" mode.

**Comment by tgxworld** [comment]
Yup we can try updating puppeteer to the latest version to see if it fixes the problem. The solution being suggested is a work around and I don't think the workaround is the proper fix here. That would be admitting that puppeteer's click method is unreliable and if that is true, we shouldn't even be using puppeteer. That being said, I suspect something else is at play here. In most cases, puppeteer is clicking at a point in the page. Maybe the link is animating? Maybe try getting a screenshot of the page before we click?

**Comment by vinothkannans** [comment]
> Yup we can try updating puppeteer to the latest version

@tgxworld upgrading to the latest version fixes the `page.click` issue in my local environment.

**Review by tgxworld — APPROVED** [review]

**Comment by tgxworld** [comment]
O this is nice :+1:

**Pull request merged**
