### PR TITLE
DEV: Function to get baseUri from get-url helper

### PR DESCRIPTION
**Pull request by markvanlan**
@eviltrout This is so that I can get the subfolder path. I didn't want to export the variable, so that it cannot be set outside of the get-url file, so I wrote a get function.

### CODE REVIEW

**Comment by eviltrout** [comment]
Why do you need this though? So far other code has avoided it so I am curious.

**Comment by markvanlan** [comment]
@eviltrout This returns just the subfolder path, if one is present. It is useful to me in my Plugin Adventures :tm:, and seems generally useful. Not sure a cleaner way to get just the subfolder path otherwise!

**Comment by eviltrout** [comment]
You can call `get-url "/"` right?

**Comment by markvanlan** [comment]
@eviltrout :facepalm:

**Pull request closed without merging**
