### PR TITLE
DEV: Fix typo in `docker_test.rb` script

### PR DESCRIPTION
**Pull request by tgxworld**
Follow up to 9caba30d5c9adb81c11185e67b986d13545f5152

### CODE REVIEW

**Comment by tgxworld** [comment]
No tests cause I have no idea how we can test this.

**Review by ZogStriP — APPROVED** [review]

**Comment by tgxworld** [comment]
Thank you @ZogStriP :)

**Comment by jjaffeux** [comment]
> No tests cause I have no idea how we can test this.

honnest :D

**Comment by jjaffeux** [comment]
> No tests cause I have no idea how we can test this.

honnest :D

**Pull request merged**
