### PR TITLE
DEV: replaces huge generated emoji list by a simpler regex

### PR DESCRIPTION
**Pull request by jjaffeux**
Uses simpler emoji regex instead of a complex generated string of 50kb+ (we now site at around 15kb, which could probably be still improve in the future), this is also necessary as it's currently not possible to add more data to this string or it's causing crashes.

### CODE REVIEW

**Comment by jjaffeux** [comment]
@eviltrout @gschlager note that the commit is huge but, there's actually only few files relevant to review:
- app/assets/javascripts/pretty-text/addon/emoji.js
- lib/pretty_text/shims.js
- lib/tasks/emoji.rake

**Comment by CvX** [comment]
Regarding the failed test: I believe using only `\p{Emoji}` won't be enough.

Per unicode spec (see http://unicode.org/reports/tr51/#EBNF_and_Regex), a more exhaustive expression might be needed:

```js
"☺️😃👨‍🌾😜".match(/\p{Emoji}/gu)
// ["☺", "😃", "👨", "🌾", "😜"]

"☺️😃👨‍🌾😜".match(/\p{RI}\p{RI}|\p{Emoji}(\p{Emoji_Modifier}|\u{FE0F}\u{20E3}?|[\u{E0020}-\u{E007E}]+\u{E007F})?(\u{200D}\p{Emoji}(\p{Emoji_Modifier}|\u{FE0F}\u{20E3}?|[\u{E0020}-\u{E007E}]+\u{E007F})?)*/gu)
// ["☺️", "😃", "👨‍🌾", "😜"]
```

**Comment by jjaffeux** [comment]
> Regarding the failed test: I believe using only `\p{Emoji}` won't be enough.
> 
> Per unicode spec (see http://unicode.org/reports/tr51/#EBNF_and_Regex), a more exhaustive expression might be needed:
> 
> ```js
> "☺️😃👨‍🌾😜".match(/\p{Emoji}/gu)
> // ["☺", "😃", "👨", "🌾", "😜"]
> 
> "☺️😃👨‍🌾😜".match(/\p{RI}\p{RI}|\p{Emoji}(\p{Emoji_Modifier}|\u{FE0F}\u{20E3}?|[\u{E0020}-\u{E007E}]+\u{E007F})?(\u{200D}\p{Emoji}(\p{Emoji_Modifier}|\u{FE0F}\u{20E3}?|[\u{E0020}-\u{E007E}]+\u{E007F})?)*/gu)
> // ["☺️", "😃", "👨‍🌾", "😜"]
> ```

Yes I have seen the failure I think we will have to go for more complex indeed, not a big deal, still way simpler than what we had

**Comment by SamSaffron** [comment]
@jjaffeux where are we on this? has stuff drifted since this PR was made (do you need another emoji update)

**Comment by jjaffeux** [comment]
@SamSaffron there's multiple subjects at once now:

- we need to update how we match emojis as our current way is buggy and more importantly will crash if we add more emojis and is very slow and adds to the payload
- we need to drop joypixels set and replace it with open emoji
- we need to update to support new emojis, and things have changed a lot since I done it first and I would want to update the script to make all of this even easier in the future
- I would want to investigate using svgs for emojis

So yes lots of things going on, I'm currently investigating various things to try to split this in different tasks. We can close this one for now if you want.

**Comment by gschlager** [comment]
> I would want to investigate using svgs for emojis

:heart_eyes: :heart_eyes: :heart_eyes:

**Comment by SamSaffron** [comment]
can we do a new update @jjaffeux and merge this week ?

**Comment by jjaffeux** [comment]
I can try yes, this is really touchy so not 100% sure, bit will try

**Comment by jjaffeux** [comment]
@SamSaffron I will re-read this, do more checks and look at few places for improvements on Monday but it's almost done.

**Review by ZogStriP — APPROVED** [review]

**Comment by jjaffeux** [comment]
@SamSaffron I had quite a lot of things to adjust, I will merge it tomorrow morning first thing.

**Pull request merged**
