### PR TITLE
FIX: hidden was defined as static instead of relying on attribute

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Review by CvX — COMMENTED** [review]
If the parent component ([`composer-messages`](https://github.com/discourse/discourse/blob/ce686a008f97708099efbe9969d1a83f8b8950cf/app/assets/javascripts/discourse/app/components/composer-messages.js)) hides and shows itself, is this required at all?

**Comment by jjaffeux** [comment]
> If the parent component ([`composer-messages`](https://github.com/discourse/discourse/blob/ce686a008f97708099efbe9969d1a83f8b8950cf/app/assets/javascripts/discourse/app/components/composer-messages.js)) hides and shows itself, is this required at all?

ahah I was already changing this :p see last commit, I also changed other thing, because this intermediate action seems useless

**Comment by jjaffeux** [comment]
Hmmm I see that few themes are the closeMessage though... perspective and etiquette

**Comment by CvX** [comment]
+1 on deprecating the action 🙂

> is this required at all?

By "this" I meant the original reason of this PR - the `hidden` class. 😃 Is this component used anywhere outside the `composer-messages`? If not, it's already hidden whenever the parent component is hidden, right?

**Comment by jjaffeux** [comment]
> By "this" I meant the original reason of this PR - the `hidden` class. 😃 Is this component used anywhere outside the `composer-messages`? If not, it's already hidden whenever the parent component is hidden, right?

Yes right, let's just get rid of it too

**Review by CvX — APPROVED** [review]

**Pull request merged**
