### PR TITLE
FIX: Ensure images do not change height when loading is complete

### PR DESCRIPTION
**Pull request by davidtaylorhq**
Browsers automatically calculate an aspect ratio based on the width/height attributes of an `<img`. HOWEVER that aspect ratio only applies while the image is loading. Once loaded, it'll use the
image's actual dimensions. This can cause things to jump around after loading. For example:
 - if a user deliberately inserts false width/height
 - the image fails to load (404)
 - an optimised image is a few pixels different, due to a rounding when resizing

This decorator explicitly sets the `aspect-ratio` property so that things are consistent throughout the lifetime of all `<img` elements.

This may help to resolve https://meta.discourse.org/t/screen-jumping-around-on-mobile/223009

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
I think this fixes the problem @cvx described in #15678 (that had to be reverted due to side effects (#15815))

(meta ref for that issue: https://meta.discourse.org/t/216921)

**Review by pmusaraj — APPROVED** [review]
Looks good to me! 

Since this is fixing a fairly small issue, I am tempted to recommend not doing anything for older browsers that don't support the `aspect-ratio` property. Especially if it causes improperly scaled images following a window resize or a device rotation.

**Comment by davidtaylorhq** [comment]
> Since this is fixing a fairly small issue, I am tempted to recommend not doing anything for older browsers that don't support the aspect-ratio property

It may seem like a minor issue, but any jumping of height can have catastrophic consequences for our infinite-scrolling topics. For example, this report is for issues on an older iOS version: https://meta.discourse.org/t/screen-jumping-around-on-mobile/223009

**Comment by pmusaraj** [comment]
Fair enough, @davidtaylorhq, let's go with what you have which includes support for previous browser versions.

**Review by CvX — APPROVED** [review]

**Pull request merged**
