### PR TITLE
FIX: Update Nabble importer to use Email.Receiver new API

### PR DESCRIPTION
**Pull request by Mogztter**
Email.Receiver API changed in 30836573587079c5e663d7b3122957fc8c70dafe

### CODE REVIEW

**Comment by ZogStriP** [comment]
Thanks 👍

**Comment by Mogztter** [comment]
I'm glad to contribute to this *awesome* project :wink: 

I think `mbox` importer needs to be updated as well: https://github.com/discourse/discourse/blob/master/script/import_scripts/mbox.rb#L296

I would like to add specs on importer, do you have any recommandations/rules to follow ?

Thanks

**Comment by ZogStriP** [comment]
> I would like to add specs on importer, do you have any recommandations/rules to follow ?

Unfortunately, this is one of the area we're lacking tests. There are a [few](https://github.com/discourse/discourse/tree/master/script/import_scripts/socialcast) [importers](https://github.com/discourse/discourse/tree/master/script/import_scripts/quandora) which have tests. You can use them as inspiration if you want.

**Comment by mcwumbly** [comment]
@Mogztter while I've added some tests on the two importers I wrote, I'd be
happy to kick around ideas for different approaches. If you want to discuss
any of this is more detail, feel free to create a topic on meta.

**Pull request merged**
