### PR TITLE
FIX: Do not reset link counts upon rebake

### PR DESCRIPTION
**Pull request by davidtaylorhq**
This was an indentation mistake introduced in 44eba0b. Pretty understandable, considering we are indented 8 levels deep in this method. The first commit corrects the issue and adds a test, the second commit refactors the method to reduce complexity.

(Please use rebase & merge, not squash, so that we keep the two commits separate)

### CODE REVIEW

**Comment by rboy1** [comment]
Quick question, so posts which have been rebaked before this patch was rolled out would have lost their link counts? Any way to retrieve them?

**Comment by davidtaylorhq** [comment]
Unfortunately not, the records were erased from the database. The only possible way would be to extract the old values from an old database backup.

**Comment by rboy1** [comment]
Ok. One more question. How long before this rolls out to your enterprise customers ?

**Comment by davidtaylorhq** [comment]
Sorry for the delay in response @rboy1 - this fix has already been deployed across all of our hosting. If you notice any further issues please do let us know.

**Pull request merged**
