### PR TITLE
Update Vagrantfile to install ruby 2.0

### PR DESCRIPTION
**Pull request by rubo77**
This installs Ruby 2.0 on the Ubuntu 12.04 box. Otherwise installation fails.

### CODE REVIEW

**Comment by rubo77** [comment]
It seems this is not enough, there has to be adapted the Path to ruby gems in the rest of the script also

**Comment by rubo77** [comment]
At least there has to be installed `ruby-dev` as well
I now try 

    config.vm.box = "ubuntu14.04"
    config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box"

omnibus plugin for chef: 

    # vagrant plugin install vagrant-omnibus --verbose
    config.omnibus.chef_version = :latest

and then the provision line

    config.vm.provision :shell, :inline => "set -x; PS4='executing: '; apt-get -qq update && apt-get -y install ruby2.0 ruby-dev build-essential && gem install chef --no-rdoc --no-ri --conservative --verbose"

**Comment by rubo77** [comment]
Also with a Ubuntu 15.04 vagrant box discourse does not installed completely.

It crashes when calling the chef script:

    ERROR: Cookbook loaded at path(s) [/tmp/vagrant-chef-3/chef-solo-1/cookbooks/vim] has invalid metadata: The `name' attribute is required in cookbook metadata
    ==> default: [2015-04-12T01:11:32+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

It seems there is no cookbook for Ubuntu 15.04 yet

**Comment by rubo77** [comment]
It is strange, but it solved without installing ruby2. I don't know exactly how, but what I did was:

 - I enabled Virtualization in my BIOS settings (restart computer and press F2) 
 - prepared the omnibus Plugin for vagrant:  
 
        vagrant plugin install vagrant-omnibus --verbose
 - I installed the omnibus plugin for chef in my vagrant file:  

        config.omnibus.chef_version = :latest
 - I deleted the whole discourse directory and cloned a fresh instance
 - i started `vagrant up`

Now everything runs through fine without error warning.

The last line of output during vagrant is

    ==> default: [2015-04-12T04:13:54-04:00] INFO: Report handlers complete

**Comment by SamSaffron** [comment]
I am pretty sure @eviltrout recently updated this ... going to close for now

**Pull request closed without merging**
