### PR TITLE
Update Twitter App links

### PR DESCRIPTION
**Pull request by itsbhanusharma**
Twitter changed their Developer page link again, apps.twitter.com is now in sunset phase.

### CODE REVIEW

**Comment by tgxworld** [comment]
@itsbhanusharma Please sign the CLA :)

**Comment by itsbhanusharma** [comment]
I already did it yesterday ...

**Comment by itsbhanusharma** [comment]
Just in case that didn't work, I have filled it once again.

**Comment by itsbhanusharma** [comment]
I just updated to latest after the commit was merged, Changes aren't visible for some reason. 
screenshot_2019-01-22 admin - orng central 1

**Pull request merged**
