### PR TITLE
Fix composer for FF14+

### PR DESCRIPTION
**Pull request by xfalcox**
Fix the preview for old versions of Firefox.

https://meta.discourse.org/t/composer-preview-broken-in-firefox-esr-17/33365

### CODE REVIEW

**Comment by riking** [comment]
What's the min-height adjustment do?

**Comment by xfalcox** [comment]
@riking Without min-height it looks like this:

discourse-without-minheight-auto

**Comment by eviltrout** [comment]
I agree the `min-height` seems a bit risky. The `moz` tag seems safe but are we sure that won't break something else?

**Comment by xfalcox** [comment]
@eviltrout I found it strange too, but, the selectors are pretty specific. I'm using it with CSS customization on my instance and it works well. Maybe test with CSS customization on meta?

https://bugzilla.mozilla.org/show_bug.cgi?id=308801

**Comment by eviltrout** [comment]
Cool let's give it a shot! Thanks a lot.

**Pull request merged**
