### PR TITLE
Add incoming email prefer html site setting

### PR DESCRIPTION
**Pull request by mcwumbly**
https://meta.discourse.org/t/linebreaks-in-posts-created-via-email-in-from-gmail/44676/11?u=mcwumbly

### CODE REVIEW

**Comment by ZogStriP** [comment]
Build is failing BTW ;)

**Comment by mcwumbly** [comment]
OK, will sort it out tonight

**Comment by mcwumbly** [comment]
I believe these failures are unrelated:

```
Finished in 11 minutes 33 seconds (files took 9.38 seconds to load)
5186 examples, 6 failures, 9 pending
Failed examples:
rspec ./spec/components/distributed_cache_spec.rb:43 # DistributedCache does not leak state across caches
rspec ./spec/components/distributed_cache_spec.rb:56 # DistributedCache allows coerces symbol keys to strings
rspec ./spec/components/distributed_cache_spec.rb:73 # DistributedCache deletes from other caches
rspec ./spec/components/distributed_cache_spec.rb:88 # DistributedCache clears cache on request
rspec ./spec/components/distributed_cache_spec.rb:66 # DistributedCache sets other caches
rspec ./spec/components/distributed_cache_spec.rb:14 # DistributedCache allows us to store Set
Randomized with seed 58740
```

**Comment by mcwumbly** [comment]
rebased and we're officially green 🍏

**Pull request merged**
