### PR TITLE
Use sRGB Color Profile when converting images

### PR DESCRIPTION
**Pull request by darix**
With the conversion done when uploading or fetching an image we also
lose any embedded color profiles. [This leads to images possibly not rendered
properly in the browsers.][1] To fix the issue we tell imagemagick to render
the image from the embedded color profile to sRGB, which is the color
space used by most browsers.

RT_sRGB.icm is taken from the [RawTherapee repository][2] and is licensed as Public Domain.

[1]: https://meta.discourse.org/t/image-embedded-color-profile/40519
[2]: https://github.com/Beep6581/RawTherapee/blob/master/rtdata/iccprofiles/output/RT_sRGB.icm

### CODE REVIEW

**Comment by coding-horror** [comment]
:+1: looks good, but how risky is this change? It is referencing a local file, will that file be present? @ZogStriP ?

**Comment by darix** [comment]
the profile file is part of the PR

**Comment by ZogStriP** [comment]
How is that different from using the `-colorspace sRGB` option?

**Comment by patdavid** [comment]
@ZogStriP the `-colorspace sRGB` option is a rough conversion and not really appropriate for high quality image conversions (per im docs + forums)

**Comment by patdavid** [comment]
__If__:

* the image has an embedded colorspace, this will convert it to sRGB (appropriate for browser viewing safely).
* the image does _not_ have an embedded colorspace, it's highly likely to be sRGB and thus this conversion will have no effect.
* the image does _not_ have an embedded colorspace, _but it was supposed to_, then it will be obvious to the poster that their colors are off and to fix the problem... :)

**Comment by ZogStriP** [comment]
Let's try it. :+1:

**Comment by darix** [comment]
deployed now.

**Pull request merged**
