### PR TITLE
FEATURE: Improve dice rolling for discourse-narrative-bot

### PR DESCRIPTION
**Pull request by neemiasvf**
https://meta.discourse.org/t/improve-dice-rolling-for-discourse-narrative-bot/115177

### CODE REVIEW

**Comment by SamSaffron** [comment]
I am definitely not comfortable pulling in a whole gem dependency here for this feature. Not against making it a bit better as long as we don't carry too much extra code.

**Comment by coding-horror** [comment]
Yeah a whole new dependency for this is _no bueno_

**Comment by neemiasvf** [comment]
Then I guess I'll have to publish a plugin. The "problem" is *way more* complex than it seems and I'm not interested in reimplementing everything… :/

**Comment by SamSaffron** [comment]
Sorry about it @neemiasvf  I am just super protective about adding more dependencies to Discourse if you can think of a hook on narrative bot that makes implementing your plugin easier feel free to submit a patch

**Comment by neemiasvf** [comment]
That's okay @SamSaffron. I understand how dependencies can be a headache.

**Comment by ZogStriP** [comment]
> The "problem" is _way more_ complex than it seems and I'm not interested in reimplementing everything… :/

Is it really though? I guess you could just start with the most used notations?

**Comment by neemiasvf** [comment]
It kind of is. Not the actual calculation of the result itself, but the
parser. Plus, the gem is beautifully written. In fact, I could integrate
the gem implementation to the core code. I'm not up to implementing a new
solution to the same problem, but I could recycle the same code. Would that
be acceptable? :)

**Comment by RvdE** [comment]
I'd be very interested in the enhanced dice rolling as well. I've converted from vBulletin 4 a couple of days ago where I had a dice roller plugin that could do math as well. A plugin would be neat as well.

**Pull request closed without merging**
