### PR TITLE
DEV: Remove duplicate emoji files

### PR DESCRIPTION
**Pull request by pmusaraj**
These are duplicates, and one of them caused an issue on macOS, because the file had changed, it appeared as a modified file immediately after a pull. 

More details about this git issue in https://stackoverflow.com/questions/2016404/git-status-shows-modifications-git-checkout-file-doesnt-remove-them/2016426#2016426

### CODE REVIEW

**Review by CvX — APPROVED** [review]
Robin [mentioned](https://github.com/discourse/discourse/pull/15493#issuecomment-1007777841) that Falco also had a solution, but I don't see a PR so… 😛🚢

**Comment by pmusaraj** [comment]
Ah, in that case, maybe let's wait for @xfalcox to have a look.

**Comment by xfalcox** [comment]
> Ah, in that case, maybe let's wait for @xfalcox to have a look.

Fix is https://github.com/jjaffeux/emoji-db/pull/9

**Comment by pmusaraj** [comment]
> > Ah, in that case, maybe let's wait for @xfalcox to have a look.
> 
> Fix is [jjaffeux/emoji-db#9](https://github.com/jjaffeux/emoji-db/pull/9)

Cool, then I'll merge this, it's essentially the same as your PR (but in separate repos).

**Pull request merged**
