### PR TITLE
Phpbb3.2 preliminary support

### PR DESCRIPTION
**Pull request by pfaffman**
@gschlager here you go! This worked for the site I imported, though it definitely needs a bit more work.

### CODE REVIEW

**Comment by gschlager** [comment]
Thanks! I'm planning on getting this into tip-top shape by the end of December. I guess my XML to Markdown converter needs a few refinements for better integration with the existing import script.

**Comment by pfaffman** [comment]
I hope this helps! It's not as beautiful as your code, but it did work for one particular site.

**Comment by bikezilla** [comment]
@pfaffman I tried running this script on an experimental phpbb3.2 migration, but I ran into an error:
```
Traceback (most recent call last):
        9: from script/import_scripts/phpbb3.rb:11:in `<main>'
        8: from script/import_scripts/phpbb3.rb:12:in `<module:ImportScripts>'
        7: from script/import_scripts/phpbb3.rb:30:in `<module:PhpBB3>'
        6: from script/import_scripts/phpbb3.rb:30:in `require_relative'
        5: from /var/www/discourse/script/import_scripts/phpbb3/importer.rb:4:in `<top (required)>'
        4: from /var/www/discourse/script/import_scripts/phpbb3/importer.rb:4:in `require_relative'
        3: from /var/www/discourse/script/import_scripts/phpbb3/importers/importer_factory.rb:11:in `<top (required)>'
        2: from /var/www/discourse/script/import_scripts/phpbb3/importers/importer_factory.rb:11:in `require_relative'
        1: from /var/www/discourse/script/import_scripts/phpbb3/support/text_processor.rb:1:in `<top (required)>'
/var/www/discourse/script/import_scripts/phpbb3/support/text_processor.rb:1:in `require_relative': cannot load such file -- /var/www/discourse/script/import_scripts/phpbb3/support/markdown_node (LoadError)

```
It looks like you've forgotten to add the `markdown_node.rb` file. Any chance you can add it?

**Comment by pfaffman** [comment]
Sorry. Here it is. I'll try to submit it next week but here it is.

```
module BBCode
  class MarkdownNode
    # @return [String]
    attr_reader :xml_node_name

    # @return [MarkdownNode]
    attr_reader :parent

    # @return [Array<MarkdownNode>]
    attr_reader :children

    # @return [String]
    attr_accessor :text

    # @return [String]
    attr_accessor :prefix

    # @return [String]
    attr_accessor :postfix

    # @return [Integer]
    attr_accessor :prefix_newlines

    # @return [Integer]
    attr_accessor :postfix_newlines

    # @return [String]
    attr_accessor :prefix_children

    # @param xml_node_name [String]
    # @param parent [MarkdownNode]
    def initialize(xml_node_name:, parent:)
      @xml_node_name = xml_node_name

      @text = ""
      @prefix = ""
      @postfix = ""

      @prefix_newlines = 0
      @postfix_newlines = 0

      @parent = parent
      @children = []

      @parent.children << self if parent
    end

    def enclosed_with=(text)
      @prefix = @postfix = text
    end

    def root?
      @parent.nil?
    end

    def skip_children
      @children = nil
    end

    def to_s
      "name: #{xml_node_name}, prefix: #{prefix}, text: #{text}, children: #{children.size}, postfix: #{postfix}"
    end
  end
end
```

**Comment by gschlager** [comment]
I'm closing because it's quite broken. It will be superseded by my work in https://github.com/gschlager/discourse/tree/phpbb3

@pfaffman Thanks for testing my converter in its early stage. I've already fixed the problems you noticed and improved the converter a lot.

**Pull request closed without merging**
