### PR TITLE
Enhance, refactor populate.thor

### PR DESCRIPTION
**Pull request by pthomas551**
Enhance lib/tasks/populate.thor to allow for the creation of seed users and multiple seed topics.

Includes refactoring and use of ffaker gem to populate users and post data.

### CODE REVIEW

**Comment by coding-horror** [comment]
Didn't you work on the 999 reply post generation @nlalonde ? How does this look to you?

**Comment by nlalonde** [comment]
Is it possible to do this without adding a new gem to the Gemfile? I would rather avoid adding a gem dependency for this, which is why I originally made the `hipster_words`, `image_posts`, and `wikipedia_posts` methods to populate data. We already have the [Fabrication gem](https://www.fabricationgem.org/), so maybe it can be used to generate users and other data.

**Comment by pthomas551** [comment]
@nlalonde OK, will rework to avoid gem dependencies.

**Comment by pthomas551** [comment]
Now reworked, gem dependency should be removed now. Also for future reference the hipster_words method generates amusing emails ;)

**Comment by nlalonde** [comment]
Thanks, looks good! 👍

**Pull request merged**
