### PR TITLE
DEV: Run tests with new chrome headless

### PR DESCRIPTION
**Pull request by tgxworld**
New headless shares the same implementation as the chrome browser
instead of being a seprate implementation of its own.

See https://developer.chrome.com/articles/new-headless/ for more
details

### CODE REVIEW

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
hmmm system test failure probably needs to be pristine prior to merging this....

**Comment by tgxworld** [comment]
Failure here seems to be consistent so probably legit.

**Comment by xfalcox** [comment]
:eyes:

https://github.com/discourse/discourse/pull/20940

**Comment by tgxworld** [comment]
@xfalcox Yea I was working off your PR as it seemed to be a draft. I have also updated our qunit test suite to use the new chrome headless mode. I ensured that the commit has been co-authored by you. However, it seems like there is a legit failure with our system tests so this can't be merged yet.

**Comment by xfalcox** [comment]
Perfect, let me close the other one then.


Btw so far I think the failures in this mode may be real bugs and not the browser fault.

**Comment by jjaffeux** [comment]
Spec failure fixed in https://github.com/discourse/discourse/commit/8d2ae1e4a654e40094f53a51472e648f043457ed will merge this soon

**Pull request merged**
