### PR TITLE
Create installing discourse on ibm cloud

### PR DESCRIPTION
**Pull request by Sumithkr**
Add documents on Discourse Documentation page
how to install Discource on ibm cloud

[Discourse.docx](https://github.com/discourse/discourse/files/5610666/Discourse.docx)

### CODE REVIEW

**Comment by eviltrout** [comment]
I noticed this was drafted on meta: 

https://meta.discourse.org/t/installing-discourse-on-ibm-cloud/170914

I feel that is a much better place for this document than in core discourse.

**Comment by Sumithkr** [comment]
i think it better on formal documentation
this docs have instructions that how to installing discourse on ibm cloud

**Comment by eviltrout** [comment]
Sorry, but I disagree.

**Comment by Sumithkr** [comment]
https://mariadb.com/kb/en/installing-mariadb-on-ibm-cloud/
check this
i think it better on your documentation as other platforms also upload it
that docs have all instruction how to install discourse on ibm cloud

**Pull request closed without merging**
