### PR TITLE
DEV: introduces prettier for core hbs files

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by jjaffeux** [comment]
cc @eviltrout @ZogStriP @romanrizzi

**Comment by jjaffeux** [comment]
@eviltrout https://github.com/discourse/discourse/pull/7678/files#diff-c8c45f49ff4abc8b46ee342667f0d839R53 as discussed

I will try to see if we can at least have this fixed

**Comment by ZogStriP** [comment]
Yeah, that one is really bad 😲

**Comment by romanrizzi** [comment]
The only downside of the PR is that removes a lot of blank lines that were introduced to improve readability

**Comment by jjaffeux** [comment]
> The only downside of the PR is that removes a lot of blank lines that were introduced to improve readability

That doesn't bother me much, it was not consistent at all

**Comment by SamSaffron** [comment]
I also support the "not thinking" movement. It does touch lots of stuff though so lets hold off till after 2.3

**Comment by jjaffeux** [comment]
Update the PR, few things getting better, only one last remaining thing is truly bohering me.

**Pull request closed without merging**
