### PR TITLE
DEV: makes discourse-styleguide a core plugin

### PR DESCRIPTION
**Pull request by jjaffeux**
This plugin is only useful for developpers, however, making it core allows us to centralize any component modification in one commit.

This integration also adds a new site_setting: `styleguide_admin_only` which allows to enable a styleguide on a live site while restricting visibility to admins only.

By default, styleguide is disabled.

### CODE REVIEW

**Comment by jjaffeux** [comment]
Note this commit is also adding specs for site settings, and fixing a lot of linting issues required to be part of our core lint CI.

**Comment by davidtaylorhq** [comment]
I suspect this will cause a repeat of https://meta.discourse.org/t/rebuilds-fail-for-anyone-with-discourse-narrative-bot-in-app-yml/63410?u=david

One workaround is to rename the plugin to `styleguide` rather than `discourse-styleguide` (then the naming style will match `poll` and `lazy-yt`)

**Comment by jjaffeux** [comment]
> I suspect this will cause a repeat of https://meta.discourse.org/t/rebuilds-fail-for-anyone-with-discourse-narrative-bot-in-app-yml/63410?u=david
> 
> One workaround is to rename the plugin to `styleguide` rather than `discourse-styleguide` (then the naming style will match `poll` and `lazy-yt`)

yes I was wondering about this, ok cool, will rename. I actually maybe I will rename it discourse-storybook, what do you think @eviltrout ?

**Comment by jjaffeux** [comment]
I went with styleguide finally, FWIW, I tried with both this enabled and discourse-styleguide installed, it seems to work, it's ofc not recommended as they share the same /styleguide endpoint but that doesn't seems to create any big issue.

**Review by CvX — APPROVED** [review]
Let's get this ~party started~ merged!

**Comment by CvX** [comment]
(…after fixing those linting issues 😉)

**Review by davidtaylorhq — APPROVED** [review]

**Comment by jjaffeux** [comment]
> (…after fixing those linting issues 😉)

Should be good now, damn replacing strings changed the length of a line which made it not linting anymore

**Pull request merged**
