### PR TITLE
UX: improve emoji alignment for text

### PR DESCRIPTION
**Pull request by chapoi**
Changing the alignment of emoji's to text-bottom for a bit of improvement:

**before**
image

**after**
image

### CODE REVIEW

**Comment by CvX** [comment]
Just a bit of QA Q&A 😉 

- does it look right in the topic titles/header?
- does it look right in chat?
- does it look right with custom (user uploaded) emoji?
- is "🏎️" emoji (probably the most bottom-skewed one) reasonably placed on the text line? 😃

**Review by CvX — APPROVED** [review]
Approving, but a second opinion is needed if you'd like to squeeze it into 3.0 release

**Comment by nbianca** [comment]
If you feel confident, I am fine with it too.

**Comment by jjaffeux** [comment]
@chapoi I think you can merge it Monday if you want please.

**Pull request merged**
