### PR TITLE
phpbb-import-script: move bbcode_to_md to before other text processing

### PR DESCRIPTION
**Pull request by ryantm**
This seems to fix the issue I reported in
https://meta.discourse.org/t/import-script-phpbb/40424

### CODE REVIEW

**Comment by SamSaffron** [comment]
@ZogStriP  your call.

**Comment by ZogStriP** [comment]
I think the better fix here is to submit a PR to `bbcode_to_md` instead so that it doesn't change `https` to `http`.

**Comment by ryantm** [comment]
@ZogStriP I did fix that. This is a separate problem, I think.

**Comment by ZogStriP** [comment]
Great, let's merge it then ;)

**Pull request merged**
