### PR TITLE
FIX: Embedded Youtube videos lacking margin at bottom

### PR DESCRIPTION
**Pull request by gotens1211**
The markdown was not adding margin in the embedded videos when there was more then one new line. Changed the cook function arguments for youtube videos now it is working fine.

https://meta.discourse.org/t/double-spaced-youtube-embeds-lack-bottom-padding/55748

### CODE REVIEW

**Comment by tgxworld** [comment]
Hmm perhaps we can just add the margins using CSS?

**Comment by coding-horror** [comment]
just CSS is preferred

**Comment by gotens1211** [comment]
Actually the method i used first was conserving the behaviour of the markdown and also the files of lazyYt plugin for youtube videos used by discourse said update if necessary 😅. The video divs are separated with a br tag when there is a newline present in the markdown but if there are more then 
one newlines the br tag is absent which is causing the problem.

I have updated the css file of lazyYt to give some margin to the video container, should i push it ?

**Comment by ZogStriP** [comment]
> I have updated the css file of lazyYt to give some margin to the video container, should i push it ?

Yes, please! 👍

**Comment by ZogStriP** [comment]
Can you remove the cosmetic changes you've made to the `post_analyser.rb` file?

**Comment by ZogStriP** [comment]
Thanks 👍

**Pull request merged**
