### PR TITLE
Add plugin for displaying sidekiq statistic in web ui

### PR DESCRIPTION
**Pull request by davydovanton**
Hello,
I created simple [plugin](https://github.com/davydovanton/sidekiq-statistc) for displaying sidekiq statistic in web UI. Also I have some screenshots for index page with my plugin:
screenshot 2015-09-03 01 22 32
screenshot 2015-09-03 01 22 43
screenshot 2015-09-03 01 22 50

/cc @SamSaffron

### CODE REVIEW

**Comment by davydovanton** [comment]
done :+1:

**Comment by SamSaffron** [comment]
cool, thanks so much 

Are we on a "recent enough" sidekiq?

**Comment by davydovanton** [comment]
@SamSaffron yep, you have `3.4.2` version :)

**Comment by davydovanton** [comment]
@SamSaffron thanks for merge! If you have some ideas for my plugin I'll be happy to realize this :blush:

**Pull request merged**
