### PR TITLE
FEATURE: Add /search discovery

### PR DESCRIPTION
**Pull request by riking**
The opensearch.xml results in a "site search engine" being added to Chrome, while the sitelinks search tag results in "Search this website" being added to Google Search.

I moved manifest.json into a more generic MetadataController.

Proof it's working: chrome://settings/searchEngines

image

### CODE REVIEW

**Comment by coding-horror** [comment]
Sure can you review this Tuesday @eviltrout?

**Comment by tgxworld** [comment]
@riking ESLint is failing here :smile_cat:

**Comment by riking** [comment]
Yes, it is. Which is interesting because I didn't touch any of the JS

**Comment by coding-horror** [comment]
Can you rebase this @riking

**Comment by riking** [comment]
@coding-horror rebased

**Comment by coding-horror** [comment]
@eviltrout is this OK to merge?

**Pull request merged**
