### PR TITLE
FIX: forces VPatch.node with svg shadow-root in virtual-dom

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by eviltrout** [comment]
Should we add a test to our app to make sure this doesn't regress? I doubt we'll update virtual-dom, but if someone didn't know you patched it in our vendor area it could break again.

**Comment by jjaffeux** [comment]
I can try to write a test for it, not sure yet how to do it though.

**Comment by SamSaffron** [comment]
what is the call on this patch? when can we merge it?

**Comment by jjaffeux** [comment]
waiting for subseting

**Pull request closed without merging**
