### PR TITLE
 DEV: debundle plugin css assets and don't load if disabled

### PR DESCRIPTION
**Pull request by vinothkannans**

### CODE REVIEW

**Comment by SamSaffron** [comment]
I worry we are sitting on this for so long, is this ready to merge?

**Comment by vinothkannans** [comment]
@SamSaffron it is ready to merge.

**Comment by SamSaffron** [comment]
This looks quite good to me. Maybe @OsamaSayegh can also have a look at this and review cause he is super familiar with this system. 

The only minor thing I am seeing here (which is not new) is the name `asset_name` is quite confusing imo, maybe we should call it `plugin_directory_name` to be explicit or something else?

**Comment by vinothkannans** [comment]
The variable `asset_name` is now renamed to `plugin_directory_name`. And I added a minor fix too. cc @OsamaSayegh

**Pull request merged**
