### PR TITLE
Add locale for Vietnamese

### PR DESCRIPTION
**Pull request by khoa-le**
I have added Vietnamese locale, and also update Transifex.com translation. Please review it. Thanks!

### CODE REVIEW

**Comment by gschlager** [comment]
I'm quite sure the locale should be `vi` instead of `vi_VN`.

**Comment by khoa-le** [comment]
I followed that [link](https://meta.discourse.org/t/how-to-add-a-new-language/14970). Do I need to update `vi_VN` to `vi`?

**Comment by gschlager** [comment]
Yes, unless you tested it with `vi_VN` and it worked.
I didn't test it myself, but I assume it should be `vi` since the [plurals.rb](https://github.com/discourse/discourse/blob/master/config/locales/plurals.rb#L108) uses `vi`.

**Comment by khoa-le** [comment]
Sure, it worked. I deployed to [http://forum.nhadep24.com](http://forum.nhadep24.com), and can change the config to vi_VN.

**Comment by ZogStriP** [comment]
I agree with @gschlager here, we should follow rails' convention and use `vi` instead of `vi_VN`. Can you make that change @khoa-le?

**Comment by khoa-le** [comment]
Thank you, @ZogStriP and @gschlager. I will update it.

**Comment by gschlager** [comment]
One thing is still missing. You need to add the language mapping `vi_VN: vi` to [.tx/config on line 3](https://github.com/discourse/discourse/blob/master/.tx/config#L3).

**Comment by SamSaffron** [comment]
Thanks!

**Pull request merged**
