### PR TITLE
Add s3 region

### PR DESCRIPTION
**Pull request by lhkjacky**

### CODE REVIEW

**Comment by SamSaffron** [comment]
@andrewschleifer any concern around adding ap_east_1? should we go ahead and merge?

**Comment by andrewschleifer** [comment]
Shouldn't be a problem adding the region key. Translations should be submitted in [CrowdIn](https://translate.discourse.org/discourse), though.

**Comment by SamSaffron** [comment]
@lhkjacky please remove the zh_TW translation and then we can go ahead and merge.

**Review by CvX — APPROVED** [review]

**Comment by CvX** [comment]
Thank you!

**Pull request merged**
