### PR TITLE
Added S3 region eu-south-1 Milan

### PR DESCRIPTION
**Pull request by agiovacchini**

### CODE REVIEW

**Comment by xfalcox** [comment]
Hey @agiovacchini, thanks for the PR!

Can you please follow the CLA assistant instructions and sign the our CLA?

**Comment by gschlager** [comment]
> **andrea** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by agiovacchini** [comment]
Ok, I've added the email used by git client in the computer I used for commit to my githut account, now I think it should be ok, can you confirm?

**Comment by gschlager** [comment]
@agiovacchini Could you squash your commits and ensure that there's only 1 commit with your correct email address? Currently there are two. You can use `git push --force` afterwards. Or, if it is easier for you, you can create a new PR with the correct commit.

**Comment by agiovacchini** [comment]
@gschlager Done, thank you

**Review by eviltrout — APPROVED** [review]

**Pull request merged**
