### PR TITLE
change condition when displaying s3 uploads, rename S3 vars

### PR DESCRIPTION
**Pull request by majakomel**
Applied required changes from https://github.com/discourse/discourse/pull/5829

@jjaffeux, can you take a look?

### CODE REVIEW

**Comment by jjaffeux** [comment]
@majakomel I don’t know much about our upload code. Is this expected we don’t have to change anything here https://github.com/discourse/discourse/blob/master/lib/pretty_text.rb#L213?

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!
Simone Bartolini

________________________________

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Comment by Giacomino1** [comment]
I closed my account and then I had to close all the trheads out of kindness otherwise I would have to trash the emails and then I hope that this explanation is enough. Thank you!!!

Simone Bartolini

________________________________

**Pull request merged**
