### PR TITLE
DEV: User email test optimization

### PR DESCRIPTION
**Pull request by danielwaterworth**
This PR removes unnecessary fabrications of user emails. It wasn't quite the speed boost I was hoping for, but it does reduce the number of fabricated objects by ~7,000 and speeds up the tests by ~20s.

This PR makes the default `:user` fabricator create a user with a single email address. When you need a user with a secondary email, you can use the old `:user` fabricator which has been renamed to `:user_with_secondary_email`.

### CODE REVIEW

**Comment by tgxworld** [comment]
Thank you for the change here. We should default `Fabricactor(:user)` to one that only contains a single primary email IMO. Any spec that requires  a secondary email can fabricate the user separately.

**Comment by SamSaffron** [comment]
Agree with @tgxworld here ... we should change the default.

**Comment by danielwaterworth** [comment]
I'm glad we agree. That is the effect of this PR.

**Comment by danielwaterworth** [comment]
I was expecting more of the tests to depend on fabricated users have multiple email addresses (which is why I did it this way with diffs affecting all of the specs). Since this wasn't the case, I can make this PR much easier to review by just changing the fabricators and fixing up any broken tests afterwards.

**Comment by SamSaffron** [comment]
cool, yes, please do so!

**Comment by danielwaterworth** [comment]
Only three tests relied on having a user with multiple email addresses.

**Comment by tgxworld** [comment]
Thank you for this @danielwaterworth  :+1:

**Comment by danielwaterworth** [comment]
@tgxworld, thank you for merging it :smile:

**Pull request merged**
