### PR TITLE
Added Lets Encrypt Information

### PR DESCRIPTION
**Pull request by djtye**
Well got to make sure forums become SSL friendly ;)

### CODE REVIEW

**Comment by coding-horror** [comment]
I think better to add it to the links at the bottom in "bonus stuff you can do after install", instead..

**Comment by djtye** [comment]
I will also if its needed modify the discourse_docker to comment it out :)

**Comment by coding-horror** [comment]
Sure, having it commented out there is smart, I can support that!

**Comment by djtye** [comment]
I done that, I will add it to the bonus stuff. I had trouble finding out about Lets Encrypt for Discourse, need to make people aware :)

**Pull request closed without merging**
