### PR TITLE
TopicViewItem: Do not store IP of logged in users

### PR DESCRIPTION
**Pull request by riking**
Second part of IP logging removals

### CODE REVIEW

**Comment by riking** [comment]
Only remaining test failure is a flake.

**Comment by SamSaffron** [comment]
looks good, but I think you are missing a test here, also can you send a separate PR for the flaky spec, so @jjaffeux  can merge in and fix.

**Comment by SamSaffron** [comment]
I think this is reasonably safe but waiting till post 2.1 on it cause index work can be expensive and potentially block stuff

**Comment by SamSaffron** [comment]
I am fine with this, lets try it out

**Comment by riking** [comment]
Oops, I let that sit for a while didn't I

**Pull request merged**
