### PR TITLE
DEV: Fix Settings/Interface UI breaking on Ember CLI

### PR DESCRIPTION
**Pull request by CvX**
Fixes failures in user-preferences-interface-test on Ember CLI.

### CODE REVIEW

**Comment by pmusaraj** [comment]
Sure, I can take a look (probably early next week).

**Comment by CvX** [comment]
Thank you! 🙌

**Comment by pmusaraj** [comment]
Your changes look good @CvX, and the stub should now work in ember-cli. We might need a third person to review this?

**Comment by CvX** [comment]
Yeah, GH doesn't allow approving own PRs 😛

**Review by davidtaylorhq — APPROVED** [review]

**Pull request merged**
