### PR TITLE
Update utilities.js.es6

### PR DESCRIPTION
**Pull request by quangbuule**
The PR is fix this:
image

### CODE REVIEW

**Comment by SamSaffron** [comment]
I totally believe that this fixes an issue, but we need a test here, can you add one?

**Comment by SamSaffron** [comment]
@quangbuule any news on this?

**Comment by quangbuule** [comment]
Hi Sam, sorry for not replying your last comment. My workload this week was just little heavier than normal so I couldn't have time for this one, will get back on this this Weekend ;).

**Comment by SamSaffron** [comment]
No worries! thanks

**Comment by SamSaffron** [comment]
Still waiting on a test here, sorry, going to close this for now, can you resubmit with a test?

**Pull request closed without merging**
