### PR TITLE
FIX: add X-Robots-Tag header for check_xhr-covered GET actions, too

### PR DESCRIPTION
**Pull request by artemv**
see https://meta.discourse.org/t/missing-x-robots-tag/152593/3 for context

### CODE REVIEW

**Comment by eviltrout** [comment]
Can you add a test for this? We rarely accept fixes without tests.

**Comment by artemv** [comment]
> Can you add a test for this? We rarely accept fixes without tests.

It would be easy if there was an existing non-json GET action in Discourse that 
* allowed non-logged visitors
* didn't skip `check_xhr` filter

Do you know such action? Otherwise I can add such action in spec code similarly to what plugins do but this sounds hacky. Or fine?

**Comment by eviltrout** [comment]
Why would a GET for html not skip xhr? I don't understand now that I've read in more detail.

**Comment by artemv** [comment]
> Why would a GET for html not skip xhr? I don't understand now that I've read in more detail.

Initially my plugin' action didn't skip check_xhr, and it was happily rendering empty layout then loaded page contents with XHR - the same way e.g. `/admin` does (its HTML version doesn't skip `check_xhr`), but in my case for not logged in users. This doesn't look wrong to me by itself. But the `add_noindex_header` not working in this case does look wrong.

**Comment by eviltrout** [comment]
@artemv I am still super confused here. Where does `/admin` render HTML without skipping xhr?

**Comment by artemv** [comment]
> @artemv I am still super confused here. Where does `/admin` render HTML without skipping xhr?

At standard Discourse. Here, I've added logging to `check_xhr` and requested `localhost:3000/admin`: 
bundle exec rails server 2020-05-26 17-43-46

**Comment by eviltrout** [comment]
Aha I understand now, sorry what confused me is `check_xhr` does not ensure that XHR is present, it bootstraps the app for any GET if nothing special is supposed to happen.

It looks like the `/groups` path will respond to anonymous requests and doesn't skip xhr, so your test can use that path.

**Comment by artemv** [comment]
@eviltrout I'm glad you figured it out - I was like, ugh, let's annotate `check_xhr` filter to give that guy more context about it. Wait, he's the author? Eh. :) It was long ago though, understood!

**Comment by artemv** [comment]
@eviltrout just in case - I've added a test, please review

**Pull request merged**
