### PR TITLE
UX: Show user card on load

### PR DESCRIPTION
**Pull request by venarius**
This shows the user card even before it finished loading.

### Before
Peek 2019-04-15 19-31

### After
Peek 2019-04-15 20-10

&nbsp;
&nbsp;
This is a first mockup I made for this 🙂 I fiddled a lot around with different animations and even slower opacity fading of the modal but everything felt bad to me. That's why I kept it that way.

Also as far as I know the avatar can't be shown during load, because all the modal knows from the user is his username.

For: https://meta.discourse.org/t/user-more-info-cache-results-and-render-optimization/17578

### CODE REVIEW

**Comment by venarius** [comment]
Changed style of animation and use the Cache:

Peek 2019-04-19 00-08

**Comment by coding-horror** [comment]
oooh super nice 🤩

**Comment by coding-horror** [comment]
If this looks OK we should merge it @ZogStriP

**Comment by ZogStriP** [comment]
Cool, let's try it 👍

**Pull request merged**
