### PR TITLE
FEATURE: Onebox for Embed Motoko

### PR DESCRIPTION
**Pull request by rvanasa**
This PR adds custom URL previews for [Embed Motoko](https://embed.smartcontracts.org/motoko), an interactive code snippet service. Embed Motoko is currently registered as an [Embedly](https://embed.ly) provider for use in Medium stories, so we hope to also make this tool available on Discourse forums via Onebox.

### CODE REVIEW

**Comment by pmusaraj** [comment]
@rvanasa thanks. I'm curious though, is this going to output something different from a generic Onebox? Can you explain what the differences would be?

**Comment by rvanasa** [comment]
@pmusaraj Thank you for taking a look! These embed snippets work best with adaptive iframe heights (since users can directly edit and run the code snippets). To my understanding, it will require a custom Onebox to get this working as expected. We ran into issues with this while becoming an Embedly provider, so I anticipate a custom solution will be necessary here.

**Review by pmusaraj — APPROVED** [review]

**Comment by rvanasa** [comment]
This should be ready to merge. Would it be possible to include this basic implementation for the time being? That way, I could start setting up the responsive embed height in a separate PR without having to get approval for each CI run (as a first-time contributor).

Thanks, and happy holidays!

**Comment by pmusaraj** [comment]
Thanks @rvanasa, happy holidays to you as well.

**Pull request merged**
