### PR TITLE
DEV: make user status a tracked property

### PR DESCRIPTION
**Pull request by AndrewPrigorshnev**

### CODE REVIEW

**Comment by CvX** [comment]
@davidtaylorhq I'm losing track (badum tsss 😄) of what works with what – any potential issues with `@tracked` inside an EmberObject model?

**Comment by AndrewPrigorshnev** [comment]
> @davidtaylorhq I'm losing track (badum tsss 😄) of what works with what – any potential issues with `@tracked` inside an EmberObject model?

Just for context, I needed it in order to make status on the new sidebar (on direct message channels) live. This worked out well, haven't noticed any side effects so far.

**Comment by davidtaylorhq** [comment]
I think this is technically fine - computed properties are intercompatible with `@tracked`.

However, it feels a bit weird to have this as the **only** tracked property in the user model. I think I'd prefer to avoid tracked in models for now, and then we'll migrate to them in one go.

>  I needed it in order to make status on the new sidebar (on direct message channels) live

When accessing a property on an EmberObject from inside an autotracked native getter, you need to use `user.get("userStatus")` to make it update live. (full list of requirements is in internal `/t/72006`). I think if you do that, then `@tracked` shouldn't be required. Can you try it and see if it helps?

(also, can we add a test for this live-update?)

**Comment by AndrewPrigorshnev** [comment]
> When accessing a property on an EmberObject from inside an autotracked native getter, you need to use `user.get("userStatus")` to make it update live.

I've tried it, and it works. So no need to make the property tracked. Thank you, David! I'm closing this PR.

> (also, can we add a test for this live-update?)

Tests are in the Discourse-Chat PR - https://github.com/discourse/discourse-chat/pull/1185.

**Pull request closed without merging**
