### PR TITLE
Add Rubinius to Build Matrix with Allowed Failure

### PR DESCRIPTION
**Pull request by bjfish**
Please add Rubinius to the build matrix with failure allowed.

I am trying to add this to ensure Discourse works in Rubinius. Thank you.

### CODE REVIEW

**Comment by SamSaffron** [comment]
no probs, curious to see performance and changes needed to get this going

**Comment by jomaxro** [comment]
Hey @bjfish,

We’ve been digging around the repo for Discourse to make sure we have CLAs from everybody. We looked, but we couldn’t find the CLA for your commit above. Would you be able to quickly fill the CLA at https://discourse.org/cla? Sorry for the inconvenience.

**Comment by bjfish** [comment]
@jomaxro Yes, I've completed the CLA.

**Comment by jomaxro** [comment]
Much appreciated, thanks!

**Pull request merged**
