### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by JimmyJammyDodger**
@discourse-translator-bot keep_translations

### CODE REVIEW

**Comment by CvX** [comment]
we need that magic incantation that tells the translation-bot to preserve existing translations for those strings (

**Comment by CvX** [comment]
found it! it's:

> @discourse-translator-bot keep_translations

in the commit's message (see e.g. https://github.com/discourse/discourse/pull/24656)

**Comment by JimmyJammyDodger** [comment]
> found it! it's:
> 
> > @discourse-translator-bot keep_translations
> 
> in the commit's message (see e.g. #24656)

Have I done that right?

**Review by CvX — APPROVED** [review]
Be careful when merging 😛 – by default GH doesn't reuse PR's updated description as the merge commit message (it uses the original commit instead, so make sure you copy the magic text again 😅)

**Comment by JimmyJammyDodger** [comment]
Now I'm scared to press the button :)

I have this button:

image

If I press it will I get the option to re-add the magic spell?

**Comment by CvX** [comment]
Yup! You'll have the merge UI to set the commit message and details 😃

**Pull request merged**
